### ISSUE TITLE
AssertionError: Additivity check failed in TreeExplainer! Please report this on GitHub.

### ISSUE THREAD

**Issue by Research2017** [shap/shap#1013]
Hello,

I am getting the following error message asking to report this on Github.

Training until validation scores don't improve for 50 rounds
[1000]	valid_0's binary_logloss: 0.671314
Early stopping, best iteration is:
[1912]	valid_0's binary_logloss: 0.66831
 97%|=================== | 4470/4601 [00:32<00:00]       Traceback (most recent call last):
  File "Epi.py", line 80, in <module>
    shap_values = explainer.shap_values(teX)
  File "/usr/local/lib/python3.7/site-packages/shap/explainers/tree.py", line 327, in shap_values
    self.assert_additivity(out, self.model.predict(X))
  File "/usr/local/lib/python3.7/site-packages/shap/explainers/tree.py", line 438, in assert_additivity
    assert np.max(np.abs(val - model_output) / (np.abs(val) + 1e-2)) < 1e-2, err_msg
AssertionError: Additivity check failed in TreeExplainer! Please report this on GitHub.

Could you tell me how to fix this, please?

Many thanks.

**Comment by prathyushapatel** [comment]
@Research2017  Adding "check_additivity=False" should work fine.

**Comment by Research2017** [comment]
Great, thank you
