### ISSUE TITLE
Fetch argument None has invalid type <class 'NoneType'> error

### ISSUE THREAD

**Issue by vasconcelos-luiz** [shap/shap#1017]
I'm trying to evaluate a tensorflow model. But I keep hitting the folowing error when I access the shap_values:

```
Traceback (most recent call last):

  File "<ipython-input-17-9e7c19739be9>", line 1, in <module>
    runfile('/Prod codes/NN_TF_nested_SHAP.py', wdir='/Prod codes')

  File "\.conda\envs\TF14\lib\site-packages\spyder_kernels\customize\spydercustomize.py", line 668, in runfile
    execfile(filename, namespace)

  File "\.conda\envs\TF14\lib\site-packages\spyder_kernels\customize\spydercustomize.py", line 108, in execfile
    exec(compile(f.read(), filename, 'exec'), namespace)

  File "G/Prod codes/NN_TF_nested_SHAP.py", line 319, in <module>
    shap_values = e.shap_values(X_test)

  File "\.conda\envs\TF14\lib\site-packages\shap\explainers\gradient.py", line 108, in shap_values
    return self.explainer.shap_values(X, nsamples, ranked_outputs, output_rank_order)

  File "\.conda\envs\TF14\lib\site-packages\shap\explainers\gradient.py", line 248, in shap_values
    grads.append(self.run(self.gradient(find), self.model_inputs, batch))

  File "\.conda\envs\TF14\lib\site-packages\shap\explainers\gradient.py", line 295, in run
    return self.session.run(out, feed_dict)

  File "\.conda\envs\TF14\lib\site-packages\tensorflow\python\client\session.py", line 889, in run
    # Validate and process fetches.

  File "\.conda\envs\TF14\lib\site-packages\tensorflow\python\client\session.py", line 1105, in _run
    return []

  File "\.conda\envs\TF14\lib\site-packages\tensorflow\python\client\session.py", line 414, in __init__
    for fetch in self._fetch_mapper.unique_fetches():

  File "\.conda\envs\TF14\lib\site-packages\tensorflow\python\client\session.py", line 234, in for_fetch
    # Look for a handler in the registered expansions.

  File "\.conda\envs\TF14\lib\site-packages\tensorflow\python\client\session.py", line 341, in __init__
    return self._unique_fetches

  File "\.conda\envs\TF14\lib\site-packages\tensorflow\python\client\session.py", line 341, in <listcomp>
    return self._unique_fetches

  File "\.conda\envs\TF14\lib\site-packages\tensorflow\python\client\session.py", line 231, in for_fetch
    elif isinstance(fetch, dict):

TypeError: Fetch argument None has invalid type <class 'NoneType'>

```

I embedded my training inside the function run_train... made it easier to implement cross-validation...
I also create the graph inside a function that returns the graph and a list of tensors

```
with tf.Session(graph=graph) as sess:
    
    losses, accs, val_accs = run_train(sess, X_train, y_train, X_val, y_val, tensors,opt_model_hp)
    acc_test, y_score, test_logits  = sess.run([tensors["accuracy"], tensors["predicted"], tensors["logits"]], feed_dict={'X:0': X_test, 'y:0': y_test})
    
    #SHAP
    e = shap.GradientExplainer((tensors["input"],tensors["output"]),X_train,session=sess)
    shap_values = e.shap_values(X_test)
```  
Any ideas??

**Comment by niloofardadras** [comment]
@luizhav90 hi,
I was wondering if you managed to solve the issue. I am running into the same issue and can not get results
