### ISSUE TITLE
shap.TreeExplainer fails when CatBoost has a categorical feature.

### ISSUE THREAD

**Issue by arose13** [shap/shap#1061]
Shapley isn't working for some reason and I'm getting incredibly obscure errors. Even though CatBoost is throwing the error it must be because of shap as the CatBoost models still work when called directly. I think the problem is because shap calls `get_feature_importance()` with a deprecated argument.

The error is
```python
Traceback (most recent call last):
  File "C:/Users/antho/.PyCharm2019.3/config/scratches/scratch_5.py", line 17, in <module>
    shap_values = explainer.shap_values(x)
  File "C:\Users\antho\Miniconda3\lib\site-packages\shap\explainers\tree.py", line 247, in shap_values
    phi = self.model.original_model.get_feature_importance(data=X, fstr_type='ShapValues')
  File "C:\Users\antho\Miniconda3\lib\site-packages\catboost\core.py", line 2322, in get_feature_importance
    fstr, feature_names = self._calc_fstr(type, data, thread_count, verbose, shap_mode)
  File "C:\Users\antho\Miniconda3\lib\site-packages\catboost\core.py", line 1287, in _calc_fstr
    return self._object._calc_fstr(type.name, pool, thread_count, verbose, shap_mode)
  File "_catboost.pyx", line 4084, in _catboost._CatBoost._calc_fstr
  File "_catboost.pyx", line 4114, in _catboost._CatBoost._calc_fstr
_catboost.CatBoostError: c:/goagent/pipelines/buildmaster/catboost.git/catboost/libs/data/model_dataset_compatibility.cpp:47: Feature CHAS is Categorical in model but marked different in the dataset

Process finished with exit code 1
```

it's probably due to calling a deprecated argument `fstr_type='ShapValues'`...
```python
File "C:\Users\antho\Miniconda3\lib\site-packages\shap\explainers\tree.py", line 247, in shap_values
    phi = self.model.original_model.get_feature_importance(data=X, fstr_type='ShapValues')
```

The code required to get this error
```python
import shap
import pandas as pd
from catboost import CatBoostRegressor
from sklearn.datasets import load_boston

bunch = load_boston()
x, y = load_boston(True)
x = pd.DataFrame(x, columns=bunch.feature_names)
x['CHAS'] = x['CHAS'].astype(str)
print(x)

model = CatBoostRegressor(1000, cat_features=['CHAS'], verbose=False)
model.fit(x, y)

if __name__ == '__main__':
    explainer = shap.TreeExplainer(model)
    shap_values = explainer.shap_values(x)

```

**Comment by slundberg** [comment]
Thanks for noting this! It was because of a problem noting which feature were categorical when converting the dataframe you passed to a Pool object. I just pushed a fix.
