### ISSUE TITLE
conda install shap cannot import; pip install shap fail; AttributeError: module 'shap' has no attribute 'initjs'

### ISSUE THREAD

**Issue by emmaxunzhao** [shap/shap#1076]
I am using python 3.7.6 on mac os

I have used `conda install -c conda-forge shap
` to install shap, and it has been successfully installed. But when I `import shap`, I have encountered the 

> in <module> shap.initjs()

> AttributeError: module 'shap' has no attribute 'initjs'

And I have tried to uninstall shap with conda and reinstall it with pip, but I have encountered: 

> clang-9: warning: -Wl,-export_dynamic: 'linker' input unused [-Wunused-command-line-argument]
  In file included from shap/_cext.cc:3:
  In file included from /Users/zx/anaconda3/envs/py37/include/python3.7m/Python.h:97:
  /Users/zx/anaconda3/envs/py37/include/python3.7m/bytearrayobject.h:9:10: fatal error: 'stdarg.h' file not found
  #include <stdarg.h>
           ^~~~~~~~~~
  1 error generated.
  error: command 'x86_64-apple-darwin13.4.0-clang' failed with exit status 1
  ----------------------------------------
  

> ERROR: Failed building wheel for shap

Any ideas? needs help!

**Comment by tullydwyer** [comment]
Experiencing the same issue.

I tried both Ubuntu 18 docker image and MacOS 10.14, Python, and Python3.

Running the example code at [https://github.com/slundberg/shap#tree-ensemble-example-with-treeexplainer-xgboostlightgbmcatboostscikit-learnpyspark-models](url)

```
Traceback (most recent call last):
  File "./code/python/shap.py", line 2, in <module>
    import shap
  File "/*****/shap.py", line 5, in <module>
    shap.initjs()
AttributeError: 'module' object has no attribute 'initjs'
```

**Comment by alvarosalgado** [comment]
I uninstalled and reinstalled SHAP. It's working fine.
