### ISSUE TITLE
: Additivity check failed in TreeExplainer! Please report this on GitHub. Consider retrying with the feature_perturbation='interventional' option.

### ISSUE THREAD

**Issue by IonutBarbu** [shap/shap#1105]
Hi Scott,
thanks for having built an incredible package!
unfortunately running into above error when calculating shap_values. I am using xgboost as classifier with following versions
xgboost: 0.81
shap: 0.34
pandas: 1.0.1

Setting `feature_perturbation='interventional` did not help.
Attached feature matrix (DF) 
[code.zip](https://github.com/slundberg/shap/files/4344867/code.zip)
and target variable to help troubleshooting 

Error stack:
Traceback (most recent call last):

  File "C:\Users\Inout Barbu\<scrapped for privacy reasons>\code\modelling.py", line 284, in <module>
    shap_values = explainer.shap_values(X_test_trans,

  File "C:\Continuum\miniconda3\envs\churn\lib\site-packages\shap\explainers\tree.py", line 259, in shap_values
    self.assert_additivity(out, model_output_vals)

  File "C:\Continuum\miniconda3\envs\churn\lib\site-packages\shap\explainers\tree.py", line 438, in assert_additivity
    assert np.max(np.abs(val - model_output) / (np.abs(val) + 1e-2)) < 1e-2, err_msg

AssertionError: Additivity check failed in TreeExplainer! Please report this on GitHub. Consider retrying with the feature_perturbation='interventional' option.

**Comment by LEMTideman** [comment]
Similar problem as what is reported in issues #887 #941, #903 and #1096
