### ISSUE TITLE
DeepExplainer on CUDA raises hook 'deeplift_grad' error

### ISSUE THREAD

**Issue by florianst** [shap/shap#1111]
I am trying to apply DeepExplainer to a torch model. It works fine with tensors and model all on CPU, but I'd like to do it all on GPU for speed reasons. That raises the following error:

```
Traceback (most recent call last):
  File "model.py", line 1333, in <module>
    dataPortions(dbPath, home, mode)
  File "model.py", line 1314, in dataPortions
    trainResult.SHAPexplain()
  File "model.py", line 837, in SHAPexplain
    shap_values = explainer.shap_values(to_explain)
  File "/home/user/.local/lib/python3.5/site-packages/shap/explainers/deep/__init__.py", line 119, in shap_values
    return self.explainer.shap_values(X, ranked_outputs, output_rank_order)
  File "/home/user/.local/lib/python3.5/site-packages/shap/explainers/deep/deep_pytorch.py", line 186, in shap_values
    sample_phis = self.gradient(feature_ind, joint_x)
  File "/home/user/.local/lib/python3.5/site-packages/shap/explainers/deep/deep_pytorch.py", line 124, in gradient
    allow_unused=True)[0]
  File "/data/coml-crispr/user/torch-env/lib/python3.5/site-packages/torch/autograd/__init__.py", line 157, in grad
    inputs, allow_unused)
RuntimeError: hook 'deeplift_grad' has changed the type of value (was torch.cuda.FloatTensor got torch.FloatTensor)
```
I specifically verified that `to_explain` is a CUDA tensor, and `model `is on CUDA and returns CUDA tensors. I am running Python 3.5.6, PyTorch 1.4.0 and SHAP 0.31.0. Any ideas how to fix this?

**Comment by jntorres** [comment]
I am also running into a similar problem

**Comment by isaacmg** [comment]
I'm having this problem now as well.

**Comment by YangShuiShui** [comment]
I'm having this problem now as well.

**Comment by y10ab1** [comment]
I'm having this problem now as well.
shap == 0.41.0
torch == 2.0.1

**Comment by tBai1994** [comment]
I'm having this problem now as well.
