### ISSUE TITLE
Unable to obtain shap values using embedding layer, tf 2.1.0 & shap 0.35.0

### ISSUE THREAD

**Issue by kingjosephm** [shap/shap#1119]
## Full code using synthetic data to exemplify error message

import pandas as pd
import numpy as np
from tensorflow.keras.optimizers import Adam
from tensorflow.keras.losses import MSE
from tensorflow.keras.models import Model
from tensorflow.keras.layers import Input, Dense, Embedding, Flatten, Concatenate
from tensorflow.keras.backend import clear_session
from sklearn.model_selection import train_test_split
import shap

def convert_list(df):
    '''
    :param df: Pandas dataframe
    :return: list of lists, with each categorical feature (as pd.Series) in its own list,
            and one list (of pd.DataFrame) of numeric features
    '''
    return [df[col] for col in categorical_features] + [df[numeric_features]]

def expand_to_2d(arr):
    '''
    Expand a numpy array to two dimensions if it is one-dimensional.
    :param arr: Numpy array
    :return: expanded Numpy array
    '''
    if len(arr.shape) >= 2:
        return arr
    return np.expand_dims(arr, axis=1)

#### Synthesize data
np.random.seed(123)
cat1 = np.random.randint(low=1, high=5, size=100) # assume factorized categorical variable
cat2 = np.random.randint(low=1, high=10, size=100) # assume factorized categorical variable
num1 = np.random.random(size=100) # assume continuous variable that's been min-max normalized
num2 = np.random.random(size=100) # assume continuous variable that's been min-max normalized
outcome = np.random.randint(low=1, high=100, size=100)
df = pd.DataFrame({'cat1': cat1, 'cat2': cat2, 'num1': num1, 'num2': num2, 'outcome': outcome})

#### Train, validation sets
X_train, X_val, y_train, y_val = train_test_split(df, df['outcome'], test_size=0.25, random_state=123)

#### Identify categorical vs. numeric features in dataset
categorical_features = ['cat1']
numeric_features = ['num1']

X_train_list = convert_list(X_train)
X_val_list = convert_list(X_val)

#### Build model (Keras Model API)
clear_session()
categorical_input_layers = [Input(shape=(1,), dtype='int32') for _ in categorical_features]
embedded_layers = [Embedding(input_dim=df[col].nunique() + 1, output_dim=1)(lyr) for (col, lyr) in zip(categorical_features, categorical_input_layers)]
flatten_layer = [Flatten()(lyr) for lyr in embedded_layers]
numeric_input_layer = Input(shape=(len(numeric_features),))
concat_layer = Concatenate(axis=1)(flatten_layer + [numeric_input_layer])
dense_layer = Dense(128, activation='relu')(concat_layer)
output_layer = Dense(1, activation='linear', name='output')(dense_layer)
model = Model(inputs=categorical_input_layers+[numeric_input_layer], outputs=output_layer)

#### Fit model
model.compile(loss=MSE, optimizer=Adam(amsgrad=True), metrics=[MSE])
model.fit(X_train_list, y_train, epochs=50, batch_size=256, verbose=0, validation_data=(X_val_list, y_val))

#### Subsample & reshape data
sample = [i[:5] for i in X_train_list] # get first 5 obs of X_train
reshaped_sample = [expand_to_2d(i.values) for i in sample]

#### Get shap values
explainer = shap.DeepExplainer(model, reshaped_sample)
shap_values = explainer.shap_values(reshaped_sample) # breaks here

## Traceback
WARNING:tensorflow:The dtype of the watched tensor must be floating (e.g. tf.float32), got tf.int32
WARNING:tensorflow:The dtype of the source tensor must be floating (e.g. tf.float32) when calling GradientTape.gradient, got tf.int32
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "C:\Users\jking\Documents\PythonVirtualEnv\20200301\lib\site-packages\shap\explainers\deep\__init__.py", line 119, in shap_values
    return self.explainer.shap_values(X, ranked_outputs, output_rank_order, check_additivity=check_additivity)
  File "C:\Users\jking\Documents\PythonVirtualEnv\20200301\lib\site-packages\shap\explainers\deep\deep_tf.py", line 304, in shap_values
    sample_phis = self.run(self.phi_symbolic(feature_ind), self.model_inputs, joint_input)
  File "C:\Users\jking\Documents\PythonVirtualEnv\20200301\lib\site-packages\shap\explainers\deep\deep_tf.py", line 361, in run
    return self.execute_with_overridden_gradients(anon)
  File "C:\Users\jking\Documents\PythonVirtualEnv\20200301\lib\site-packages\shap\explainers\deep\deep_tf.py", line 397, in execute_with_overridden_gradients
    out = f()
  File "C:\Users\jking\Documents\PythonVirtualEnv\20200301\lib\site-packages\shap\explainers\deep\deep_tf.py", line 357, in anon
    final_out = out(inputs)
  File "C:\Users\jking\Documents\PythonVirtualEnv\20200301\lib\site-packages\tensorflow_core\python\eager\def_function.py", line 568, in __call__
    result = self._call(*args, **kwds)
  File "C:\Users\jking\Documents\PythonVirtualEnv\20200301\lib\site-packages\tensorflow_core\python\eager\def_function.py", line 615, in _call
    self._initialize(args, kwds, add_initializers_to=initializers)
  File "C:\Users\jking\Documents\PythonVirtualEnv\20200301\lib\site-packages\tensorflow_core\python\eager\def_function.py", line 497, in _initialize
    *args, **kwds))
  File "C:\Users\jking\Documents\PythonVirtualEnv\20200301\lib\site-packages\tensorflow_core\python\eager\function.py", line 2389, in _get_concrete_function_internal_garbage_collected
    graph_function, _, _ = self._maybe_define_function(args, kwargs)
  File "C:\Users\jking\Documents\PythonVirtualEnv\20200301\lib\site-packages\tensorflow_core\python\eager\function.py", line 2703, in _maybe_define_function
    graph_function = self._create_graph_function(args, kwargs)
  File "C:\Users\jking\Documents\PythonVirtualEnv\20200301\lib\site-packages\tensorflow_core\python\eager\function.py", line 2593, in _create_graph_function
    capture_by_value=self._capture_by_value),
  File "C:\Users\jking\Documents\PythonVirtualEnv\20200301\lib\site-packages\tensorflow_core\python\framework\func_graph.py", line 978, in func_graph_from_py_func
    func_outputs = python_func(*func_args, **func_kwargs)
  File "C:\Users\jking\Documents\PythonVirtualEnv\20200301\lib\site-packages\tensorflow_core\python\eager\def_function.py", line 439, in wrapped_fn
    return weak_wrapped_fn().__wrapped__(*args, **kwds)
  File "C:\Users\jking\Documents\PythonVirtualEnv\20200301\lib\site-packages\tensorflow_core\python\framework\func_graph.py", line 968, in wrapper
    raise e.ag_error_metadata.to_exception(e)
tensorflow.python.framework.errors_impl.InternalError: in converted code:
    C:\Users\jking\Documents\PythonVirtualEnv\20200301\lib\site-packages\shap\explainers\deep\deep_tf.py:244 grad_graph  *
        x_grad = tape.gradient(out, shap_rAnD)
    C:\Users\jking\Documents\PythonVirtualEnv\20200301\lib\site-packages\tensorflow_core\python\eager\backprop.py:1029 gradient
        unconnected_gradients=unconnected_gradients)
    C:\Users\jking\Documents\PythonVirtualEnv\20200301\lib\site-packages\tensorflow_core\python\eager\imperative_grad.py:77 imperative_grad
        compat.as_str(unconnected_gradients.value))
    `InternalError: Recorded operation 'shap_ResourceGather' returned too few gradients. Expected 2 but received 3`

**Comment by lrdsouza** [comment]
Hi @kingjosephm,
Same problem here. Did you manage to solve it?

**Comment by kingjosephm** [comment]
Hi @lrdsouza,
I unfortunately did not, but would welcome any suggestions! In another variant I also tested whether the problem was the dual input layers in the Keras Model class by feeding it separate lists of numeric-only features (and no embedding layer). This, however, worked. So it seems something related to the presence of the embedding layer.

**Comment by Expendable0** [comment]
I had the same issue.  The only temp work-around that I could find was to 

1. train the model
2. use get_weights[0] to grab the weights of the embedding layer
3. Save the embeddings to the original dataset
4. Run a new model using the embeddings as normal features

**Comment by Sheldon-Zhang** [comment]
@Expendable0 As you re-train the new model, I am not sure if the new model will be the same as the original model. Any better walk-around?

**Comment by abiudrodas** [comment]
Hi @kingjosephm 

were you able to solve this?

**Comment by kingjosephm** [comment]
@abiudrodas - unfortunately no, I ran out of time to attempt the solution proposed by @Expendable0, nor have I investigated alternative solutions. As far as I'm aware it still remains an issue

**Comment by MohamadJaber1** [comment]
I just got the same error. Apparently its not resolved yet.

**Comment by mayurou** [comment]
我也遇到这个问题了，两年了还没有解决办法吗

**Comment by Zitihskx** [comment]
I'm having trouble with the same issue to this date.

**Comment by vla6** [comment]
Same issue with the embedding layer (July 2024)

There is a workaround for my model which is to explain the model below the layer where inputs are concatenated.  So, first get the concatenated inputs like:

( Assume I have a trained model with entity embeddings, called "model")

from tensorflow.keras import layers, Model
sub_imp = Model(inputs=model.input, outputs=model.get_layer('input_concat').output)

Then get the data, e.g. 

sub_data = sub_imp.predict(X_train_list)

Then create a model starting with concatenated inputs:

rem_model = Model(inputs=model.get_layer('input_concat').output,   outputs=model.output)

And finally explain the data using rem_model:

explainer = shap.DeepExplainer(rem_model, sub_data)
explainer.shap_values(sub_data)

This works for models like mine which are just some numeric features and some categorical which get concatenated.  I name my concatenation layer 'input_concat', and it's the flattened categorical inputs with the numeric features, see example here: https://github.com/vla6/Blog_naics_nn/blob/9323948f59fe8eb1a239119722a11f1cadc60b0a/sba_nn/sba_nn/sbnn_model.py#L61

This seems to work for me without retraining.
