### ISSUE TITLE
AttributeError: module 'shap' has no attribute 'DeepExplainer'

### ISSUE THREAD

**Issue by MayurDivate** [shap/shap#1158]
Hi, 

If I run the code using python script, get the following error. 
However, I don't get any error if I use Jupyter notebook.
The same code works fine.

```
Traceback (most recent call last):
  File "shap.py", line 1, in <module>
    import shap
  File "/home/ubuntu/Project/1_DNN/shap.py", line 67, in <module>
    explainer_shap = shap.DeepExplainer(model=model, data=testX)
AttributeError: module 'shap' has no attribute 'DeepExplainer'

```

shap version = 0.35.0
installed using pip3

How can I make my python script to work, so that I can run it on big data?

Thanks,
Mayur

**Comment by alexcoca** [comment]
Did the installation succeed? You could try uninstalling and reinstalling using `pip install shap` but I don't think this would make a difference...

**Comment by MayurDivate** [comment]
Yes, it is successful.

Below is the screenshot. 

<img width="785" alt="Screen Shot 2020-04-16 at 7 15 32 PM" src="https://user-images.githubusercontent.com/10526942/79438509-f1a54f00-8016-11ea-9239-7ecdc2a17b18.png">

**Comment by alexcoca** [comment]
So have you tried uninstalling and installing again? Failing that you can always check if it works by cloning the github repo. It works for me.

**Comment by MayurDivate** [comment]
Yeah, I have tried many times.
Sure I will try cloning also.

Thanks,
Mayur

**Comment by KahiniWadhawan** [comment]
`background = images[:100]`
`e = shap.DeepExplainer(model, background)`

I am getting the same error for the above code - AttributeError: module 'shap' has no attribute 'DeepExplainer'. Is it resolved?

**Comment by kabartay** [comment]
@KahiniWadhawan which Python version you use and which SHAP?

**Comment by ayushrathore111** [comment]
which shap version having these functionalities

**Comment by JoJoBarthold2** [comment]
Is there any fix known now?

**Comment by ValentinJSchmidt** [comment]
I think all of them, maybe you are importing shap wrong?
