### ISSUE TITLE
tensorflow.estimator is not currently a supported model type!/ .MetaGraphDef'> is not currently a supported model type!

### ISSUE THREAD

**Issue by niloofardadras** [shap/shap#1160]
Hi,
After Trying to solve this issue for days i have decided to post. 
I am using tensorflow estimator API to train my model. However I am getting multiple issues trying to use shap to explain feature importance of my model. I am using anaconda environment python 3.6

1. my inputs are dataframes
2. I have a model function which i train the model with tf.estimator.EstimatorSpec
3 my nn is created as bellow
nn = tf.estimator.Estimator(
                model_fn=model_fn,
                params=model_params,
                config=trainingConfig
        )
4. nn.train is deployed.

5.to get shap values:
            e = shap.DeepExplainer(nn,x_train.loc[1:100,:])
            shap_values = e.shap_values(x_test.loc[10,:])

here is the error I am getting 
"ERROR - Read sys.argv: Traceback (most recent call last):
  File "C:/Users/nhossein/PycharmProjects/ShapExplain/run_experiments.py", line 217, in main
    df=train_model_with_validation_and_confidence.train(parameters, Dataa, my_labb,count)
  File "C:\Users\nhossein\PycharmProjects\ShapExplain\train_model_with_validation_and_confidence.py", line 437, in train
    e = shap.DeepExplainer(nn,x_train.loc[1:100,:])
  File "C:\Anaconda3\envs\AzureEvn\lib\site-packages\shap\explainers\deep\__init__.py", line 80, in __init__
    self.explainer = TFDeepExplainer(model, data, session, learning_phase_flags)
  File "C:\Anaconda3\envs\AzureEvn\lib\site-packages\shap\explainers\deep\deep_tf.py", line 92, in __init__
    assert False, str(type(model)) + " is not currently a supported model type!"
AssertionError: <class 'tensorflow_estimator.python.estimator.estimator.Estimator'> is not currently a supported model type!"

also I have tries using the created model meta and index files and it gives error that estimator graph is not currently supported

**Comment by niloofardadras** [comment]
I Would truly appreciate any help.
