### ISSUE TITLE
Cannot run the examples on github README.md

### ISSUE THREAD

**Issue by AmartyaBarua** [shap/shap#1169]
I have tried switching Tensorflow to version 1 from 2 and downgraded Keras to 2.2.5, but I couldn't run the DeepExplainer and the GradientExplainer examples shown on the main repo page. I will link the main page here again. Just trying to see if I can use shap in my project, but without the examples running it is a little hard, for me personally, so see how this library works. Any idea on how to solve this problem would be really appreciated. Thanks

Examples are here:
[https://github.com/slundberg/shap](https://github.com/slundberg/shap)

I have used both Google Colab and local machine.

**Comment by pierresphabmixay** [comment]
Exact same problem here

**Comment by atomrom** [comment]
Same issue here. The GradientExplainer example output:
Traceback (most recent call last):
  File "C:\apps\Python3.6\lib\site-packages\tensorflow\python\client\session.py", line 1322, in _do_call
    return fn(*args)
  File "C:\apps\Python3.6\lib\site-packages\tensorflow\python\client\session.py", line 1307, in _run_fn
    options, feed_dict, fetch_list, target_list, run_metadata)
  File "C:\apps\Python3.6\lib\site-packages\tensorflow\python\client\session.py", line 1409, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.FailedPreconditionError: Attempting to use uninitialized value block3_conv1/kernel
         [[Node: block3_conv1/kernel/read = Identity[T=DT_FLOAT, _class=["loc:@block3_conv1/kernel"], _device="/job:localhost/replica:0/task:0/device:CPU:0"](block3_conv1/kernel)]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "explain.py", line 28, in <module>
    shap_values,indexes = e.shap_values(map2layer(to_explain, 7), ranked_outputs=2)
  File "C:\apps\Python3.6\lib\site-packages\shap\explainers\gradient.py", line 106, in shap_values
    return self.explainer.shap_values(X, nsamples, ranked_outputs, output_rank_order, rseed, return_variances)
  File "C:\apps\Python3.6\lib\site-packages\shap\explainers\gradient.py", line 206, in shap_values
    model_output_values = self.run(self.model_output, self.model_inputs, X)
  File "C:\apps\Python3.6\lib\site-packages\shap\explainers\gradient.py", line 319, in run
    return self.session.run(out, feed_dict)
  File "C:\apps\Python3.6\lib\site-packages\tensorflow\python\client\session.py", line 900, in run
    run_metadata_ptr)
  File "C:\apps\Python3.6\lib\site-packages\tensorflow\python\client\session.py", line 1135, in _run
    feed_dict_tensor, options, run_metadata)
  File "C:\apps\Python3.6\lib\site-packages\tensorflow\python\client\session.py", line 1316, in _do_run
    run_metadata)
  File "C:\apps\Python3.6\lib\site-packages\tensorflow\python\client\session.py", line 1335, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.FailedPreconditionError: Attempting to use uninitialized value block3_conv1/kernel
         [[Node: block3_conv1/kernel/read = Identity[T=DT_FLOAT, _class=["loc:@block3_conv1/kernel"], _device="/job:localhost/replica:0/task:0/device:CPU:0"](block3_conv1/kernel)]]

Caused by op 'block3_conv1/kernel/read', defined at:
  File "explain.py", line 9, in <module>
    model = VGG16(weights='imagenet', include_top=True)
  File "C:\apps\Python3.6\lib\site-packages\keras\applications\__init__.py", line 28, in wrapper
    return base_fun(*args, **kwargs)
  File "C:\apps\Python3.6\lib\site-packages\keras\applications\vgg16.py", line 11, in VGG16
    return vgg16.VGG16(*args, **kwargs)
  File "C:\apps\Python3.6\lib\site-packages\keras_applications\vgg16.py", line 134, in VGG16
    name='block3_conv1')(x)
  File "C:\apps\Python3.6\lib\site-packages\keras\engine\base_layer.py", line 431, in __call__
    self.build(unpack_singleton(input_shapes))
  File "C:\apps\Python3.6\lib\site-packages\keras\layers\convolutional.py", line 141, in build
    constraint=self.kernel_constraint)
  File "C:\apps\Python3.6\lib\site-packages\keras\legacy\interfaces.py", line 91, in wrapper
    return func(*args, **kwargs)
  File "C:\apps\Python3.6\lib\site-packages\keras\engine\base_layer.py", line 252, in add_weight
    constraint=constraint)
  File "C:\apps\Python3.6\lib\site-packages\keras\backend\tensorflow_backend.py", line 402, in variable
    v = tf.Variable(value, dtype=tf.as_dtype(dtype), name=name)
  File "C:\apps\Python3.6\lib\site-packages\tensorflow\python\ops\variables.py", line 235, in __init__
    constraint=constraint)
  File "C:\apps\Python3.6\lib\site-packages\tensorflow\python\ops\variables.py", line 397, in _init_from_args
    self._snapshot = array_ops.identity(self._variable, name="read")
  File "C:\apps\Python3.6\lib\site-packages\tensorflow\python\ops\array_ops.py", line 142, in identity
    return gen_array_ops.identity(input, name=name)
  File "C:\apps\Python3.6\lib\site-packages\tensorflow\python\ops\gen_array_ops.py", line 3795, in identity
    "Identity", input=input, name=name)
  File "C:\apps\Python3.6\lib\site-packages\tensorflow\python\framework\op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File "C:\apps\Python3.6\lib\site-packages\tensorflow\python\framework\ops.py", line 3392, in create_op
    op_def=op_def)
  File "C:\apps\Python3.6\lib\site-packages\tensorflow\python\framework\ops.py", line 1718, in __init__
    self._traceback = self._graph._extract_stack()  # pylint: disable=protected-access

FailedPreconditionError (see above for traceback): Attempting to use uninitialized value block3_conv1/kernel
         [[Node: block3_conv1/kernel/read = Identity[T=DT_FLOAT, _class=["loc:@block3_conv1/kernel"], _device="/job:localhost/replica:0/task:0/device:CPU:0"](block3_conv1/kernel)]]

**Comment by ITWOI** [comment]
Hi, I figured out how to fix the example in DeepExplainer. Here is the code.

```
import keras
...
explainer = shap.DeepExplainer(model, x_train[:100], keras.backend.get_session())
```

I think it may also apply to the example in GradientExplainer.

**Comment by Nico-ba** [comment]
@ITWOI Thanks for the answer! Works also with GradientExplainer.
