### ISSUE TITLE
Unable to create dependence plot if one of the features is of type category

### ISSUE THREAD

**Issue by gmyrianthous** [shap/shap#1189]
So in the scenario you have at least one variable of type `category`, the user will get a `ValueError: could not convert string to float:`

### How to reproduce

```
import shap
import lightgbm as lgbm
import numpy as np
import platform
import pandas as pd
import matplotlib.pyplot as plt
import matplotlib


def generate_sample_data():
    np.random.seed(123)

    df = pd.DataFrame(np.random.randint(0, 100, size=(100, 3)), columns=list('ABC'))
    df['D'] = np.random.choice(['X', 'Y', 'Z'], len(df))
    df['D'] = df['D'].astype('category')
    df['label'] = np.random.choice([0, 1], len(df))

    return df


def report_versions():
    print("="*35)
    print(f"python version: {platform.python_version()}")
    print(f"pandas version: {pd.__version__}")
    print(f"lightgbm version: {lgbm.__version__}")
    print(f"shap version: {shap.__version__}")
    print(f"matplotlib version: {matplotlib.__version__}")
    print("="*35)


def train_model(df, feature_names, label_name, parameters, categorical_feature=None):
    training_df = lgbm.Dataset(df[feature_names], label=df[label_name], categorical_feature=categorical_feature)
    model = lgbm.train(parameters, training_df, categorical_feature=categorical_feature)
    model.save_model('lightgbm_model_file.txt')


def create_shap_dependence_plots(model_filename, df, feature_names, label_name):
    bst = lgbm.Booster(model_file=model_filename)

    tree_explainer = shap.TreeExplainer(bst)
    tree_explainer.model.original_model.params = params
    shap_vals = tree_explainer.shap_values(df[feature_names], y=df[label_name])

    for feature in feature_names:
        plt.figure(figsize=(18, 18))
        shap.dependence_plot(feature, shap_vals[-1], df[feature_names], display_features=df[feature_names], show=False)
        plt.xticks(rotation=90)
        plt.tight_layout()
        plt.savefig(f"{feature}.png")
        plt.close()


if __name__ == '__main__':
    # Report all versions of the packages used
    report_versions()

    # Generate a dummy dataset
    df = generate_sample_data()
    print(df)

    # Prepare the parameters for the LightGBM model
    params = dict(
        objective='binary',
        num_leaves=3,
        num_trees=10,
        learning_rate=0.5,
        tree_learner='data',
        device='cpu',
        seed=123,
        max_depth=15,
        metric='binary_logloss'
    )

    # Train the model and save the model file
    feature_names = ['A', 'B', 'C', 'D']
    train_model(df, feature_names, 'label', params, ['D'])

    # Attempt to create SHAP dependence plots
    create_shap_dependence_plots('lightgbm_model_file.txt', df, feature_names, 'label')
```

and the result will be something like: 

```
===================================
python version: 3.7.7
pandas version: 1.0.3
lightgbm version: 2.3.1
shap version: 0.35.0
matplotlib version: 3.2.1
===================================
Found `num_trees` in params. Will use it instead of argument
     A   B   C  D  label
0   66  92  98  Y      1
1   17  83  57  Y      0
2   86  97  96  Z      0
3   47  73  32  Z      1
4   46  96  25  Y      1
..  ..  ..  .. ..    ...
95  84  90   4  Z      0
96  21  32  39  X      0
97   1  98  82  Z      0
98  90  35  58  X      1
99  38   1  52  Y      1

[100 rows x 5 columns]
[LightGBM] [Warning] Starting from the 2.1.2 version, default value for the "boost_from_average" parameter in "binary" objective is true.
This may cause significantly different results comparing to the previous versions of LightGBM.
Try to set boost_from_average=false, if your old models produce bad results
[LightGBM] [Info] Number of positive: 56, number of negative: 44
[LightGBM] [Info] Total Bins 90
[LightGBM] [Info] Number of data: 100, number of used features: 4
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.560000 -> initscore=0.241162
[LightGBM] [Info] Start training from score 0.241162
Setting feature_perturbation = "tree_path_dependent" because no background data was given.
LightGBM binary classifier with TreeExplainer shap values output has changed to a list of ndarray
Traceback (most recent call last):
  File "/Users/gmyrianthous/PycharmProjects/shap-category/test.py", line 79, in <module>
    create_shap_dependence_plots('lightgbm_model_file.txt', df, feature_names, 'label')
  File "/Users/gmyrianthous/PycharmProjects/shap-category/test.py", line 46, in create_shap_dependence_plots
    shap.dependence_plot(feature, shap_vals[-1], df[feature_names], display_features=df[feature_names], show=False)
  File "/Users/gmyrianthous/PycharmProjects/shap-category/venv/lib/python3.7/site-packages/shap/plots/dependence.py", line 108, in dependence_plot
    interaction_index = approximate_interactions(ind, shap_values, features)[0]
  File "/Users/gmyrianthous/PycharmProjects/shap-category/venv/lib/python3.7/site-packages/shap/common.py", line 307, in approximate_interactions
    val_other = X[inds, i][srt].astype(np.float)
ValueError: could not convert string to float: 'Z'
```

**Comment by gmyrianthous** [comment]
I am planning to raise a PR with a fix later this week.

**Comment by nickcorona** [comment]
Have this problem too with both catboost and lightgbm.

**Comment by SwapnilDreams100** [comment]
Hi is this problem fixed?
