### ISSUE TITLE
keras is no longer supported, please use tf.keras instead.

### ISSUE THREAD

**Issue by lineho** [shap/shap#1259]
Hello, I am a student who learns by watching dipshap on this site(https://towardsdatascience.com/interpretability-of-deep-learning-models-9f52e54d72ab). I can't do this part well, can you help me?
Keras changed, but the error continues.
:
`
import pandas as pd
import seaborn as sns
import keras
import shap
import sklearn
from sklearn import model_selection
import tensorflow as tf
from tensorflow.keras.layers import Input, Dense, BatchNormalization
from tensorflow.keras.models import Model
from tensorflow.keras.callbacks import EarlyStopping
import matplotlib.pyplot as plt

df=sns.load_dataset(name='diamonds')
print(df.head())
print(df.describe()) 

X = df.drop('price',axis=1)
Y = df.price

X[['cut','color','clarity']] = X[['cut','color','clarity']].astype('category')
.

cut_cat_map = [x for x in zip(X.cut.cat.categories,X.cut.cat.codes.unique() )]
color_cat_map = [x for x in zip(X.color.cat.categories,X.cut.cat.codes.unique() )]
clarity_cat_map = [x for x in zip(X.clarity.cat.categories,X.cut.cat.codes.unique() )]
print('cut_cat_map:' , cut_cat_map)
print('color_cat_map: ',color_cat_map)
print('clarity_cat_map: ', clarity_cat_map)

X[['cut','color','clarity']] = X[['cut','color','clarity']].apply(lambda c : c.cat.codes)

X_train, X_test, Y_train, Y_test = model_selection.train_test_split(X, Y, test_size = 0.33, random_state = 5)
print('X_train: ', X_train.shape)
print('X_test: ', X_test.shape)
print('Y_train: ', Y_train.shape)
print('Y_test: ', Y_test.shape)

inputs = Input(shape=(X_train.shape[1],), name='input')

x = BatchNormalization(name='input_bn')(inputs)

x = Dense(X_train.shape[1], activation='relu', name='first')(x)
x = Dense(64, activation='relu',name='second')(x)
x = Dense(X_train.shape[1], activation='elu',name='last')(x)

predictions = Dense(1, activation='relu', name='ouput')(x)

model = Model(inputs=inputs, outputs=predictions)
model.compile(optimizer='adam',
              loss='mape')
model.fit(X_train,
          Y_train,
          epochs = 100,
          batch_size = 1000,
          validation_data = (X_test,Y_test),
          shuffle=True,
          callbacks=[EarlyStopping(monitor='val_loss', patience=1,)])

val_loss = model.history.history['val_loss']
loss = model.history.history['loss']

print(model.summary())

plt.figure()
plt.plot(val_loss, label='val_loss')
plt.plot(loss, label = 'loss')
plt.legend()
plt.show()

shap.initjs()

explainer_shap = shap.DeepExplainer(model=model,data=X_train)

shap_values = explainer_shap.shap_values(X=X_train.values[:500],ranked_outputs=True)
`

and error said

keras is no longer supported, please use tf.keras instead.
You have provided over 5k background samples! For better performance consider using smaller random sample.
Traceback (most recent call last):
  File "F:/dropbox/Dropbox/Coding/python/study/deep-learning/DeepSHAP/DeepSHAP.py", line 110, in <module>
  File "C:\Users\e\anaconda3\envs\torch\lib\site-packages\shap\explainers\deep\__init__.py", line 119, in shap_values
    return self.explainer.shap_values(X, ranked_outputs, output_rank_order, check_additivity=check_additivity)
  File "C:\Users\e\anaconda3\envs\torch\lib\site-packages\shap\explainers\deep\deep_tf.py", line 304, in shap_values
    sample_phis = self.run(self.phi_symbolic(feature_ind), self.model_inputs, joint_input)
  File "C:\Users\e\anaconda3\envs\torch\lib\site-packages\shap\explainers\deep\deep_tf.py", line 361, in run
    return self.execute_with_overridden_gradients(anon)
  File "C:\Users\e\anaconda3\envs\torch\lib\site-packages\shap\explainers\deep\deep_tf.py", line 397, in execute_with_overridden_gradients
    out = f()
  File "C:\Users\e\anaconda3\envs\torch\lib\site-packages\shap\explainers\deep\deep_tf.py", line 357, in anon
    final_out = out(inputs)
  File "C:\Users\e\anaconda3\envs\torch\lib\site-packages\tensorflow\python\eager\def_function.py", line 580, in __call__
    result = self._call(*args, **kwds)
  File "C:\Users\e\anaconda3\envs\torch\lib\site-packages\tensorflow\python\eager\def_function.py", line 627, in _call
    self._initialize(args, kwds, add_initializers_to=initializers)
  File "C:\Users\e\anaconda3\envs\torch\lib\site-packages\tensorflow\python\eager\def_function.py", line 505, in _initialize
    self._stateful_fn._get_concrete_function_internal_garbage_collected(  # pylint: disable=protected-access
  File "C:\Users\e\anaconda3\envs\torch\lib\site-packages\tensorflow\python\eager\function.py", line 2446, in _get_concrete_function_internal_garbage_collected
    graph_function, _, _ = self._maybe_define_function(args, kwargs)
  File "C:\Users\e\anaconda3\envs\torch\lib\site-packages\tensorflow\python\eager\function.py", line 2777, in _maybe_define_function
    graph_function = self._create_graph_function(args, kwargs)
  File "C:\Users\e\anaconda3\envs\torch\lib\site-packages\tensorflow\python\eager\function.py", line 2657, in _create_graph_function
    func_graph_module.func_graph_from_py_func(
  File "C:\Users\e\anaconda3\envs\torch\lib\site-packages\tensorflow\python\framework\func_graph.py", line 981, in func_graph_from_py_func
    func_outputs = python_func(*func_args, **func_kwargs)
  File "C:\Users\e\anaconda3\envs\torch\lib\site-packages\tensorflow\python\eager\def_function.py", line 441, in wrapped_fn
    return weak_wrapped_fn().__wrapped__(*args, **kwds)
  File "C:\Users\e\anaconda3\envs\torch\lib\site-packages\tensorflow\python\framework\func_graph.py", line 968, in wrapper
    raise e.ag_error_metadata.to_exception(e)
tensorflow.python.autograph.impl.api.StagingError: in user code:

    C:\Users\e\anaconda3\envs\torch\lib\site-packages\shap\explainers\deep\deep_tf.py:244 grad_graph  *
        x_grad = tape.gradient(out, shap_rAnD)
    C:\Users\e\anaconda3\envs\torch\lib\site-packages\tensorflow\python\eager\backprop.py:1042 gradient  **
        flat_grad = imperative_grad.imperative_grad(
    C:\Users\e\anaconda3\envs\torch\lib\site-packages\tensorflow\python\eager\imperative_grad.py:71 imperative_grad
        return pywrap_tfe.TFE_Py_TapeGradient(
    C:\Users\e\anaconda3\envs\torch\lib\site-packages\tensorflow\python\eager\backprop.py:145 _gradient_function
        grad_fn = ops._gradient_registry.lookup(op_name)  # pylint: disable=protected-access
    C:\Users\e\anaconda3\envs\torch\lib\site-packages\tensorflow\python\framework\registry.py:96 lookup
        raise LookupError(

    LookupError: gradient registry has no entry for: shap_AddV2

**Comment by monikaheinzl** [comment]
Hi, I have the same issue. Could you solve it?
