### ISSUE TITLE
shap.dependence_plot("RM", shap_values, X) getting 'invalild DISPLAY variable'

### ISSUE THREAD

**Issue by kennyqiweng** [shap/shap#126]
When I was tinkering with shap.dependence_plot("RM", shap_values, X), an error occurred as follows:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/data/j-wengqi-jk/anaconda3/lib/python3.6/site-packages/shap-0.19.0-py3.6-linux-x86_64.egg/shap/plots.py", line 215, in dependence_plot
    alpha=alpha, vmin=clow, vmax=chigh, norm=color_norm, rasterized=len(xv) > 500)
  File "/data/j-wengqi-jk/anaconda3/lib/python3.6/site-packages/matplotlib/pyplot.py", line 3456, in scatter
    ax = gca()
  File "/data/j-wengqi-jk/anaconda3/lib/python3.6/site-packages/matplotlib/pyplot.py", line 984, in gca
    return gcf().gca(**kwargs)
  File "/data/j-wengqi-jk/anaconda3/lib/python3.6/site-packages/matplotlib/pyplot.py", line 601, in gcf
    return figure()
  File "/data/j-wengqi-jk/anaconda3/lib/python3.6/site-packages/matplotlib/pyplot.py", line 548, in figure
    **kwargs)
  File "/data/j-wengqi-jk/anaconda3/lib/python3.6/site-packages/matplotlib/backend_bases.py", line 161, in new_figure_manager
    return cls.new_figure_manager_given_figure(num, fig)
  File "/data/j-wengqi-jk/anaconda3/lib/python3.6/site-packages/matplotlib/backend_bases.py", line 167, in new_figure_manager_given_figure
    canvas = cls.FigureCanvas(figure)
  File "/data/j-wengqi-jk/anaconda3/lib/python3.6/site-packages/matplotlib/backends/backend_qt5agg.py", line 24, in __init__
    super(FigureCanvasQTAgg, self).__init__(figure=figure)
  File "/data/j-wengqi-jk/anaconda3/lib/python3.6/site-packages/matplotlib/backends/backend_qt5.py", line 234, in __init__
    _create_qApp()
  File "/data/j-wengqi-jk/anaconda3/lib/python3.6/site-packages/matplotlib/backends/backend_qt5.py", line 125, in _create_qApp
    raise RuntimeError('Invalid DISPLAY variable')

But when I tried to fix by command 'matplotlib.pyplot.switch_backend('agg')',  shap.dependence_plot("RM", shap_values, X) gave no data at all.

**Comment by slundberg** [comment]
Look like a matplotlib problem. Can you make a matplotlib plot directly to make sure it works?

**Comment by kennyqiweng** [comment]
Looks like the redhat server I used doesn't support any plot function. I had to download to local computer to see plots. By the way, does SHAP support tree models in H2O package?
