### ISSUE TITLE
DeepExplainer crashes on saved models

### ISSUE THREAD

**Issue by billbradley** [shap/shap#1295]
Tensorflow originally saved models as HDF5 files, but now uses a new "SavedModel" format.  If we load a model from the HDF5 format, `DeepExplainer()/shap_values()` works fine; if we use the new format, it crashes.

Versions of stuff:
```
tensorflow==2.1.0
protobuf==3.11.3
shap==0.35.0
```

Here's minimal code to reproduce the bug:
```
import shap
import numpy as np
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers

# Make some data
num_features = 10
num_samples = 50
X = np.random.randn(num_samples, num_features)
y = np.random.randint(10, size=num_samples)
# Create 3 target samples to be explained
explainees = np.random.randn(3, num_features)

# Make and train minimal model
model = tf.keras.Sequential()
model.add(layers.Dense(10, activation='relu', input_shape=(num_features,)))
model.compile(optimizer='adam',
              loss=tf.losses.SparseCategoricalCrossentropy(
                  from_logits=True),
              metrics=['accuracy'])
model.fit(X, y, epochs=1, batch_size=10)

# Save model in new format
model.save('SavedModel_format')
model2 = keras.models.load_model('SavedModel_format')

# Save model in older format
model.save('HDF5_format', save_format='h5')
model3 = keras.models.load_model('HDF5_format')

# Test all the models
for m, m_str in [(model, 'Built'), (model3, 'HDF5'), (model2, 'SavedModel')]:
    try:
        explainer = shap.DeepExplainer(m, X)
        shap_values = explainer.shap_values(explainees)
        print(40 * '=')
        print('%s model worked.\n' % m_str)
    except Exception:
        print(40 * '=')
        print('%s model failed!!!!!\n' % m_str)
        raise
```

Output I get:
```
...
========================================
Built model worked.

========================================
HDF5 model worked.

========================================
SavedModel model failed!!!!!

Traceback (most recent call last):
  File "minimal_example.py", line 37, in <module>
    shap_values = explainer.shap_values(explainees)
  File "/usr/local/lib/python3.7/site-packages/shap/explainers/deep/__init__.py", line 119, in shap_values
    return self.explainer.shap_values(X, ranked_outputs, output_rank_order, check_additivity=check_additivity)
  File "/usr/local/lib/python3.7/site-packages/shap/explainers/deep/deep_tf.py", line 304, in shap_values
    sample_phis = self.run(self.phi_symbolic(feature_ind), self.model_inputs, joint_input)
  File "/usr/local/lib/python3.7/site-packages/shap/explainers/deep/deep_tf.py", line 361, in run
    return self.execute_with_overridden_gradients(anon)
  File "/usr/local/lib/python3.7/site-packages/shap/explainers/deep/deep_tf.py", line 413, in execute_with_overridden_gradients
    return [v.numpy() for v in out]
  File "/usr/local/lib/python3.7/site-packages/shap/explainers/deep/deep_tf.py", line 413, in <listcomp>
    return [v.numpy() for v in out]
AttributeError: 'NoneType' object has no attribute 'numpy'
```

**Comment by EtienneBoisvenue** [comment]
I am having exactly the same issue

**Comment by EtienneBoisvenue** [comment]
You could use this to convert the model into a tensorflow.python.keras.engine.sequential.Sequential object instead of a tensorflow.python.keras.saving.saved_model.load.Sequential object.





def load_keras_model_object(model_path):
    #model path can be a directory (new tensorflow way of saving)
    #of model path can be a single .h5 file (whatever the extension, but the content must be the one of a saved h5 keras model)

    model = tf.keras.models.load_model(model_path)
    model_type = str(type(model))

    if model_type == "<class 'tensorflow.python.keras.saving.saved_model.load.Sequential'>" or \
            model_type == "tensorflow.python.keras.saving.saved_model.load.Sequential":
        # Intentionality saving the model into h5 format
        path_h5 = model_path+"_h5.h5"
        model.save(path_h5, save_format = "h5")
        reloaded_model = tf.keras.models.load_model(path_h5)
        os.remove(path_h5)

    elif model_type == "<class 'tensorflow.python.keras.engine.sequential.Sequential'>" or \
            model_type == "tensorflow.python.keras.engine.sequential.Sequential" :
        # object of the desired class
        reloaded_model = model
    else:
        # Not a model form keras.engine and not a model from saved_model
        print("unknown model format")
        reloaded_model = None
        pass

    return reloaded_model

**Comment by billbradley** [comment]
Dear Etienne,

That's a very clever work-around!

I'm still concerned that as the two saved formats continue to diverge, with the modern one unsupported, that there will be an increasing number of features that will be lost from a SavedModel=>HDF5 conversion.

**Comment by EtienneBoisvenue** [comment]
I totally agree with you. This is by no mean a permanent fix. For the moment being, it will be the fix for my current app, but definitely finding a more robust approach has been added to my backlog.

The real fix would be that the shap library supports the new SavedModel format. I'm pretty sure I saw that issue on their repo.

**Comment by ghost** [comment]
Keep in mind that Tensorflow has multiple versions of savedmodel: one for Keras and one for low-level Tensorflow.  I've been trying to use the workaround above on a model saved with the low level api and the tf.keras specific instructions above don't work.  Presumably because Keras and basic TF use different formats under the hood.  If I figure out a way to do this i'll post.  If anyone has insight into bare TF savedmodels i'd love to hear it.

**Comment by ghost** [comment]
low level tensorflow savedmodel documentation: https://www.tensorflow.org/api_docs/python/tf/saved_model

tf.keras savedmodel documentation:  
https://www.tensorflow.org/guide/keras/save_and_serialize

**Comment by alielabridi** [comment]
@jason-brian-anderson were you able to find a solution for using low level tf saved_model with shap? especially with deepExplainer and using signatureDef?

**Comment by RX1256** [comment]
> Tensorflow originally saved models as HDF5 files, but now uses a new "SavedModel" format. If we load a model from the HDF5 format, `DeepExplainer()/shap_values()` works fine; if we use the new format, it crashes.
> 
> Versions of stuff:
> 
> ```
> tensorflow==2.1.0
> protobuf==3.11.3
> shap==0.35.0
> ```
> 
> Here's minimal code to reproduce the bug:
> 
> ```
> import shap
> import numpy as np
> import tensorflow as tf
> from tensorflow import keras
> from tensorflow.keras import layers
> 
> # Make some data
> num_features = 10
> num_samples = 50
> X = np.random.randn(num_samples, num_features)
> y = np.random.randint(10, size=num_samples)
> # Create 3 target samples to be explained
> explainees = np.random.randn(3, num_features)
> 
> # Make and train minimal model
> model = tf.keras.Sequential()
> model.add(layers.Dense(10, activation='relu', input_shape=(num_features,)))
> model.compile(optimizer='adam',
>               loss=tf.losses.SparseCategoricalCrossentropy(
>                   from_logits=True),
>               metrics=['accuracy'])
> model.fit(X, y, epochs=1, batch_size=10)
> 
> # Save model in new format
> model.save('SavedModel_format')
> model2 = keras.models.load_model('SavedModel_format')
> 
> # Save model in older format
> model.save('HDF5_format', save_format='h5')
> model3 = keras.models.load_model('HDF5_format')
> 
> # Test all the models
> for m, m_str in [(model, 'Built'), (model3, 'HDF5'), (model2, 'SavedModel')]:
>     try:
>         explainer = shap.DeepExplainer(m, X)
>         shap_values = explainer.shap_values(explainees)
>         print(40 * '=')
>         print('%s model worked.\n' % m_str)
>     except Exception:
>         print(40 * '=')
>         print('%s model failed!!!!!\n' % m_str)
>         raise
> ```
> 
> Output I get:
> 
> ```
> ...
> ========================================
> Built model worked.
> 
> ========================================
> HDF5 model worked.
> 
> ========================================
> SavedModel model failed!!!!!
> 
> Traceback (most recent call last):
>   File "minimal_example.py", line 37, in <module>
>     shap_values = explainer.shap_values(explainees)
>   File "/usr/local/lib/python3.7/site-packages/shap/explainers/deep/__init__.py", line 119, in shap_values
>     return self.explainer.shap_values(X, ranked_outputs, output_rank_order, check_additivity=check_additivity)
>   File "/usr/local/lib/python3.7/site-packages/shap/explainers/deep/deep_tf.py", line 304, in shap_values
>     sample_phis = self.run(self.phi_symbolic(feature_ind), self.model_inputs, joint_input)
>   File "/usr/local/lib/python3.7/site-packages/shap/explainers/deep/deep_tf.py", line 361, in run
>     return self.execute_with_overridden_gradients(anon)
>   File "/usr/local/lib/python3.7/site-packages/shap/explainers/deep/deep_tf.py", line 413, in execute_with_overridden_gradients
>     return [v.numpy() for v in out]
>   File "/usr/local/lib/python3.7/site-packages/shap/explainers/deep/deep_tf.py", line 413, in <listcomp>
>     return [v.numpy() for v in out]
> AttributeError: 'NoneType' object has no attribute 'numpy'
> ```

i have the same error. Have you figured out how to fix it? thanks a lot
