### ISSUE TITLE
UnicodeDecode error during installation

### ISSUE THREAD

**Issue by Nicolabo** [shap/shap#132]
Hi,
I was trying to install `shap` package locally and on EC2.

I was able to install it locally but on EC2 I got an error:

```
$ pip install shap
Collecting shap
  Using cached https://files.pythonhosted.org/packages/87/67/dc358c988a4527297e3a7f43d792088c7482338bfe2fa4fe67003228c601/shap-0.18.1.tar.gz
    Complete output from command python setup.py egg_info:
    'ascii' codec can't decode byte 0xc5 in position 9922: ordinal not in range(128)
    WARNING: The C extension could not be compiled, sklearn tree models not supported.
    Traceback (most recent call last):
      File "/tmp/pip-install-sqjxpliz/shap/setup.py", line 51, in <module>
        run_setup(True)
      File "/tmp/pip-install-sqjxpliz/shap/setup.py", line 28, in run_setup
        long_description = fh.read()
      File "/home/ubuntu/anaconda/envs/venv-conda-earlyalerts/lib/python3.6/encodings/ascii.py", line 26, in decode
        return codecs.ascii_decode(input, self.errors)[0]
    UnicodeDecodeError: 'ascii' codec can't decode byte 0xc5 in position 9922: ordinal not in range(128)

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-sqjxpliz/shap/setup.py", line 55, in <module>
        run_setup(False)
      File "/tmp/pip-install-sqjxpliz/shap/setup.py", line 28, in run_setup
        long_description = fh.read()
      File "/home/ubuntu/anaconda/envs/venv-conda-earlyalerts/lib/python3.6/encodings/ascii.py", line 26, in decode
        return codecs.ascii_decode(input, self.errors)[0]
    UnicodeDecodeError: 'ascii' codec can't decode byte 0xc5 in position 9922: ordinal not in range(128)
```

I thought that it could be a problem with my EC2 instance. However, my colleague get the same error during installation on local machine. Do you know what's the problem?

**Comment by TejjeT** [comment]
Hello,

I got the same error while I was trying to install it in docker. it worked fine in my local though!!
python version = 3.4

**Comment by slundberg** [comment]
I think it is because of a non-ascii character in the README file. I'll remove it.

**Comment by Nicolabo** [comment]
The problem still occurs. I work on Python 3.6.4
