### ISSUE TITLE
Support for csr sparse matrices.

### ISSUE THREAD

**Issue by asutosh97** [shap/shap#138]
Currently, KernelExplainer only supports pandas dataframe and numpy matrices. It should be extended to support `scipy.sparse.csr.csr_matrix`

**Comment by slundberg** [comment]
This would be good. It will take some work though so I can't promise any time line. You could work around it by selecting just the non-zero entries for the background and the instance you are explaining and passing those as a dense vector. This would effectively assume the sparse entries will have zero SHAP values.

**Comment by asutosh97** [comment]
Okay, cool. I'll give that a try. 
I also have one more doubt. Let's say I have a text data featured as BoW or TF-IDF. So, I have a separate list of mappings of feature number to the word that it corresponds to. Is there any way that I can pass this to get SHAP values of those words?

**Comment by slundberg** [comment]
Not sure I fully understand the question. You have SHAP values for the features represented as a number and you want to get the SHAP value for the words? If there is a one-to-one mapping then SHAP values are the same.

**Comment by psinger** [comment]
Having sparse functionality would be extremely valuable. At the moment I run in a lot of bottlenecks working with larger datasets in TreeExplainer, e.g., with BOW models.

**Comment by slundberg** [comment]
@psinger yeah, that would be really nice. The core part would require updating the code `tree_shap.h` to handle a sparse feature vector and return a sparse attribution vector.

I should note that one way to mitigate this would be to find out what features the tree model actually depends on and make sure those are the only ones in your input dataset (i.e. prune unused words).

**Comment by psinger** [comment]
@slundberg Wouldn't it be already enough to return a sparse matrix in `shap_values` and then update the plotting function accordingly?

**Comment by zmabzug** [comment]
+1 for sparse support for TreeExplainer!

**Comment by slundberg** [comment]
It depends on if we are talking about the XGBoost LightGBM or sklearn implementations. the XGBoost and LightGBM currently are embedded in those packages. So the whole phi matrix is returned before we have the chance to make it sparse. That means the C++ implementations should be updated. You are right that if we could just import the XGBoost models and use the tree_shap.h implementation we could do dense rows but make a sparse matrix. I don't know if building a sparse matrix in python/numpy will be fast or not. Could be worth a try :) ...I can't pursue it at this moment though, so if anyone else wants to take a shot at it that would be great!

**Comment by psinger** [comment]
You are right, your implementations in xgboost and lightgbm return dense matrices. One could transform them to sparse matrices in this repo though, to at least somehow allow to work with sparse matrices. In the end, one better would return sparse matrices directly in xgboost and lightgbm though.

As a side question regarding this issue: I have struggles understanding why calculations on shap values are done in respective tree repos like xgboost or lightgbm but that then some further calculations are necessary within this package via `tree_shap.h`. Could you please shortly elaborate on that?

**Comment by slundberg** [comment]
Initially tree_shap.h was used for sklearn-models since merging with the
core sklearn library for all their models was going to be problematic. I
also am not sure I want to maintain separate implementations in every tree
package, so I figured one common implementation would be better. The
XGBoost and LightGBM implementations came before tree_shap.h. tree_shap.h
is not used for XGBoost or CatBoost, and is only used for interaction
values with LightGBM.

**Comment by psinger** [comment]
Thanks for the elaboration, makes sense! After a quick glance, it seems to me though that `tree_shap` is also called via `_tree_shap_ind` which is called also for non-interaction shap values.

Anyways, I quickly implemented a dirty batch processing function that takes a large-scale sparse matrix and subsequently calculated the shap values for it and transforms the results to sparse matrices. The good thing is that the current `shap_values ` function already works out of the box with providing sparse features, but it returns a dense matrix, so one needs to transform it to sparse afterwards. The batch processing was necessary for me as I also ran into https://github.com/Microsoft/LightGBM/issues/1334.

Then, one needs to transform the dense shap values matrix to sparse and the plotting functions need a few re-implementation to work with sparse shap values and features. To try it out, I adapted the `summary_plot `code for dot and bar plots. One can see the changes here: https://github.com/psinger/shap/commit/2fe13faf050fd185dbcf5e781c6a90061e4c66f2 
Maybe this is helpful to someone.

**Comment by slundberg** [comment]
Thanks @psinger! We should really support returning a csr at some point, but what you did seems like a good stopgap.

**Comment by yramon** [comment]
@slundberg: "This would be good. It will take some work though so I can't promise any time line. You could work around it by selecting just the non-zero entries for the background and the instance you are explaining and passing those as a dense vector. This would effectively assume the sparse entries will have zero SHAP values."

I have a question how this is exactly done for sparse data sets? I already use as reference values all zeros to speed up the algorithm and the input is a numpy array with only a small fraction of non-zero values. Is this what you mean with "working around it by selecting only the non-zero entries for instance"? Or did you mean something else as to enter the input to make KernelShap more efficient?

**Comment by slundberg** [comment]
@YanouRamon #200 has now added sparse support to KernelExplainer. So just passing a sparse matrix is enough.

**Comment by yramon** [comment]
@slundberg 

When I pass the dense format (numpy array), the shap function works. However, when I pass the sparse matrix, I get the following error:

shap_values = explainer.shap_values(instance_idx, nsamples=5000)
  0%|          | 0/1 [00:00<?, ?it/s]
Traceback (most recent call last):

  File "<ipython-input-195-eba41b031c12>", line 1, in <module>
    shap_values = explainer.shap_values(instance_idx, nsamples=5000)

  File "C:\Users\yramon\AppData\Local\Continuum\anaconda3\lib\site-packages\shap\explainers\kernel.py", line 202, in shap_values
    explanations.append(self.explain(data, **kwargs))

  File "C:\Users\yramon\AppData\Local\Continuum\anaconda3\lib\site-packages\shap\explainers\kernel.py", line 331, in explain
    self.addsample(instance.x, mask, w)

  File "C:\Users\yramon\AppData\Local\Continuum\anaconda3\lib\site-packages\shap\explainers\kernel.py", line 490, in addsample
    self.synth_data[offset:offset+self.N, groups] = x[0, groups]

ValueError: setting an array element with a sequence.

**Comment by ferlocar** [comment]
@yramon, I have the same error. Did you manage to circumvent the issue?

**Comment by imatiach-msft** [comment]
@yramon @ferlocar sorry for the late response, can you please send a repro of the issue - eg a code snippet that reproduces the error or the learner + dataset?  Also, what version of shap are you using?  Some bug fixes have been added to the sparse code since the original PR, especially for sparse background case.

**Comment by yramon** [comment]
@ferlocar  @imatiach-msft 
I use the latest version of shap. 

I managed to work with the sparse instance format by changing the reference value to a sparse matrix as well. Hope this works for you as well. More specifically, I did the following: 

Reference_value=np.zeros(np.shape(x_test)[1])
RV=np.reshape(Reference_value,(1,len(Reference_value)))
RV=sparse.csr_matrix(RV)

explainer = shap.KernelExplainer(f, RV, link="identity")

**Comment by ferlocar** [comment]
@imatiach-msft @yramon 

Sorry for the late reply. I stopped working on my project for a while. 

@yramon Your solution works! That's what I was missing. Thanks a lot!
