### ISSUE TITLE
`shap.Explainer` doesn't work with `sklearn.linear_model.LinearRegression`

### ISSUE THREAD

**Issue by harupy** [shap/shap#1486]
I'm testing the auto-chooses feature of `shap.Explainer` and found it doesn't work with `sklearn.linear_model.LinearRegression`. Is this behavior intended or not?

Code:

```python
import shap
from sklearn.datasets import load_iris
from sklearn.linear_model import LinearRegression

X, y = load_iris(return_X_y=True)

model = LinearRegression()
model.fit(X, y)

explainer = shap.Explainer(model, X)
explanation = explainer(X)
```

Stack trace:

```
Traceback (most recent call last):
  File "g.py", line 10, in <module>
    explainer = shap.Explainer(model, X)
  File "/xxx/site-packages/shap/explainers/_explainer.py", line 141, in __init__
    raise Exception("Unknown algorithm type passed: %s!" % algorithm)
Exception: Unknown algorithm type passed: linear!
```

**Comment by harupy** [comment]
btw are models `shap.Explainer` supports documented somewhere?
