### ISSUE TITLE
Reshape error in XGBoost explainer.shap_values()

### ISSUE THREAD

**Issue by VolodyaCO** [shap/shap#1658]
This is related to #580 where people experienced a reshape error when passing a matrix with more or less features to the `explainer.shap_values` than the number of features used to train a tree model.

I present the same bug, but I am passing a matrix with the correct number of features:

```python
# Quick test that everything works ok:
dtest = xgb.DMatrix(features)
model.predict(dtest)
print('features are ok!')
print(features.shape)

# Shap implementation of model
explainer = shap.TreeExplainer(model)

X = shap.sample(features, 100)
print( type(X), X.shape )

model.predict(xgb.DMatrix(X))
shap_values = explainer.shap_values(xgb.DMatrix(X))
```

When I run it I get this:

```shell
features are ok!
(544401, 92)
<class 'pandas.core.frame.DataFrame'> (100, 92)
Traceback (most recent call last):
  File "/home/vladimir/.local/share/virtualenvs/ICFES-SocioEconomico-eS63OEPi/lib/python3.8/site-packages/shap/explainers/_tree.py", line 280, in shap_values
    phi = self.model.original_model.predict(
  File "/home/vladimir/.local/share/virtualenvs/ICFES-SocioEconomico-eS63OEPi/lib/python3.8/site-packages/xgboost/core.py", line 1397, in predict
    preds = preds.reshape(nrow, ngroup, data.num_col() + 1)
ValueError: cannot reshape array of size 23400 into shape (100,2,93)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "shapsummaryplots.py", line 122, in <module>
    shap_summary_plots(2014, 2)
  File "shapsummaryplots.py", line 97, in shap_summary_plots
    shap_values = explainer.shap_values(xgb.DMatrix(X))
  File "/home/vladimir/.local/share/virtualenvs/ICFES-SocioEconomico-eS63OEPi/lib/python3.8/site-packages/shap/explainers/_tree.py", line 285, in shap_values
    raise ValueError("This reshape error is often caused by passing a bad data matrix to SHAP. " \
ValueError: This reshape error is often caused by passing a bad data matrix to SHAP. See https://github.com/slundberg/shap/issues/580
```

so out of nowhere it seems that SHAP is passing new data to XGBoost? (`ValueError: cannot reshape array of size 23400 into shape (100,2,93)`)

Definitely I'm passing the correct number of columns, no matter if I sample or not the features dataframe, as `model.predict(xgb.DMatrix(X))` works ok, but then when getting the shap values with the explainer it fails!

My shap version is 0.37 and my xgboost version is 1.2.1

_Originally posted by @VolodyaCO in https://github.com/slundberg/shap/issues/580#issuecomment-745382015_

**Comment by nparraa10** [comment]
I have the same error and need help with this!

**Comment by PLPATENOTRE** [comment]
Hi there ! 

I come late to the battle but finally got the solution to the issue.

```python

explainer = shap.TreeExplainer(model)
shap_values = explainer.shap_values(X, y=y.values)
```

This worked for me. And be careful that your model matches with your X_train, in term of number of columns.

Hope this helps ! 
Cheers

**Comment by arnabsinha99** [comment]
> Hi there !
> 
> I come late to the battle but finally got the solution to the issue.
> 
> ```python
> explainer = shap.TreeExplainer(model)
> shap_values = explainer.shap_values(X, y=y.values)
> ```
> 
> This worked for me. And be careful that your model matches with your X_train, in term of number of columns.
> 
> Hope this helps !
> Cheers

This does not help me actually.. the columns are the same number as trained and being passed in the SHAP.

**Comment by jacobmardian** [comment]
This solution did not help me either. I believe this issue is related to the size of the dataset. When running shap values on one million rows it is successful:
```python
shap_vals = explainer.shap_values(X.iloc[1:1000000,:], y[1:1000000].values)
```
However, when I run the exact same code with 10 million rows:

```python
shap_vals = explainer.shap_values(X.iloc[1:10000000,:], y[1:10000000].values)
```
I get this error:
```
XGBoostError: [12:33:27] c:\ci\xgboost-split_1638290375667\work\src\c_api\c_api_utils.h:119: Check failed: std::accumulate(shape.cbegin(), shape.cend(), 1, std::multiplies<>{}) == chunksize * rows (-1419050067 vs. 7170884525) : 

The above exception was the direct cause of the following exception:

ValueError: This reshape error is often caused by passing a bad data matrix to SHAP. See https://github.com/slundberg/shap/issues/580
```
Any ideas?

**Comment by asdfrfg** [comment]
> Hi there !
> 
> I come late to the battle but finally got the solution to the issue.
> 
> ```python
> explainer = shap.TreeExplainer(model)
> shap_values = explainer.shap_values(X, y=y.values)
> ```
> 
> This worked for me. And be careful that your model matches with your X_train, in term of number of columns.
> 
> Hope this helps ! Cheers

sorry for ask when so long have been 
when i type 
"explainer = shap.TreeExplainer(model)
shap_values = explainer.shap_values(X_test)"

it will report the error like this discuss, but when i try

"explainer = shap.TreeExplainer(model,X_test)
shap_values = explainer.shap_values(X_test)"
it work! it looks like different with the most answer ,may i ask why it work?and how this function work?or where i can find the guidebook about this function?

**Comment by asdfrfg** [comment]
guys i find sometime maybe useful https://shap.readthedocs.io/en/latest/example_notebooks/api_examples/explainers/GPUTree.html
