### ISSUE TITLE
Interaction value summary plot broke in 0.20

### ISSUE THREAD

**Issue by gabrielcs** [shap/shap#173]
When trying to create the summary plot with interaction values in the [NHANES I sample notebook](https://github.com/gabrielcs/shap/blob/master/notebooks/tree_explainer/NHANES%20I%20Survival%20Model.ipynb) I get the following error (SHAP `0.20.1`):

```
---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
<ipython-input-31-60630d2823f1> in <module>()
----> 1 local_shap.summary_plot(shap_interaction_values, X.iloc[:2000,:], color_bar=True)

~/workspace/shap/local_shap/plots.py in summary_plot(shap_values, features, feature_names, max_display, plot_type, color, axis_color, title, alpha, show, sort, color_bar, auto_size_plot, layered_violin_max_num_bins, class_names)
    380         pl.figure(figsize=(1.5 * max_display + 1, 0.8 * max_display + 1))
    381         pl.subplot(1, max_display, 1)
--> 382         proj_shap_values = shap_values[:, sort_inds[0], np.hstack((sort_inds, len(sort_inds)))]
    383         #proj_shap_values = shap_values[:, sort_inds[0], sort_inds]
    384         proj_shap_values[:, 1:] *= 2  # because off diag effects are split in half

IndexError: index 19 is out of bounds for axis 2 with size 19
```

**Comment by florianst** [comment]
Hey @slundberg, I'm running into this problem using a shap build from the current master branch. My model takes two inputs which I supply as a list to summary_plot, as in #439:
```
            next_target1, next_target2, y = next(iter(trainLoader))
            indexes_target1 = np.random.choice(next_target1.shape[0], 300, replace=False)
            indexes_target2 = np.random.choice(next_target2.shape[0], 300, replace=False)
            explain_target1, explain_target2 = next_target1[indexes_target1], next_target2[indexes_target2]
            explainer = shap.DeepExplainer(model, [explain_target1, explain_target2])
            
            test_target1, test_target2, y = next(iter(testLoader))
            to_explain = [test_target1[indexes_target1], test_target2[indexes_target2]]
            shap_values = explainer.shap_values(to_explain)
            shapplot = shap.summary_plot(shap_values, to_explain)
```
The testLoader gives a torch tensor of shape (300,14,23), i.e. 300 data points with 23 features in 14 channels. I get a similar error:
```
Traceback (most recent call last):
  File "train.py", line 431, in <module>
    shapplot = shap.summary_plot(shap_values, to_explain)
  File "/users/florianst/.local/lib/python3.6/site-packages/shap-0.29.3.dev0-py3.6-linux-x86_64.egg/shap/plots/summary.py", line 398, in summary_plot
    pl.barh(
IndexError: index 22 is out of bounds for axis 0 with size 14
```
Any ideas?

**Comment by slundberg** [comment]
Hmm...could you share the length of shap_values and the dimensions of all the things inside it (and to_explain)?
