### ISSUE TITLE
ModuleNotFoundError: No module named 'IPython' on import shap

### ISSUE THREAD

**Issue by rooom13** [shap/shap#1783]
I'm using the shap package outside a Jupyter Notebook.

On package import I already receive an `ModuleNotFoundError: No module named 'IPython'`
`shap==0.38.1`
`python==3.6.9`

```
>>> import shap
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/share/virtualenvs/my-env-rJwChpKj/lib/python3.6/site-packages/shap/__init__.py", line 38, in <module>
    from .plots._beeswarm import summary_legacy as summary_plot
  File "/home/virtualenvs/my-env-rJwChpKj/lib/python3.6/site-packages/shap/plots/__init__.py", line 8, in <module>
    from ._image import image, image_to_text
  File "/home/virtualenvs/my-venv-rJwChpKj/lib/python3.6/site-packages/shap/plots/_image.py", line 15, in <module>
    from IPython.core.display import display, HTML
ModuleNotFoundError: No module named 'IPython'
```

With the version `shap==0.38.1` this was not ocurring

**Comment by roi-meir** [comment]
This is the same issue as #1757 
I opened a pull request today to resolve it #1779

**Comment by rooom13** [comment]
being handled in #1749
