### ISSUE TITLE
IndexError: index 5 is out of bounds for axis 1 with size 1

### ISSUE THREAD

**Issue by frankligy** [shap/shap#1801]
I am aware that similar issues exist but none of them solves my problems.

I used a toy example:
```
X,y = shap.datasets.boston()
model = GradientBoostingRegressor()
model.fit(X,y)
explainer = shap.TreeExplainer(model=model)
shap_values_explanation = explainer(X)
```
So far so good, then I tried to generate the scatter plot
```
shap.plots.scatter(shap_values_explanation[:,'RM'])
```

Error:
```
Traceback (most recent call last):
  File "/Users/ligk2e/opt/anaconda3/envs/scanpy/lib/python3.6/site-packages/IPython/core/interactiveshell.py", line 3343, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-24-b2a9028afaf3>", line 1, in <module>
    shap.plots.scatter(shap_values_explanation[:,'RM'])
  File "/Users/ligk2e/opt/anaconda3/envs/scanpy/lib/python3.6/site-packages/shap/_explanation.py", line 297, in __getitem__
    new_self._s = self._s.__getitem__(item)
  File "/Users/ligk2e/opt/anaconda3/envs/scanpy/lib/python3.6/site-packages/slicer/slicer.py", line 112, in __getitem__
    sliced_o = tracked[slicer_index]
  File "/Users/ligk2e/opt/anaconda3/envs/scanpy/lib/python3.6/site-packages/slicer/slicer_internal.py", line 69, in __getitem__
    return UnifiedDataHandler.slice(self.o, index_tup, self.max_dim)
  File "/Users/ligk2e/opt/anaconda3/envs/scanpy/lib/python3.6/site-packages/slicer/slicer_internal.py", line 582, in slice
    is_element, sliced_o, cut = head_slice(o, index_tup, max_dim)
  File "/Users/ligk2e/opt/anaconda3/envs/scanpy/lib/python3.6/site-packages/slicer/slicer_internal.py", line 418, in head_slice
    sliced_o = o[cut_index]
IndexError: index 5 is out of bounds for axis 1 with size 1
```

It is clear that this error comes from ```slicer``` package, it shouldn't be related to matplotlib or shap version, my shap version is 0.38.1, and it is a persistent issue, I can not generate scatter plots in all my cases.

Also, I tried to understand this ```Explanation``` object, it seems like all the attributes explanations are yet to be completed( https://shap.readthedocs.io/en/latest/generated/shap.Explanation.html#shap.Explanation ), which prompted me to this issue page and try to get some hints on how to solve this problem.

Thank you,
Frank

**Comment by CanML** [comment]
I am having the same problem with a fairly basic use case and getting the same error in shap 0.39.0 and slicer 0.0.7:

IndexError: index 1 is out of bounds for axis 1 with size 1

Frank - were you ever able to resolve it?

**Comment by frankligy** [comment]
> I am having the same problem with a fairly basic use case and getting the same error in shap 0.39.0 and slicer 0.0.7:
> 
> IndexError: index 1 is out of bounds for axis 1 with size 1
> 
> Frank - were you ever able to resolve it?

Hi,

I haven't been able to resolve it, the workaround is to just plot the scatter plot from the scratch, which is not horribly difficult but it is certainly a hassle to not be able to run this command in the shap package.

Best,
Frank

**Comment by CanML** [comment]
Hi Frank,

Would you mind posting a quick example of your workaround? I've tried the ellipsis (which some refer to as stretch so I assume is what you mean by "stretch") but got the exact same error as when I sliced it.

**Comment by CanML** [comment]
As an update - if the model I use is LGBM, it works fine. If my model is a random forest or ExtraTrees model from sklearn, it doesn't work. So, there may be inconsistencies in how things are processed by the shap library (via the Tree explainer and associated Explanation object) across different model types.

**Comment by frankligy** [comment]
> Hi Frank,
> 
> Would you mind posting a quick example of your workaround? I've tried the ellipsis (which some refer to as stretch so I assume is what you mean by "stretch") but got the exact same error as when I sliced it.

I am sorry my bad, I mean from the scratch. So I basically pull out the shap value from the TreeExplainer object and use matplotlib to draw scatter plot by myself.

**Comment by CanML** [comment]
No problem, thanks for clarifying.

Yes, it seems like the slice notation works just fine for some models but not for others, so it's possible there needs to be some checks/standardization added to the shap Explanation and/or slicer code.

**Comment by CanML** [comment]
@slundberg just bumping this issue since it can impact a decent chunk of shap visualization functionality and I am guessing is a fairly easy fix for someone who can identify the specific quirk causing this issue.

**Comment by JohannaB-IRT** [comment]
Hi,

I'm new at using the SHAP package but I've encountered the same problem while applying the toy tree ensemble example from the README. 
It works fine when using a XGRegressor but fails with the same slicing issue when using RandomForestRegressor from scikit-learn on the same dataset.

The solution that works for me : force the Explainer `expected_value` to be an numeric value instead of an array of one element. That way the `base_values` from the shap_values has the dimension expected by the figure that is `(n, )` and not `(n,1)` : 

```
rf_model = RandomForestRegressor().fit(X, y)
rf_explainer = shap.Explainer(rf_model)
rf_explainer.expected_value = rf_explainer.expected_value[0]  # Additional line to force the dim of base_values
rf_shap_values = rf_explainer(X)
shap.plots.scatter(rf_shap_values[:,"RM"], color=rf_shap_values)
```
I don't know precisely why this solve the problem but it does. And I don't know if it is the same for other type of models but I guess it is worth a try because the slicing issue points to a shape/dimension issue.


NB : This solution also solves the problem of the waterfall plot call with the syntax:
```
shap.plots.waterfall(rf_shap_values[0])
```

**Comment by juandpinto** [comment]
@JohannaB-IRT, your extra line has fixed all the issues I've been having with Shap. Thank you! 👏👏👏

**Comment by ericluo04** [comment]
I haven't found a solution for a similar index error with text plots using huggingface models, so I'm kindly piggybacking off this thread to share. I use colab GPU to train (which explains the cuda bits of code) - delete these for a CPU implementation. This solution borrows heavily from the official shap [implementation](https://shap.readthedocs.io/en/latest/example_notebooks/api_examples/plots/text.html?highlight=hugging%20face#) with some modifications and necessary clarifications. 

I fine-tuned an NLP model, which I load in here:
```
# DeBERTa tokenizer
db_tokenizer = DebertaTokenizer.from_pretrained('microsoft/deberta-base')
# load pretrained model
deBERTa = DebertaForSequenceClassification.from_pretrained(f"{path}3_output/Weights/2021-06-22 deBERTa").cuda()
```

Then, I define my explainer function. Importantly, for NLP models, you cannot simply feed in the model into the explainer object. You have to write a different function that explicitly makes predictions using your model given text input. 
```
# define a prediction function
def shap_pred(text):
    tensor_text = db_tokenizer(list(text), truncation=True, padding=True, return_tensors="pt").to('cuda')
    outputs = deBERTa(**tensor_text)[0].detach().cpu().numpy()
    return outputs

# build an explainer using a token masker
explainer = shap.Explainer(shap_pred, db_tokenizer)

# generate shapley values
shap_values = explainer(x_train)
```

Now, let's try to make text plots. I've realized that the issue is in `.base_values`. By default, these are embedded in an array but these need to just be numbers for the plotting functions to work. You should produce the below errors if you run these:
```
# local explanation for your first example
shap.plots.text(shap_values[0])
IndexError: index 1 is out of bounds for axis 0 with size 1

# global summary explanation
shap.plots.bar(shap_values.abs.sum(0), max_display=50)
(no error here, but the plot only produces the CLS token)
```

To resolve this, you should change your indexing syntax. For my regression task (where the number of labels = 1), the below code works:
```
# local explanation for your first example
shap.plots.text(shap_values[0, :, 0])
# global summary explanation
shap.plots.bar(shap_values[:, :, 0].abs.sum(0), max_display=50)
```

For a classification task (where the number of labels > 1), you should adjust the last index appropriately. In fact, the [main github page](https://github.com/slundberg/shap) has an implementation of this where they simply use the name of the class instead of the index:
```
# visualize the first prediction's explanation for the POSITIVE output class
shap.plots.text(shap_values[0, :, "POSITIVE"])
```

**Comment by SebDarco** [comment]
> 
> 
> Hi,
> 
> I'm new at using the SHAP package but I've encountered the same problem while applying the toy tree ensemble example from the README. It works fine when using a XGRegressor but fails with the same slicing issue when using RandomForestRegressor from scikit-learn on the same dataset.
> 
> The solution that works for me : force the Explainer `expected_value` to be an numeric value instead of an array of one element. That way the `base_values` from the shap_values has the dimension expected by the figure that is `(n, )` and not `(n,1)` :
> 
> ```
> rf_model = RandomForestRegressor().fit(X, y)
> rf_explainer = shap.Explainer(rf_model)
> rf_explainer.expected_value = rf_explainer.expected_value[0]  # Additional line to force the dim of base_values
> rf_shap_values = rf_explainer(X)
> shap.plots.scatter(rf_shap_values[:,"RM"], color=rf_shap_values)
> ```
> 
> I don't know precisely why this solve the problem but it does. And I don't know if it is the same for other type of models but I guess it is worth a try because the slicing issue points to a shape/dimension issue.
> 
> NB : This solution also solves the problem of the waterfall plot call with the syntax:
> 
> ```
> shap.plots.waterfall(rf_shap_values[0])
> ```

Hello, Johanna, Thank you !
Your solution also worked for me (Shap 0.39.0 with RandomForestRegressor) and solve both the Scatter issue and the Waterfall issue below

`Exception: waterfall_plot requires a scalar base_values of the model output as the first parameter, but you have passed an array as the first parameter! Try shap.waterfall_plot(explainer.base_values[0], values[0], X[0]) or for multi-output models try shap.waterfall_plot(explainer.base_values[0], values[0][0], X[0]).`

**Comment by suzuki-shm** [comment]
Hi,

@JohannaB-IRT  has already mentioned the cause of this problem as 
> The solution that works for me : force the Explainer expected_value to be an numeric value instead of an array of one element. That way the base_values from the shap_values has the dimension expected by the figure that is (n, ) and not (n,1) :

I tried to find out why it becomes an array and found out that there are at least two reasons.

## 1. An output of the model is a 2D array and ExactExplainer is used

@frankligy reported this problem with TreeExplainer, but it can also happen with ExactExplainer. You can test this with the following code. This is relevant to https://github.com/scikit-learn/scikit-learn/issues/19693 .

```python
model = Ridge()
model.fit(X,y.reshape(len(y), 1)) # Transform to 2D array
explainer = shap.Explainer(model.predict, X)
shap_values_explanation = explainer(X)
shap_values_explanation.base_values.shape
> (506, 1)
```

In this case, the cause is that the output of the model is a two-dimensional array; in Scikit-learn, if y is a two-dimensional array such as (n_data, 1) during training, the output from `Ridge().predict` will also be a two-dimensional array. This error occurs because ExactExplainer uses the output of the model.

In the above example, `y` is forced to be two-dimensional, but the following process is often seen. In this case, it is also two-dimensional.
```python
df = ...
X_names = [ foo, bar, ... ]
y_names = [ baz ]
X = df[X_names]
y = df[y_names] # Single Column DataFrame 
```

To deal with this problem, converting the target variable to a 1D array would be appropriate.
```python
model.fit(X, y.ravel())
```

## 2. A tree structure model + TreeExplainer

This corresponds to the report of @frankligy. The cause of this is in the following section.

https://github.com/slundberg/shap/blob/429fb3e0ac2ef179f1cff7e1a64b4f7b26f41eb5/shap/explainers/_tree.py#L191

The base_offset that is added here is processed in the next part to be a 1D array in some tree models. This results in the final `expected_value` being an array.

https://github.com/slundberg/shap/blob/429fb3e0ac2ef179f1cff7e1a64b4f7b26f41eb5/shap/explainers/_tree.py#L1024


A possible way to deal with this problem is to calculate the expected_value by explicitly giving the data used for training.

```python
model = GradientBoostingRegressor()
model.fit(X,y)
explainer = shap.TreeExplainer(model=model, data=X)
shap_values_explanation = explainer(X)
shap_values_explanation.base_values.shape
> (506,)
```

In this case, the following steps work and avoid the arraying process.

https://github.com/slundberg/shap/blob/429fb3e0ac2ef179f1cff7e1a64b4f7b26f41eb5/shap/explainers/_tree.py#L180

I hope this problem will be fixed. In this case, you can use https://github.com/slundberg/shap/issues/1801#issuecomment-811091856 to deal with this problem. You can also use the following procedure to make it work uniformly even when `Explainer` is working correctly.

```python
explainer = shap.Explainer(model)
# Helper procedure
if hasattr(explainer, "expected_value"):
    if type(explainer.expected_value) is np.ndarray:
        explainer.expected_value = explainer.expected_value.mean()
shap_values = explainer(X)
```

**Comment by 688spiderbin** [comment]
> I haven't found a solution for a similar index error with text plots using huggingface models, so I'm kindly piggybacking off this thread to share. I use colab GPU to train (which explains the cuda bits of code) - delete these for a CPU implementation. This solution borrows heavily from the official shap [implementation](https://shap.readthedocs.io/en/latest/example_notebooks/api_examples/plots/text.html?highlight=hugging%20face#) with some modifications and necessary clarifications.
> 
> I fine-tuned an NLP model, which I load in here:
> 
> ```
> # DeBERTa tokenizer
> db_tokenizer = DebertaTokenizer.from_pretrained('microsoft/deberta-base')
> # load pretrained model
> deBERTa = DebertaForSequenceClassification.from_pretrained(f"{path}3_output/Weights/2021-06-22 deBERTa").cuda()
> ```
> 
> Then, I define my explainer function. Importantly, for NLP models, you cannot simply feed in the model into the explainer object. You have to write a different function that explicitly makes predictions using your model given text input.
> 
> ```
> # define a prediction function
> def shap_pred(text):
>     tensor_text = db_tokenizer(list(text), truncation=True, padding=True, return_tensors="pt").to('cuda')
>     outputs = deBERTa(**tensor_text)[0].detach().cpu().numpy()
>     return outputs
> 
> # build an explainer using a token masker
> explainer = shap.Explainer(shap_pred, db_tokenizer)
> 
> # generate shapley values
> shap_values = explainer(x_train)
> ```
> 
> Now, let's try to make text plots. I've realized that the issue is in `.base_values`. By default, these are embedded in an array but these need to just be numbers for the plotting functions to work. You should produce the below errors if you run these:
> 
> ```
> # local explanation for your first example
> shap.plots.text(shap_values[0])
> IndexError: index 1 is out of bounds for axis 0 with size 1
> 
> # global summary explanation
> shap.plots.bar(shap_values.abs.sum(0), max_display=50)
> (no error here, but the plot only produces the CLS token)
> ```
> 
> To resolve this, you should change your indexing syntax. For my regression task (where the number of labels = 1), the below code works:
> 
> ```
> # local explanation for your first example
> shap.plots.text(shap_values[0, :, 0])
> # global summary explanation
> shap.plots.bar(shap_values[:, :, 0].abs.sum(0), max_display=50)
> ```
> 
> For a classification task (where the number of labels > 1), you should adjust the last index appropriately. In fact, the [main github page](https://github.com/slundberg/shap) has an implementation of this where they simply use the name of the class instead of the index:
> 
> ```
> # visualize the first prediction's explanation for the POSITIVE output class
> shap.plots.text(shap_values[0, :, "POSITIVE"])
> ```

Hello, thank you for sharing. I have the problem with shap.plots.bar(shap_values[:,:,'0'].mean(0))
![image](https://user-images.githubusercontent.com/62921113/235075996-b24a1d69-d345-48b7-8929-1dbd6b95e19f.png)
and this is my shap value shape
![image](https://user-images.githubusercontent.com/62921113/235076403-6f1745eb-54b7-41c7-b2e4-ca59d8274556.png)

**Comment by 688spiderbin** [comment]
@ericluo04 Hello, thank you for sharing huggingface model with shap. I have another problem when using  shap.plots.bar(shap_values[:,:,'0'].mean(0)) to get global explanation in transformer model. I have get this problem.
![image](https://user-images.githubusercontent.com/62921113/235077777-d8b005f4-0146-432e-b3fd-158b557be20d.png)
And I am doing two classification task, my shap_value shape is below
![image](https://user-images.githubusercontent.com/62921113/235078044-bc34de2f-48a3-45fb-a748-7e59595b1644.png)
how should I fix this problem , thank you for reply !

**Comment by iawang** [comment]
> 您好，感谢您与Shap分享拥抱脸模型。使用 shap.plots.bar（shap_values[：，：，'0'].mean（0）） 在变压器模型中获取全局解释时，我遇到了另一个问题。我遇到了这个问题。 ![图像](https://user-images.githubusercontent.com/62921113/235077777-d8b005f4-0146-432e-b3fd-158b557be20d.png)而且我正在做两个分类任务，我的shap_value形状在下面![图像](https://user-images.githubusercontent.com/62921113/235078044-bc34de2f-48a3-45fb-a748-7e59595b1644.png)应该如何解决这个问题，谢谢你的回复！

I have the same problem as you, have you solved it? How did you solve it? Thank you!

**Comment by moulhamPy** [comment]
in RF there is a possibility that the your shap_values is contained in an extra array layer which is not needed I had classification problem with 23 features and 2 classes. shap_values was giving me a (1,23,2) matrix i.e. (1, number of features, number of classes).
I fixed this by getting rid of this layer using

shap_values_for_plotting = shap_values[0][:, 1]

Not sure how my answer can be applied to other models but as a short answer see the shap_values.shape if it matches your expectation and try to fix it if not. I hope this helps
