### ISSUE TITLE
Shap installation failing in Docker container

### ISSUE THREAD

**Issue by kjanko** [shap/shap#1811]
I'm trying to create a simple container with shap in it:

```
FROM python:3.8

USER root
WORKDIR /workdir

RUN pip3 install --upgrade setuptools pip
RUN pip3 install shap
```
This fails with a simple error:

> ERROR: No .egg-info directory found in /tmp/pip-pip-egg-info-skuygqi6

From looking at other issues, this seems to be solved by upgrading setuptools, but as you can see here it doesn't happen. Any idea?

**Comment by kjanko** [comment]
Issue is caused because we are behind a proxy:

```
    Running setup.py (path:/tmp/pip-install-qfis2b_i/shap_7b4a926dfecc476da5d19391f62eafac/setup.py) egg_info for package shap
    Created temporary directory: /tmp/pip-pip-egg-info-al4w2ues
[91m    Running command python setup.py egg_info
[0m[91m    WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ConnectTimeoutError(<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7fe7470b4100>, 'Connection to pypi.org timed out. (connect timeout=15)')': /simple/numpy/
```

Instead of using the propagated proxy to pip, It's trying to use the pypi official repository.

**Comment by kjanko** [comment]
Here's the entire stacktrace:

```
    Running setup.py (path:/tmp/pip-install-qfis2b_i/shap_7b4a926dfecc476da5d19391f62eafac/setup.py) egg_info for package shap
    Created temporary directory: /tmp/pip-pip-egg-info-al4w2ues
[91m    Running command python setup.py egg_info
[0m[91m    WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ConnectTimeoutError(<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7fe7470b4100>, 'Connection to pypi.org timed out. (connect timeout=15)')': /simple/numpy/
[0m[91m    WARNING: Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ConnectTimeoutError(<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7fe7470b42e0>, 'Connection to pypi.org timed out. (connect timeout=15)')': /simple/numpy/
[0m[91m    WARNING: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ConnectTimeoutError(<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7fe7470b4460>, 'Connection to pypi.org timed out. (connect timeout=15)')': /simple/numpy/
[0m[91m    WARNING: Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ConnectTimeoutError(<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7fe7470b45e0>, 'Connection to pypi.org timed out. (connect timeout=15)')': /simple/numpy/
[0m[91m    WARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ConnectTimeoutError(<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7fe7470b4760>, 'Connection to pypi.org timed out. (connect timeout=15)')': /simple/numpy/
[0m[91m    ERROR: Could not find a version that satisfies the requirement numpy
[0m[91m    ERROR: No matching distribution found for numpy
[0m[91m    WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ConnectTimeoutError(<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7f0b5dac8a60>, 'Connection to pypi.org timed out. (connect timeout=15)')': /simple/numpy/
[0m[91m    WARNING: Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ConnectTimeoutError(<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7f0b5dac8c40>, 'Connection to pypi.org timed out. (connect timeout=15)')': /simple/numpy/
[0m[91m    WARNING: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ConnectTimeoutError(<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7f0b5dac8dc0>, 'Connection to pypi.org timed out. (connect timeout=15)')': /simple/numpy/
[0m[91m    WARNING: Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ConnectTimeoutError(<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7f0b5dac8f40>, 'Connection to pypi.org timed out. (connect timeout=15)')': /simple/numpy/
[0m[91m    WARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ConnectTimeoutError(<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7f0b5daf2100>, 'Connection to pypi.org timed out. (connect timeout=15)')': /simple/numpy/
[0m[91m    ERROR: Could not find a version that satisfies the requirement numpy
[0m[91m    ERROR: No matching distribution found for numpy
[0m[91m    The nvcc binary could not be located in your $PATH. Either  add it to your path, or set $CUDAHOME to enable CUDA
    Error building cuda module: TypeError('cannot unpack non-iterable NoneType object')
[0m[91m    WARNING: Could not compile cuda extensions
[0m[91m    Command '['/usr/local/bin/python', '-m', 'pip', '--disable-pip-version-check', 'wheel', '--no-deps', '-w', '/tmp/tmp_32z5e1s', '--quiet', 'numpy']' returned non-zero exit status 1.
[0m[91m    WARNING: The C extension could not be compiled, sklearn tree models not supported.
[0m[91m    Command '['/usr/local/bin/python', '-m', 'pip', '--disable-pip-version-check', 'wheel', '--no-deps', '-w', '/tmp/tmpzn9o4m0g', '--quiet', 'numpy']' returned non-zero exit status 1.
[0m[91m    ERROR: Failed to build!
[0m[91mERROR: No .egg-info directory found in /tmp/pip-pip-egg-info-al4w2ues
[0mException information:
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/pip/_vendor/resolvelib/resolvers.py", line 171, in _merge_into_criterion
    crit = self.state.criteria[name]
KeyError: 'shap'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/pip/_internal/cli/base_command.py", line 189, in _main
    status = self.run(options, args)
  File "/usr/local/lib/python3.8/site-packages/pip/_internal/cli/req_command.py", line 178, in wrapper
    return func(self, options, args)
  File "/usr/local/lib/python3.8/site-packages/pip/_internal/commands/install.py", line 316, in run
    requirement_set = resolver.resolve(
  File "/usr/local/lib/python3.8/site-packages/pip/_internal/resolution/resolvelib/resolver.py", line 121, in resolve
    self._result = resolver.resolve(
  File "/usr/local/lib/python3.8/site-packages/pip/_vendor/resolvelib/resolvers.py", line 453, in resolve
    state = resolution.resolve(requirements, max_rounds=max_rounds)
  File "/usr/local/lib/python3.8/site-packages/pip/_vendor/resolvelib/resolvers.py", line 318, in resolve
    name, crit = self._merge_into_criterion(r, parent=None)
  File "/usr/local/lib/python3.8/site-packages/pip/_vendor/resolvelib/resolvers.py", line 173, in _merge_into_criterion
    crit = Criterion.from_requirement(self._p, requirement, parent)
  File "/usr/local/lib/python3.8/site-packages/pip/_vendor/resolvelib/resolvers.py", line 82, in from_requirement
    if not cands:
  File "/usr/local/lib/python3.8/site-packages/pip/_vendor/resolvelib/structs.py", line 124, in __bool__
    return bool(self._sequence)
  File "/usr/local/lib/python3.8/site-packages/pip/_internal/resolution/resolvelib/found_candidates.py", line 143, in __bool__
    return any(self)
  File "/usr/local/lib/python3.8/site-packages/pip/_internal/resolution/resolvelib/found_candidates.py", line 38, in _iter_built
    candidate = func()
  File "/usr/local/lib/python3.8/site-packages/pip/_internal/resolution/resolvelib/factory.py", line 167, in _make_candidate_from_link
    self._link_candidate_cache[link] = LinkCandidate(
  File "/usr/local/lib/python3.8/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 300, in __init__
    super().__init__(
  File "/usr/local/lib/python3.8/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 144, in __init__
    self.dist = self._prepare()
  File "/usr/local/lib/python3.8/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 226, in _prepare
    dist = self._prepare_distribution()
  File "/usr/local/lib/python3.8/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 311, in _prepare_distribution
    return self._factory.preparer.prepare_linked_requirement(
  File "/usr/local/lib/python3.8/site-packages/pip/_internal/operations/prepare.py", line 457, in prepare_linked_requirement
    return self._prepare_linked_requirement(req, parallel_builds)
  File "/usr/local/lib/python3.8/site-packages/pip/_internal/operations/prepare.py", line 500, in _prepare_linked_requirement
    dist = _get_prepared_distribution(
  File "/usr/local/lib/python3.8/site-packages/pip/_internal/operations/prepare.py", line 66, in _get_prepared_distribution
    abstract_dist.prepare_distribution_metadata(finder, build_isolation)
  File "/usr/local/lib/python3.8/site-packages/pip/_internal/distributions/sdist.py", line 41, in prepare_distribution_metadata
    self.req.prepare_metadata()
  File "/usr/local/lib/python3.8/site-packages/pip/_internal/req/req_install.py", line 549, in prepare_metadata
    self.metadata_directory = self._generate_metadata()
  File "/usr/local/lib/python3.8/site-packages/pip/_internal/req/req_install.py", line 524, in _generate_metadata
    return generate_metadata_legacy(
  File "/usr/local/lib/python3.8/site-packages/pip/_internal/operations/build/metadata_legacy.py", line 77, in generate_metadata
    return _find_egg_info(egg_info_dir)
  File "/usr/local/lib/python3.8/site-packages/pip/_internal/operations/build/metadata_legacy.py", line 28, in _find_egg_info
    raise InstallationError(
pip._internal.exceptions.InstallationError: No .egg-info directory found in /tmp/pip-pip-egg-info-al4w2ues
Removed shap from ######
Removed build tracker: '/tmp/pip-req-tracker-mv8ethr4'

```

**Comment by dusvyat** [comment]
@kjanko - did you find a resolution for this? I seem to be running into the same issue

**Comment by kjanko** [comment]
@dusvyat Uh, in my case it was an issue caused by some of SHAP's chain dependencies - the pip HTTP proxy didn't resolve after the first level. I ended up adding a static pip configuration file inside the container and it solved the issue.

**Comment by kortschotUB** [comment]
@kjanko are you able to share some more details on your static config file? I'm running into what I assume to be a similar issue where pip is failing to build wheels for shap, but it's fine for every other package in my requirements.txt (see error code below)

`#17 27.37 Failed to build shap
#17 27.37 ERROR: Could not build wheels for shap, which is required to install pyproject.toml-based projects`
