### ISSUE TITLE
Installation issue on Python 3.8/3.9 on Big Sur

### ISSUE THREAD

**Issue by mikekap** [shap/shap#1833]
Python shipped a bug in 3.8 & 3.9 that a few users are hitting in osx 11: https://bugs.python.org/issue42504 . This is mostly harmless for a lot of packages but is an issue when installing the `shap` package:
```
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/sg/65tk18cj6md7chv7p96s2wlw0000gn/T/pip-download-tjxehxuh/shap/setup.py", line 25, in <module>
        python_target = LooseVersion(get_config_var('MACOSX_DEPLOYMENT_TARGET'))
      File "/usr/local/Cellar/python@3.8/3.8.7_2/Frameworks/Python.framework/Versions/3.8/lib/python3.8/distutils/version.py", line 304, in __init__
        self.parse(vstring)
      File "/usr/local/Cellar/python@3.8/3.8.7_2/Frameworks/Python.framework/Versions/3.8/lib/python3.8/distutils/version.py", line 312, in parse
        components = [x for x in self.component_re.split(vstring)
    TypeError: expected string or bytes-like object
```

Pandas shipped a fix for this at https://github.com/pandas-dev/pandas/pull/38766. Could shap add a similar fix in setup.py?

**Comment by prempiyush** [comment]
Seeing the same error on Python 3.7.10 in Mac 11.2.3

```   
 ERROR: Command errored out with exit status 1:
     command: /Users/prempiyush/work/code/drift/venv/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/qg/2zxf7p2100nf3084v003_1sm0000gn/T/pip-install-jpe0lpnr/shap_5e9e222b3f2a4857aec75037d0bad6d1/setup.py'"'"'; __file__='"'"'/private/var/folders/qg/2zxf7p2100nf3084v003_1sm0000gn/T/pip-install-jpe0lpnr/shap_5e9e222b3f2a4857aec75037d0bad6d1/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /private/var/folders/qg/2zxf7p2100nf3084v003_1sm0000gn/T/pip-pip-egg-info-jy1kmz7s
         cwd: /private/var/folders/qg/2zxf7p2100nf3084v003_1sm0000gn/T/pip-install-jpe0lpnr/shap_5e9e222b3f2a4857aec75037d0bad6d1/
    Complete output (9 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/qg/2zxf7p2100nf3084v003_1sm0000gn/T/pip-install-jpe0lpnr/shap_5e9e222b3f2a4857aec75037d0bad6d1/setup.py", line 25, in <module>
        python_target = LooseVersion(get_config_var('MACOSX_DEPLOYMENT_TARGET'))
      File "/usr/local/Cellar/python@3.7/3.7.10_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/distutils/version.py", line 304, in __init__
        self.parse(vstring)
      File "/usr/local/Cellar/python@3.7/3.7.10_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/distutils/version.py", line 312, in parse
        components = [x for x in self.component_re.split(vstring)
    TypeError: expected string or bytes-like object
    ----------------------------------------
```

**Comment by mikekap** [comment]
For folks having this issue, a somewhat-not-awesome fix is to patch python itself: https://gist.github.com/mikekap/1c1391eb5e3c3e606fb893e2145598a4 .

In case someone wants to repro this: you need to (re)install python while already on Big Sur (i.e. `brew reinstall python` or equivalent). If you had a python version that you installed from a previous OSX release, it won't exhibit this issue. Only new installs are affected.

**Comment by naturalethic** [comment]
@mikekap If you apply this patch to the installed version, re-installing will remove it.  Simply apply the patch and you are good to go.

**Comment by patricksheehan** [comment]
FWIW I'm running into this now, is the Python patch the only fix?

**Comment by rtstock** [comment]
Try using: pip3 install ...

**Comment by mikekap** [comment]
Installing Python 3.9.2 or newer also fixes this issue

**Comment by conqueror** [comment]
> Installing Python 3.9.2 or newer also fixes this issue

I tried to install SHAP with Python 3.9.8 on macOS Big Sur and I receive the following error:

```
In file included from shap/cext/_cext.cc:3:
  In file included from /Library/Frameworks/Python.framework/Versions/3.9/include/python3.9/Python.h:25:
  In file included from /Library/Developer/CommandLineTools/usr/bin/../include/c++/v1/stdio.h:107:
  In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/stdio.h:64:
  In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/_stdio.h:75:
  In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/sys/_types/_va_list.h:31:
  /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/machine/types.h:37:2: error: architecture not supported
  #error architecture not supported
   ^
  fatal error: too many errors emitted, stopping now [-ferror-limit=]
  20 errors generated.
  error: command '/usr/bin/gcc' failed with exit code 1
  ----------------------------------------
  ERROR: Failed building wheel for shap
ERROR: Could not build wheels for shap, which is required to install pyproject.toml-based projects
```
