### ISSUE TITLE
Python3: shap tree explainer: Exception ignored in: 'array_dealloc'

### ISSUE THREAD

**Issue by hhg7** [shap/shap#1844]
this is a similar post to https://stackoverflow.com/questions/66376784/python3-shap-tree-explainer-exception-ignored-in-array-dealloc but I'm not getting answers there

I'm running xgboost for machine learning, and after successful completion of my machine learning using `XGBClassifier`, I want to make plots of the results.

A minimal working example of my input data in JSON format: 

> [{"age":58,"Deceased":"False","sex":"False"},{"Deceased":"False","age":59,"sex":"False"},{"sex":"False","age":"68","Deceased":"False"},{"Deceased":"False","age":"26","sex":"False"},{"Deceased":"False","age":87,"sex":"False"},{"sex":"True","age":31,"Deceased":"False"},{"Deceased":"False","age":"35","sex":"False"},{"sex":"False","Deceased":"False","age":41},{"age":"78","Deceased":"False","sex":"True"},{"Deceased":"False","age":"45","sex":"True"},{"sex":"False","age":56,"Deceased":"False"},{"sex":"False","Deceased":"False","age":"26"},{"sex":"True","age":"64","Deceased":"False"},{"sex":"False","age":"37","Deceased":"False"},{"age":"86","Deceased":"True","sex":"False"},{"age":76,"Deceased":"True","sex":"True"},{"Deceased":"True","age":69,"sex":"False"},{"Deceased":"True","age":79,"sex":"True"}]

Following advice from https://evgenypogorelov.com/multiclass-xgb-shap.html

my script:

    import mlflow
    import sys
    import json
    import mlflow.sklearn
    import pandas as pd
    import matplotlib.pyplot as plt
    import numpy as np
    from sklearn.model_selection import train_test_split, KFold, cross_val_score
    import xgboost
    import shap
    from sklearn.metrics import accuracy_score, precision_score, plot_roc_curve
    
    def ref_to_json_file(data, filename):
    	json1=json.dumps(data)
    	f = open(filename,"w+")
    	print(json1,file=f)
    
    class xgb_machine_learn: # like a struct in C
      def __init__(self, accuracy, precision_score, feature_importances, results, roc, xg_clf, X, Y):
        self.accuracy = accuracy
        self.precision_score = precision_score
        self.feature_importances = feature_importances
        self.results = results
        self.roc = roc
        self.xg_clf = xg_clf
        self.X = X
        self.Y = Y

    def xgbclassifier_wrapper( json_file, dependent_var, output_stem):
      #https://xgboost.readthedocs.io/en/latest/parameter.html
      pandasDF = pd.read_json(json_file)
      bool_cols = ["Deceased", "sex"]#, 'Hospitalized', 'Respiratory_Support', 'sex']
      for col in bool_cols:
        pandasDF[col] = pandasDF[col]=='True'
      Y = pandasDF[dependent_var]
      X = pandasDF.drop([dependent_var], axis=1)
      
      X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size=0.2)
      mlflow.sklearn.autolog()
    
      # With autolog() enabled, all model parameters, a model score, and the fitted model are automatically logged.  
      with mlflow.start_run():
        # Set the model parameters. 
        n_estimators = 200
        colsample_bytree = 0.3
        learning_rate = 0.05
        max_depth = 6# default 6; max. depth of a tree. Increasing this value will make the model more complex and more likely to overfit. 0 is only accepted in lossguided growing policy when tree_method is set as hist or gpu_hist and it indicates no limit on depth. Beware that XGBoost aggressively consumes memory when training a deep tree.
        #min_child_rate = 0
        gamma = 0 # default = 0; Minimum loss reduction required to make a further partition on a leaf node of the tree. The larger gamma is, the more conservative the algorithm will be.
    
        # Create and train model.
        xg_clf = xgboost.XGBClassifier( n_estimators=n_estimators, colsample_bytree=colsample_bytree, learning_rate=learning_rate, max_depth=max_depth)
        xg_clf.fit(X_train, y_train)
        # Use the model to make predictions on the test dataset.
        predictions = xg_clf.predict(X_test)
      accuracy = accuracy_score(y_test, predictions)
      pre_score  = precision_score(y_test, predictions)
      feature_importances = pd.DataFrame(xg_clf.feature_importances_, index=X.columns, columns=['importance'])
      feature_importances.to_json("data/" + output_stem + '.feature_importances.json')
      kfold = KFold(n_splits=10)
      results = cross_val_score(xg_clf, X, Y, cv=kfold)
      accuracy = results.mean() * 100
      roc = plot_roc_curve(xg_clf, X_test, y_test, name = dependent_var)
      return_object = xgb_machine_learn(accuracy, pre_score, feature_importances, results, roc, xg_clf, X, Y)
      return return_object
 
    json_file = 'debug.json'#"/home/con/covid_study2065/data/pat.data.array.json"
    if not os.path.isfile(json_file):
    	sys.exit("json file doesn't exist.")
    deceased = xgbclassifier_wrapper(json_file, "Deceased", 'debug')
    explainer = shap.TreeExplainer(deceased.xg_clf, model_output = "raw", feature_perturbation="interventional", data = deceased.X)

    explainer = shap.TreeExplainer(deceased.xg_clf, model_output = "probability", feature_perturbation="interventional", data = deceased.X)

gives an error:

    Exception ignored in: 'array_dealloc'
    Traceback (most recent call last):
      File "/usr/local/lib/python3.8/dist-packages/shap/explainers/_tree.py", line 1353, in __init__
        _cext.dense_tree_update_weights(
    SystemError: <class 'DeprecationWarning'> returned a result with an error set
    Found a NULL input array in _cext_dense_tree_update_weights!
    Traceback (most recent call last):
      File "debug.py", line 97, in <module>
        explainer = shap.TreeExplainer(deceased.xg_clf, model_output = "probability", feature_perturbation="interventional", data = deceased.X)
      File "/usr/local/lib/python3.8/dist-packages/shap/explainers/_tree.py", line 147, in __init__
        self.model = TreeEnsemble(model, self.data, self.data_missing, model_output)
      File "/usr/local/lib/python3.8/dist-packages/shap/explainers/_tree.py", line 827, in __init__
        self.trees = xgb_loader.get_trees(data=data, data_missing=data_missing)
      File "/usr/local/lib/python3.8/dist-packages/shap/explainers/_tree.py", line 1522, in get_trees
        trees.append(SingleTree({
      File "/usr/local/lib/python3.8/dist-packages/shap/explainers/_tree.py", line 1353, in __init__
        _cext.dense_tree_update_weights(
    SystemError: <built-in function dense_tree_update_weights> returned NULL without setting an error

I have literally no idea what's causing this error, and this message isn't helpful: I never did anything like `array_alloc`, which I thought was a C-level thing to do.

I'm running Python 3.8.0 on Ubuntu 18.04 on a VM, using `shap 0.38.1`

I tried updating to Python 3.8.8, but that made the situation even worse, because one of the dependencies of `shap` isn't compatible with that version:

    Collecting slicer==0.0.7 (from shap)
      Could not find a version that satisfies the requirement slicer==0.0.7 (from shap) (from versions: )
    No matching distribution found for slicer==0.0.7 (from shap)

How can I run the `shap` library?

**Comment by BaibhavKundu2005** [comment]
@connortann I created a PR #4621 addressing this issue which was marked as todo by you. Kindly review it whenever you have some spare time. Willing to make changes if needed.
