### ISSUE TITLE
ImportError: numpy.core.multiarray failed to import 

### ISSUE THREAD

**Issue by ranjithkommula-20** [shap/shap#1895]
This issue is happening inside the docker container. 

Dockerfile content:

FROM continuumio/miniconda3:4.8.2
WORKDIR /app
COPY requirements.txt /app/
COPY lib/ /app/lib/
RUN pip install -r requirements.txt
COPY . /app/
ENTRYPOINT ["python", "-m", "api"]

requirements.txt is having dependencies pinned:

numpy==1.17.3
shap==0.36.0

Exception from shap.

C extension was not built during install!
Traceback (most recent call last):
  File "/opt/conda/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/opt/conda/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/app/dd/__main__.py", line 136, in <module>
    main()
  File "/opt/conda/lib/python3.7/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/opt/conda/lib/python3.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/opt/conda/lib/python3.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/conda/lib/python3.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/app/dd/__main__.py", line 121, in main
    run_training_and_eval_pipeline(data_layer, NODES)
  File "/opt/conda/lib/python3.7/site-packages/ai_factory/pipeline/pipeline.py", line 27, in run_training_and_eval_pipeline
    offline_training_pipeline_dag.run()
  File "/opt/conda/lib/python3.7/site-packages/ai_factory/dag/dag.py", line 49, in run
    func_returns = [node() for node in self.nodes]
  File "/opt/conda/lib/python3.7/site-packages/ai_factory/dag/dag.py", line 49, in <listcomp>
    func_returns = [node() for node in self.nodes]
  File "/opt/conda/lib/python3.7/site-packages/ai_factory/functional_pipeline_utils/wrappers.py", line 65, in _in
    data = fn(*args, **kwargs)
  File "/opt/conda/lib/python3.7/site-packages/ai_factory/functional_pipeline_utils/wrappers.py", line 99, in _in
    data = fn(*args, **kwargs)
  File "/opt/conda/lib/python3.7/site-packages/ai_factory/functional_pipeline_utils/wrappers.py", line 116, in _in
    data = fn(*data_args)
  File "/app/dd/nodes/modelling/model_generation.py", line 157, in generate_model
    model=final_model, data=all_scf_training_data, features_list=feature_names, path_to_model=path_to_root_folder
  File "/app/dd/nodes/modelling/model_explanation.py", line 53, in explain_model
    model, data=data[features_list], model_output="probability", feature_perturbation="interventional"
  File "/opt/conda/lib/python3.7/site-packages/shap/explainers/_tree.py", line 136, in __init__
    self.model = TreeEnsemble(model, self.data, self.data_missing, model_output)
  File "/opt/conda/lib/python3.7/site-packages/shap/explainers/_tree.py", line 650, in __init__
    self.trees = [SingleTree(e.tree_, normalize=True, scaling=scaling, data=data, data_missing=data_missing) for e in model.estimators_]
  File "/opt/conda/lib/python3.7/site-packages/shap/explainers/_tree.py", line 650, in <listcomp>
    self.trees = [SingleTree(e.tree_, normalize=True, scaling=scaling, data=data, data_missing=data_missing) for e in model.estimators_]
  File "/opt/conda/lib/python3.7/site-packages/shap/explainers/_tree.py", line 1096, in __init__
    assert_import("cext")
  File "/opt/conda/lib/python3.7/site-packages/shap/utils/_general.py", line 23, in assert_import
    raise e
  File "/opt/conda/lib/python3.7/site-packages/shap/explainers/_tree.py", line 22, in <module>
    from .. import _cext
ImportError: numpy.core.multiarray failed to import

**Comment by Benjamin15** [comment]
I get exactly the same issue with docker container. However, it works fine on my current env.
numpy: 1.18.1
shap: 0.35.0, 0.37.0, 0.39.0

The only way to make it works for me is to install shap before make pip install.
```
pip install shap==<version>
pip install -r requirements.txt
```

However, I would like find a better fix.

Does someone has any input on how to solve this issue ?

**Comment by ferraioc** [comment]
Had this same issue, seems to be a dependency version issue. I was originally working in a virtualenv that I had built with numpy and shap both pinned in my requirements file, which worked fine. But when I tried to build in a docker container in circleci I hit this error.
My solution was to simply remove numpy from the requirements file, leaving the shap install responsible for pulling in the appropriate version of numpy.

**Comment by brandon-leapyear** [comment]
:sparkles: _**This is an old work account. Please reference @brandonchinn178 for all future communication**_ :sparkles:


---

So after debugging, it seems like the issue is how shap is deployed to PyPI.

First, some data points:
1. Python 3.6 works with numpy 1.19 and shap 0.39
2. Python 3.9 fails with numpy 1.19 and shap 0.39
3. Python 3.9 works with numpy 1.20 and shap 0.39
4. Python 3.9 works with numpy 1.19 and shap 0.38

It seems like shap 0.39 is deployed as both a tar archive and a wheel. The wheel file seems to have been built against numpy 1.20. Meaning that the C code in shap 0.39 is compiled against numpy 1.20. So when installing the wheel file for shap 0.39 (pre-built with numpy 1.20) in an environment with numpy 1.19, we get a version mismatch at runtime for scenario 2.

It seems like in my local Python 3.6 environment, for some reason, pip is downloading shap 0.39 as a tar archive (not the wheel), so it builds shap against the version of numpy i have locally (1.19), which is why the version mismatch doesn't happen in scenario 1.

Scenario 3 works because the wheel version of shap is compiled against the same version of numpy we're installing.

Scenario 4 works because for some reason, my local Python 3.9 environment downloads the tar archive for shap 0.38 instead of the wheel file, so it builds shap against the same version of numpy we have locally.

To reduce confusion, I'd recommend not deploying the wheel file to PyPI and always have it installed as a tar archive. That way, someone running `pip install shap` will always compile shap against the same version of numpy the user has.

**Comment by banbiossa** [comment]
Taking hints from the discussion, I tried `pip install --no-binary=shap 'shap==0.39.0' --force-reinstall` after everything, and it worked on CircleCI.

**Comment by kbattocchi** [comment]
I believe this would be addressed by #1802

**Comment by brandon-leapyear** [comment]
:sparkles: _**This is an old work account. Please reference @brandonchinn178 for all future communication**_ :sparkles:


---

> 3. Python 3.9 works with numpy 1.20 and shap 0.39

For some reason, this is now failing. I see in my logs that it's installing:
* `shap-0.39.0-cp39-cp39-linux_x86_64.whl`
* `numpy-1.20.3-cp39-cp39-manylinux_2_12_x86_64.manylinux2010_x86_64.whl`

This started failing on December 31; numpy 1.22 was released on that day... coincidence?

Looking at https://pypi.org/simple/shap/, it seems like that `shap` wheel for 0.39.0 on Python 3.9 no longer exists. Was it deleted?

Update: it seems like `pip` initially does install the `.tar.gz` file, then builds a wheel and stores it in `~/.cache/pip/`, so when I SSH into the CI job and reinstall `shap`, it uses that wheel file. So that solves why I'm seeing a wheel file for shap 0.39.0 when it's not on PyPI.

> Taking hints from the discussion, I tried `pip install --no-binary=shap 'shap==0.39.0' --force-reinstall` after everything, and it worked on CircleCI.

Fixed this by adding `--no-binary=-shap` to `tox.ini`

**Comment by detrin** [comment]
Is this issue relevant even with the newest version of shap?
