### ISSUE TITLE
GPUTreeExplainer raises import error on AWS Deep Learning AMI 44

### ISSUE THREAD

**Issue by dipanjank** [shap/shap#1968]
Installing shap on AWS Deep Learning AMI 44.0 (g3s instance) either from source or by "pip install shap" produces the following error

```python
>>> import shap
>>> X, y = shap.datasets.boston()
>>> from sklearn.ensemble import IsolationForest
>>> model = IsolationForest(n_estimators=1000)
>>> model.fit(X);explainer = shap.GPUTreeExplainer(model);shap_values = explainer.shap_values(X)
IsolationForest(n_estimators=1000)
C extension was not built during install!
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/ec2-user/shap/shap/explainers/_tree.py", line 147, in __init__
    self.model = TreeEnsemble(model, self.data, self.data_missing, model_output)
  File "/home/ec2-user/shap/shap/explainers/_tree.py", line 637, in __init__
    self.trees = [IsoTree(e.tree_, f, scaling=scaling, data=data, data_missing=data_missing) for e, f in zip(model.estimators_, model.estimators_features_)]
  File "/home/ec2-user/shap/shap/explainers/_tree.py", line 637, in <listcomp>
    self.trees = [IsoTree(e.tree_, f, scaling=scaling, data=data, data_missing=data_missing) for e, f in zip(model.estimators_, model.estimators_features_)]
  File "/home/ec2-user/shap/shap/explainers/_tree.py", line 1369, in __init__
    super(IsoTree, self).__init__(tree, normalize, scaling, data, data_missing)
  File "/home/ec2-user/shap/shap/explainers/_tree.py", line 1125, in __init__
    assert_import("cext")
  File "/home/ec2-user/shap/shap/utils/_general.py", line 23, in assert_import
    raise e
  File "/home/ec2-user/shap/shap/explainers/_tree.py", line 23, in <module>
    from .. import _cext
ImportError: cannot import name '_cext' from 'shap' (/home/ec2-user/shap/shap/__init__.py)
>>>
```

**Comment by dipanjank** [comment]
output of `python setup.py build`:

```
(pytorch_latest_p37) [ec2-user@ip-172-31-27-138 shap]$ python3 setup.py build
NVCC ==>  /usr/local/cuda-11.1/bin/nvcc
Compiling cuda extension, calling nvcc with arguments:
['/usr/local/cuda-11.1/bin/nvcc', 'shap/cext/_cext_gpu.cu', '-lib', '-o', 'build/lib_cext_gpu.a', '-Xcompiler', '-fPIC', '-I/home/ec2-user/anaconda3/envs/pytorch_latest_p37/include/python3.7m', '--std', 'c++14', '--expt-extended-lambda', '--expt-relaxed-constexpr', '-arch=sm_60', '-gencode=arch=compute_70,code=sm_70', '-gencode=arch=compute_75,code=sm_75', '-gencode=arch=compute_75,code=compute_75']
running build
running build_py
creating build/lib.linux-x86_64-3.7
creating build/lib.linux-x86_64-3.7/shap
copying shap/__init__.py -> build/lib.linux-x86_64-3.7/shap
copying shap/_explanation.py -> build/lib.linux-x86_64-3.7/shap
copying shap/_serializable.py -> build/lib.linux-x86_64-3.7/shap
copying shap/datasets.py -> build/lib.linux-x86_64-3.7/shap
copying shap/links.py -> build/lib.linux-x86_64-3.7/shap
creating build/lib.linux-x86_64-3.7/shap/explainers
copying shap/explainers/__init__.py -> build/lib.linux-x86_64-3.7/shap/explainers
copying shap/explainers/_additive.py -> build/lib.linux-x86_64-3.7/shap/explainers
copying shap/explainers/_exact.py -> build/lib.linux-x86_64-3.7/shap/explainers
copying shap/explainers/_explainer.py -> build/lib.linux-x86_64-3.7/shap/explainers
copying shap/explainers/_gpu_tree.py -> build/lib.linux-x86_64-3.7/shap/explainers
copying shap/explainers/_gradient.py -> build/lib.linux-x86_64-3.7/shap/explainers
copying shap/explainers/_kernel.py -> build/lib.linux-x86_64-3.7/shap/explainers
copying shap/explainers/_linear.py -> build/lib.linux-x86_64-3.7/shap/explainers
copying shap/explainers/_partition.py -> build/lib.linux-x86_64-3.7/shap/explainers
copying shap/explainers/_permutation.py -> build/lib.linux-x86_64-3.7/shap/explainers
copying shap/explainers/_sampling.py -> build/lib.linux-x86_64-3.7/shap/explainers
copying shap/explainers/_tree.py -> build/lib.linux-x86_64-3.7/shap/explainers
copying shap/explainers/mimic.py -> build/lib.linux-x86_64-3.7/shap/explainers
copying shap/explainers/pytree.py -> build/lib.linux-x86_64-3.7/shap/explainers
copying shap/explainers/tf_utils.py -> build/lib.linux-x86_64-3.7/shap/explainers
creating build/lib.linux-x86_64-3.7/shap/explainers/other
copying shap/explainers/other/__init__.py -> build/lib.linux-x86_64-3.7/shap/explainers/other
copying shap/explainers/other/_coefficent.py -> build/lib.linux-x86_64-3.7/shap/explainers/other
copying shap/explainers/other/_lime.py -> build/lib.linux-x86_64-3.7/shap/explainers/other
copying shap/explainers/other/_maple.py -> build/lib.linux-x86_64-3.7/shap/explainers/other
copying shap/explainers/other/_random.py -> build/lib.linux-x86_64-3.7/shap/explainers/other
copying shap/explainers/other/_treegain.py -> build/lib.linux-x86_64-3.7/shap/explainers/other
creating build/lib.linux-x86_64-3.7/shap/explainers/_deep
copying shap/explainers/_deep/__init__.py -> build/lib.linux-x86_64-3.7/shap/explainers/_deep
copying shap/explainers/_deep/deep_pytorch.py -> build/lib.linux-x86_64-3.7/shap/explainers/_deep
copying shap/explainers/_deep/deep_tf.py -> build/lib.linux-x86_64-3.7/shap/explainers/_deep
creating build/lib.linux-x86_64-3.7/shap/plots
copying shap/plots/__init__.py -> build/lib.linux-x86_64-3.7/shap/plots
copying shap/plots/_bar.py -> build/lib.linux-x86_64-3.7/shap/plots
copying shap/plots/_beeswarm.py -> build/lib.linux-x86_64-3.7/shap/plots
copying shap/plots/_decision.py -> build/lib.linux-x86_64-3.7/shap/plots
copying shap/plots/_embedding.py -> build/lib.linux-x86_64-3.7/shap/plots
copying shap/plots/_force.py -> build/lib.linux-x86_64-3.7/shap/plots
copying shap/plots/_force_matplotlib.py -> build/lib.linux-x86_64-3.7/shap/plots
copying shap/plots/_group_difference.py -> build/lib.linux-x86_64-3.7/shap/plots
copying shap/plots/_heatmap.py -> build/lib.linux-x86_64-3.7/shap/plots
copying shap/plots/_image.py -> build/lib.linux-x86_64-3.7/shap/plots
copying shap/plots/_labels.py -> build/lib.linux-x86_64-3.7/shap/plots
copying shap/plots/_monitoring.py -> build/lib.linux-x86_64-3.7/shap/plots
copying shap/plots/_partial_dependence.py -> build/lib.linux-x86_64-3.7/shap/plots
copying shap/plots/_scatter.py -> build/lib.linux-x86_64-3.7/shap/plots
copying shap/plots/_text.py -> build/lib.linux-x86_64-3.7/shap/plots
copying shap/plots/_utils.py -> build/lib.linux-x86_64-3.7/shap/plots
copying shap/plots/_violin.py -> build/lib.linux-x86_64-3.7/shap/plots
copying shap/plots/_waterfall.py -> build/lib.linux-x86_64-3.7/shap/plots
creating build/lib.linux-x86_64-3.7/shap/plots/colors
copying shap/plots/colors/__init__.py -> build/lib.linux-x86_64-3.7/shap/plots/colors
copying shap/plots/colors/_colorconv.py -> build/lib.linux-x86_64-3.7/shap/plots/colors
copying shap/plots/colors/_colors.py -> build/lib.linux-x86_64-3.7/shap/plots/colors
creating build/lib.linux-x86_64-3.7/shap/benchmark
copying shap/benchmark/__init__.py -> build/lib.linux-x86_64-3.7/shap/benchmark
copying shap/benchmark/experiments.py -> build/lib.linux-x86_64-3.7/shap/benchmark
copying shap/benchmark/framework.py -> build/lib.linux-x86_64-3.7/shap/benchmark
copying shap/benchmark/measures.py -> build/lib.linux-x86_64-3.7/shap/benchmark
copying shap/benchmark/methods.py -> build/lib.linux-x86_64-3.7/shap/benchmark
copying shap/benchmark/metrics.py -> build/lib.linux-x86_64-3.7/shap/benchmark
copying shap/benchmark/models.py -> build/lib.linux-x86_64-3.7/shap/benchmark
copying shap/benchmark/perturbation.py -> build/lib.linux-x86_64-3.7/shap/benchmark
copying shap/benchmark/plots.py -> build/lib.linux-x86_64-3.7/shap/benchmark
creating build/lib.linux-x86_64-3.7/shap/maskers
copying shap/maskers/__init__.py -> build/lib.linux-x86_64-3.7/shap/maskers
copying shap/maskers/_composite.py -> build/lib.linux-x86_64-3.7/shap/maskers
copying shap/maskers/_fixed.py -> build/lib.linux-x86_64-3.7/shap/maskers
copying shap/maskers/_fixed_composite.py -> build/lib.linux-x86_64-3.7/shap/maskers
copying shap/maskers/_image.py -> build/lib.linux-x86_64-3.7/shap/maskers
copying shap/maskers/_masker.py -> build/lib.linux-x86_64-3.7/shap/maskers
copying shap/maskers/_output_composite.py -> build/lib.linux-x86_64-3.7/shap/maskers
copying shap/maskers/_tabular.py -> build/lib.linux-x86_64-3.7/shap/maskers
copying shap/maskers/_text.py -> build/lib.linux-x86_64-3.7/shap/maskers
creating build/lib.linux-x86_64-3.7/shap/utils
copying shap/utils/__init__.py -> build/lib.linux-x86_64-3.7/shap/utils
copying shap/utils/_clustering.py -> build/lib.linux-x86_64-3.7/shap/utils
copying shap/utils/_general.py -> build/lib.linux-x86_64-3.7/shap/utils
copying shap/utils/_keras.py -> build/lib.linux-x86_64-3.7/shap/utils
copying shap/utils/_legacy.py -> build/lib.linux-x86_64-3.7/shap/utils
copying shap/utils/_masked_model.py -> build/lib.linux-x86_64-3.7/shap/utils
copying shap/utils/_show_progress.py -> build/lib.linux-x86_64-3.7/shap/utils
copying shap/utils/image.py -> build/lib.linux-x86_64-3.7/shap/utils
copying shap/utils/transformers.py -> build/lib.linux-x86_64-3.7/shap/utils
creating build/lib.linux-x86_64-3.7/shap/actions
copying shap/actions/__init__.py -> build/lib.linux-x86_64-3.7/shap/actions
copying shap/actions/_action.py -> build/lib.linux-x86_64-3.7/shap/actions
copying shap/actions/_optimizer.py -> build/lib.linux-x86_64-3.7/shap/actions
creating build/lib.linux-x86_64-3.7/shap/models
copying shap/models/__init__.py -> build/lib.linux-x86_64-3.7/shap/models
copying shap/models/_model.py -> build/lib.linux-x86_64-3.7/shap/models
copying shap/models/_teacher_forcing.py -> build/lib.linux-x86_64-3.7/shap/models
copying shap/models/_text_generation.py -> build/lib.linux-x86_64-3.7/shap/models
copying shap/models/_topk_lm.py -> build/lib.linux-x86_64-3.7/shap/models
copying shap/models/_transformers_pipeline.py -> build/lib.linux-x86_64-3.7/shap/models
creating build/lib.linux-x86_64-3.7/shap/plots/resources
copying shap/plots/resources/bundle.js -> build/lib.linux-x86_64-3.7/shap/plots/resources
copying shap/plots/resources/logoSmallGray.png -> build/lib.linux-x86_64-3.7/shap/plots/resources
creating build/lib.linux-x86_64-3.7/shap/cext
copying shap/cext/tree_shap.h -> build/lib.linux-x86_64-3.7/shap/cext
running build_ext
numpy.get_include() /home/ec2-user/anaconda3/envs/pytorch_latest_p37/lib/python3.7/site-packages/numpy/core/include
building 'shap._cext' extension
creating build/temp.linux-x86_64-3.7
creating build/temp.linux-x86_64-3.7/shap
creating build/temp.linux-x86_64-3.7/shap/cext
/home/ec2-user/anaconda3/envs/pytorch_latest_p37/bin/x86_64-conda-linux-gnu-cc -Wno-unused-result -Wsign-compare -DNDEBUG -fwrapv -O2 -Wall -Wstrict-prototypes -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -pipe -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -pipe -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -ffunction-sections -pipe -isystem /home/ec2-user/anaconda3/envs/pytorch_latest_p37/include -DNDEBUG -D_FORTIFY_SOURCE=2 -O2 -isystem /home/ec2-user/anaconda3/envs/pytorch_latest_p37/include -fPIC -I/home/ec2-user/anaconda3/envs/pytorch_latest_p37/include/python3.7m -I/home/ec2-user/anaconda3/envs/pytorch_latest_p37/lib/python3.7/site-packages/numpy/core/include -c shap/cext/_cext.cc -o build/temp.linux-x86_64-3.7/shap/cext/_cext.o
cc1plus: warning: command line option '-Wstrict-prototypes' is valid for C/ObjC but not for C++
In file included from shap/cext/_cext.cc:5:0:
shap/cext/tree_shap.h: In function 'void dense_tree_interactions_path_dependent(const TreeEnsemble&, const ExplanationDataset&, tfloat*, tfloat (*)(tfloat, tfloat))':
shap/cext/tree_shap.h:1321:36: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
             for (unsigned l = 0; l < amount_of_unique_features; ++l) {
                                  ~~^~~~~~~~~~~~~~~~~~~~~~~~~~~
shap/cext/tree_shap.h:1351:36: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
             for (unsigned k = 0; k < amount_of_unique_features; ++k) {
                                  ~~^~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/ec2-user/anaconda3/envs/pytorch_latest_p37/bin/x86_64-conda-linux-gnu-c++ -pthread -shared -Wl,-O2 -Wl,--sort-common -Wl,--as-needed -Wl,-z,relro -Wl,-z,now -Wl,-rpath,/home/ec2-user/anaconda3/envs/pytorch_latest_p37/lib -L/home/ec2-user/anaconda3/envs/pytorch_latest_p37/lib -Wl,-O2 -Wl,--sort-common -Wl,--as-needed -Wl,-z,relro -Wl,-z,now -Wl,-rpath,/home/ec2-user/anaconda3/envs/pytorch_latest_p37/lib -L/home/ec2-user/anaconda3/envs/pytorch_latest_p37/lib -Wl,-O2 -Wl,--sort-common -Wl,--as-needed -Wl,-z,relro -Wl,-z,now -Wl,--disable-new-dtags -Wl,--gc-sections -Wl,-rpath,/home/ec2-user/anaconda3/envs/pytorch_latest_p37/lib -Wl,-rpath-link,/home/ec2-user/anaconda3/envs/pytorch_latest_p37/lib -L/home/ec2-user/anaconda3/envs/pytorch_latest_p37/lib -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -ffunction-sections -pipe -isystem /home/ec2-user/anaconda3/envs/pytorch_latest_p37/include -DNDEBUG -D_FORTIFY_SOURCE=2 -O2 -isystem /home/ec2-user/anaconda3/envs/pytorch_latest_p37/include build/temp.linux-x86_64-3.7/shap/cext/_cext.o -o build/lib.linux-x86_64-3.7/shap/_cext.cpython-37m-x86_64-linux-gnu.so
building 'shap._cext_gpu' extension
/home/ec2-user/anaconda3/envs/pytorch_latest_p37/bin/x86_64-conda-linux-gnu-cc -Wno-unused-result -Wsign-compare -DNDEBUG -fwrapv -O2 -Wall -Wstrict-prototypes -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -pipe -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -pipe -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -ffunction-sections -pipe -isystem /home/ec2-user/anaconda3/envs/pytorch_latest_p37/include -DNDEBUG -D_FORTIFY_SOURCE=2 -O2 -isystem /home/ec2-user/anaconda3/envs/pytorch_latest_p37/include -fPIC -I/home/ec2-user/anaconda3/envs/pytorch_latest_p37/include/python3.7m -I/home/ec2-user/anaconda3/envs/pytorch_latest_p37/lib/python3.7/site-packages/numpy/core/include -c shap/cext/_cext_gpu.cc -o build/temp.linux-x86_64-3.7/shap/cext/_cext_gpu.o -fPIC
cc1plus: warning: command line option '-Wstrict-prototypes' is valid for C/ObjC but not for C++
In file included from shap/cext/_cext_gpu.cc:5:0:
shap/cext/tree_shap.h: In function 'void dense_tree_interactions_path_dependent(const TreeEnsemble&, const ExplanationDataset&, tfloat*, tfloat (*)(tfloat, tfloat))':
shap/cext/tree_shap.h:1321:36: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
             for (unsigned l = 0; l < amount_of_unique_features; ++l) {
                                  ~~^~~~~~~~~~~~~~~~~~~~~~~~~~~
shap/cext/tree_shap.h:1351:36: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
             for (unsigned k = 0; k < amount_of_unique_features; ++k) {
                                  ~~^~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/ec2-user/anaconda3/envs/pytorch_latest_p37/bin/x86_64-conda-linux-gnu-c++ -pthread -shared -Wl,-O2 -Wl,--sort-common -Wl,--as-needed -Wl,-z,relro -Wl,-z,now -Wl,-rpath,/home/ec2-user/anaconda3/envs/pytorch_latest_p37/lib -L/home/ec2-user/anaconda3/envs/pytorch_latest_p37/lib -Wl,-O2 -Wl,--sort-common -Wl,--as-needed -Wl,-z,relro -Wl,-z,now -Wl,-rpath,/home/ec2-user/anaconda3/envs/pytorch_latest_p37/lib -L/home/ec2-user/anaconda3/envs/pytorch_latest_p37/lib -Wl,-O2 -Wl,--sort-common -Wl,--as-needed -Wl,-z,relro -Wl,-z,now -Wl,--disable-new-dtags -Wl,--gc-sections -Wl,-rpath,/home/ec2-user/anaconda3/envs/pytorch_latest_p37/lib -Wl,-rpath-link,/home/ec2-user/anaconda3/envs/pytorch_latest_p37/lib -L/home/ec2-user/anaconda3/envs/pytorch_latest_p37/lib -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -ffunction-sections -pipe -isystem /home/ec2-user/anaconda3/envs/pytorch_latest_p37/include -DNDEBUG -D_FORTIFY_SOURCE=2 -O2 -isystem /home/ec2-user/anaconda3/envs/pytorch_latest_p37/include build/temp.linux-x86_64-3.7/shap/cext/_cext_gpu.o -Lbuild -L/usr/local/cuda-11.1/lib64 -l_cext_gpu -lcudart -o build/lib.linux-x86_64-3.7/shap/_cext_gpu.cpython-37m-x86_64-linux-gnu.so



```

**Comment by ajalberd** [comment]
I have the same issue - only with GPUTree. The build seems fine just like yours. Any solution?

**Comment by ajalberd** [comment]
I solved it by doing 'pip uninstall shap' twice, downloading a fresh tar release from this github, and then making sure I had gcc and g++ that matched the CUDA version I had (in my case - 10.1 - 8.5.0)
