### ISSUE TITLE
Additivity check failed in TreeExplainer!

### ISSUE THREAD

**Issue by tjsanti** [shap/shap#1986]
I'm using shap version 0.39.0 in python 3.8.2 and getting this error when trying to do a simple classification task. As far as I can tell, it does not happen with other regression tasks that I have tried. Regardless, here is the code to reproduce this:
```
import shap
import numpy as np
import pandas as pd
from sklearn.datasets import load_iris
from sklearn.ensemble import RandomForestClassifier


def shap_importance(model, X_train, y_train):
    model.fit(X_train, y_train)
    ex = shap.Explainer(model, X_train)
    shap_values = np.array(ex.shap_values(X_train))
    if len(shap_values.shape) > 2:
        avg_shaps = np.abs(shap_values).sum(axis=0).mean(axis=0)
    else:
        avg_shaps = np.abs(shap_values).mean(axis=0)
    imps = pd.Series(data=avg_shaps, index=X_train.columns)

    return imps.sort_values(ascending=False)


iris = load_iris(as_frame=True)
X = iris.data
y = iris.target

model = RandomForestClassifier()
print(shap_importance(model, X, y))
```
And here is the traceback:
```
Traceback (most recent call last):
  File "issue.py", line 26, in <module>
    print(shap_importance(model, X, y))
  File "issue.py", line 11, in shap_importance
    shap_values = np.array(ex.shap_values(X_train))
  File "/opt/anaconda3/lib/python3.8/site-packages/shap/explainers/_tree.py", line 406, in shap_values
    self.assert_additivity(out, self.model.predict(X))
  File "/opt/anaconda3/lib/python3.8/site-packages/shap/explainers/_tree.py", line 537, in assert_additivity
    check_sum(self.expected_value[i] + phi[i].sum(-1), model_output[:,i])
  File "/opt/anaconda3/lib/python3.8/site-packages/shap/explainers/_tree.py", line 533, in check_sum
    raise Exception(err_msg)
Exception: Additivity check failed in TreeExplainer! Please ensure the data matrix you passed to the explainer is the same shape that the model was trained on. If your data shape is correct then please report this on GitHub. This check failed because for one of the samples the sum of the SHAP values was 0.000100, while the model output was 0.010000. If this difference is acceptable you can set check_additivity=False to disable this check.
```
Additionally, when I try to set `check_additivity=False` inside `shap_values` I get: `shap_values() got an unexpected keyword argument 'check_additivity'`

**Comment by xxjoeseven** [comment]
I'm adding one more example. I'm using the same data shape. 

python=3.9.12
scikit-learn=1.0.2
shap = 0.40.0

random_forest_clf = RandomForestClassifier(max_depth=15, n_estimators=300, random_state=77)
random_forest_clf.fit(X_train, y_train)

explainer = shap.TreeExplainer(random_forest_clf, X_train)
shap_values = explainer.shap_values(X_train)
shap.summary_plot(shap_values, X_train, feature_names=feature_names)

#### Error screen cap
![additivity_check_failed](https://user-images.githubusercontent.com/71744941/166215944-2f04f5bf-0c03-45e9-a514-bf524aaec7ae.JPG)

**Comment by hunaidkhan2000** [comment]
I am facing the same issue with random forest model , when i add check_additivity=False , it Kills the kernel everytime. Does any one have any solution?

**Comment by thatlittleboy** [comment]
@tjsanti Try only providing the trained model instance to `Explainer`.

```python
ex = shap.Explainer(model)  # <--- instead of shap.Explainer(model, X_train)
shap_values = ex.shap_values(X_train)
```

@xxjoeseven Same advice.

```python
explainer = shap.TreeExplainer(random_forest_clf)  # <--- instead of shap.TreeExplainer(random_forest_clf, X_train)
shap_values = explainer.shap_values(X_train)
```

I don't get any errors with additivity in this case. If anyone else still faces this issue after adjusting the call to the Explainer class, please provide a minimal working example (like @tjsanti or @xxjoeseven  did).
