### ISSUE TITLE
Catboost error with GPUTree Explainer

### ISSUE THREAD

**Issue by ThomasWolf0701** [shap/shap#2007]
Tried to run the GPU tree explainer wirh catboost and got the following error:

explainer = shap.GPUTreeExplainer(bestModel["m"], model_output='raw', feature_perturbation="tree_path_dependent" ) 

bestModelShap = explainer.shap_values( transformedMatrix)
Traceback (most recent call last):

  File "<ipython-input-193-63b3ab6cba7b>", line 1, in <module>
    bestModelShap = explainer.shap_values( transformedMatrix)

  File "C:\Users\Thomas Wolf\anaconda3\envs\ChemPipeline\lib\site-packages\shap\explainers\_gpu_tree.py", line 99, in shap_values
    self._validate_inputs(X, y,

  File "C:\Users\Thomas Wolf\anaconda3\envs\ChemPipeline\lib\site-packages\shap\explainers\_tree.py", line 235, in _validate_inputs
    tree_limit = self.model.values.shape[0]

AttributeError: 'TreeEnsemble' object has no attribute 'values'

**Comment by Liushaoqin** [comment]
Seems  gpuTreeExplainer was integrated by XG-boost

**Comment by iwm911** [comment]
Same error here :(
