### ISSUE TITLE
How to save explainer object

### ISSUE THREAD

**Issue by william-episource** [shap/shap#2118]
I'm trying to save the explainer object and have tried pickling the object as mentioned in this open issue but could not save it: https://github.com/slundberg/shap/issues/295

I then tried the Explainer() and tried to save it with the following but its throwing an error. How can I save the explainer object?
ref docs: https://shap.readthedocs.io/en/latest/generated/shap.Explainer.html

```
explainer = shap.Explainer(new_model.predict, df_no_label)
shap_values = explainer(df_no_label)
explainer.save("/tmp/explainer.sav")   <= ERROR HERE

---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-46-8550ae06d022> in <module>
----> 1 explainer.save("/tmp/explainer.sav", model_saver='.save', masker_saver='.save')

~/.local/lib/python3.7/site-packages/shap/explainers/_explainer.py in save(self, out_file, model_saver, masker_saver)
    394         """ Write the explainer to the given file stream.
    395         """
--> 396         super().save(out_file)
    397         with Serializer(out_file, "shap.Explainer", version=0) as s:
    398             s.save("model", self.model, model_saver)

~/.local/lib/python3.7/site-packages/shap/_serializable.py in save(self, out_file)
     16         """ Save the model to the given file stream.
     17         """
---> 18         pickle.dump(type(self), out_file)
     19 
     20     @classmethod

TypeError: file must have a 'write' attribute
```

**Comment by jack89roberts** [comment]
I think you need to give a file stream rather than a string, e.g.
```python
with open("/tmp/explainer.sav", "wb") as f:
     explainer.save(f)
```

**Comment by william-episource** [comment]
Unfortunately I get a different error when trying to save with the suggested code:

```
explainer = shap.Explainer(new_model.predict, df_no_label)
shap_values = explainer(df_no_label)
with open("/tmp/explainer.sav", "wb") as f:
     explainer.save(f)
     
-----------------------------------------------------------
File ".../pickle.py", line 504, in save
    f(self, obj) # Call unbound method with explicit self
  File ".../pickle.py", line 859, in save_dict
    self._batch_setitems(obj.items())
  File ".../pickle.py", line 884, in _batch_setitems
    save(k)
  File ".../pickle.py", line 524, in save
    rv = reduce(self.proto)
TypeError: can't pickle weakref objects
```

**Comment by jack89roberts** [comment]
Ah, probably one step further at least! I'm new to SHAP and also struggling with a save problem (but something else #2122).

**Comment by JackWillz** [comment]
@william-episource did you solve this? I'm having the exact same issue.

**Comment by william-episource** [comment]
@JackWillz no I didn't, this issue is still unresolved

**Comment by JackWillz** [comment]
@william-episource I've managed to save & reload with a simple pickle dump, if that helps

**Comment by william-episource** [comment]
@JackWillz are you using Tensorflow by any chance? I tested pickling with a XGBClassifier model + TreeExplainer and was able to save the explainer object and reload it. Unfortunately does not appear to be solution when working with Tensorflow/Keras model

**Comment by JackWillz** [comment]
@william-episource Ah, no sorry - I'm using XGBClassifier model, I haven't tried for TF/Keras

**Comment by shivayv24** [comment]
I know this issue still open, as anyone been able to store the deepexplainer object for TF/ keras model ? are there any breakthroughs ?

**Comment by jinyanGuan** [comment]
Have anyone have successfully saved a kernelExplainer? I can use picke and joblib to save the explainer, but after loading it, the returned shap values are different.

**Comment by thatlittleboy** [comment]
@tinaFei Can you provide a minimal working example demonstrating the problem? If we're able to reproduce the problem, it'll increase the likelihood of us fixing it.

**Comment by 9cpluss** [comment]
@thatlittleboy Here is a reproducible example:

Python 3.9.12

```python
import shap
from catboost import CatBoostClassifier

train_data = [[0, 3],
              [4, 1],
              [8, 1],
              [9, 1]]
train_labels = [0, 0, 1, 1]

model = CatBoostClassifier(iterations=1000)
model.fit(train_data, train_labels, verbose=False)

explainer = shap.TreeExplainer(model)
explainer.save("explainer.pkl")
```

That gives
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File ".../.venv/lib/python3.9/site-packages/shap/explainers/_explainer.py", line 415, in save
    super().save(out_file)
  File ".../.venv/lib/python3.9/site-packages/shap/_serializable.py", line 18, in save
    pickle.dump(type(self), out_file)
TypeError: file must have a 'write' attribute
```

The problem is with
https://github.com/shap/shap/blob/ec17a2604127c16b83caaf8e3b4d10eeadaa73ee/shap/_serializable.py#L18

Pickle can't be used like that. That is not a problem specific to the SHAP package. I am not sure what `type(self)` does but usually `pickle.dump` would have to be used in the following way.

```python
with open(out_file, "wb") as f:
    pickle.dump(type(self), f)
```

Using the above reproducible example, the following does work:
```python
with open("explainer.pkl", "wb") as f:
    pickle.dump(explainer, f)
```
---
pip list:
```
Package             Version Editable project location
------------------- ------- ---------------------------------------
catboost            1.2
cloudpickle         2.2.1
contourpy           1.1.0
cycler              0.11.0
fonttools           4.42.0
graphviz            0.20.1
importlib-resources 6.0.1
joblib              1.3.2
kiwisolver          1.4.4
llvmlite            0.39.1
matplotlib          3.7.2
numba               0.56.4
numpy               1.23.5
packaging           23.1
pandas              2.0.3
Pillow              10.0.0
pip                 22.0.4
plotly              5.16.0
pyparsing           3.0.9
python-dateutil     2.8.2
pytz                2023.3
scikit-learn        1.3.0
scipy               1.9.3
setuptools          68.1.0
setuptools-scm      7.1.0
shap                0.42.1
six                 1.16.0
slicer              0.0.7
tenacity            8.2.3
threadpoolctl       3.2.0
tomli               2.0.1
tqdm                4.66.1
typing_extensions   4.7.1
tzdata              2023.3
zipp                3.16.2
```
