### ISSUE TITLE
`TreeExplainer.save` throws `AttributeError: 'TreeEnsemble' object has no attribute 'save'`

### ISSUE THREAD

**Issue by harupy** [shap/shap#2122]
Sorry if I'm missing something, but `TreeExplainer.save` doesn't seem to work:

```python
import shap
import xgboost as xgb
from sklearn.datasets import load_iris

print(xgb.__version__)
print(shap.__version__)

dtrain = xgb.DMatrix(*load_iris(return_X_y=True))
model = xgb.train({}, dtrain)
exp = shap.TreeExplainer(model)

with open("TreeExplainer", "wb") as out_file:
    exp.save(out_file)
```

When I run this code, I get:

```python
1.4.2
0.39.0
Traceback (most recent call last):
  File "a.py", line 13, in <module>
    exp.save(out_file)
  File "/Users/foo/.pyenv/versions/miniconda3-4.7.12/envs/bar/lib/python3.7/site-packages/shap/explainers/_explainer.py", line 398, in save
    s.save("model", self.model, model_saver)
  File "/Users/foo/.pyenv/versions/miniconda3-4.7.12/envs/bar/lib/python3.7/site-packages/shap/_serializable.py", line 87, in save
    if len(inspect.getfullargspec(value.save)[0]) == 3: # backward compat for MLflow, can remove 4/1/2021
AttributeError: 'TreeEnsemble' object has no attribute 'save'
```

**Comment by harupy** [comment]
cc @slundberg

**Comment by johnkuangwork** [comment]
Yeah, I run into the exact same issue...trying pickle but the online hosting "Gradio" won't allow to load it.

**Comment by jack89roberts** [comment]
Same problem here too but with a LightGBM model.

**Comment by jack89roberts** [comment]
Actually this is not specific to `TreeExplainer`, e.g. this gives the same error (shap 0.39.0):

```python
import shap
from sklearn.linear_model import LogisticRegression
from sklearn.datasets import load_breast_cancer

X, y = load_breast_cancer(return_X_y=True)
clf = LogisticRegression().fit(X, y)

exp = shap.LinearExplainer(clf, shap.maskers.Independent(X))
with open("tmp.shap", "wb") as f:
    exp.save(f)
```

The error is coming from `Explainer.save`, which on line 398 passes `self.model` as the `value` argument for `Serializer.save`, and `Serializer.save` expects `value` to have a save method (e.g. on line 88).

**Comment by jack89roberts** [comment]
The `Serializer` class was introduced in shap 0.39.0, I don't have this problem if I use shap 0.38.1 which uses pickle.dump. However, on v0.38.1 I get an error when trying to load the explainer. After the code above:

```python
with open("tmp.shap", "rb") as f:
    load_exp = shap.Explainer.load(f)
```

This gives:
```
~/opt/anaconda3/envs/shap/lib/python3.9/site-packages/shap/explainers/_explainer.py in load(cls, in_file, model_loader, masker_loader)
    366         """
    367         explainer_type = pickle.load(in_file)
--> 368         return explainer_type._load(in_file, model_loader, masker_loader)
    369 
    370 def pack_values(values):

AttributeError: type object 'Linear' has no attribute '_load'
```

**Comment by delestro** [comment]
I'm having the same issue when trying to save an explainer. For my case it's an XGBoost model.

**Saving works** if I set the atributes `model_saver` and `masker_saver` to `"auto"`:

```python
explainer.save(open(model_name, 'wb') , model_saver="auto", masker_saver="auto")
```

I get a file with a about 50 MB, so something is there. But when trying **to load I have an issue**:
`shap.Explainer.load(open(model_name, 'rb'))` gives the following:
```python
Exception: Invalid object type loaded from file. <shap.explainers._tree.TreeEnsemble object at 0x7fd64027e250> is not a subclass of <class 'shap.models._model.Model'>.
```
Trying to use the `TreeEnsemble`, calling it like this:
```python
shap.Explainer.load(open(model_name, 'rb'), 
                    model_loader=shap.explainers._tree.TreeEnsemble)
```

Also gives an error. Here the full traceback:
```python
---------------------------------------------------------------------------
Exception                                 Traceback (most recent call last)
~/anaconda3/envs/xgboost/lib/python3.9/site-packages/shap/explainers/_explainer.py in load(cls, in_file, model_loader, masker_loader, instantiate)
    423         with Deserializer(in_file, "shap.Explainer", min_version=0, max_version=0) as s:
--> 424             kwargs["model"] = s.load("model", model_loader)
    425             kwargs["masker"] = s.load("masker", masker_loader)

~/anaconda3/envs/xgboost/lib/python3.9/site-packages/shap/_serializable.py in load(self, name, decoder)
    182 
--> 183         value = self._load_data_value(decoder)
    184         log.debug("value = %s", str(value))

~/anaconda3/envs/xgboost/lib/python3.9/site-packages/shap/_serializable.py in _load_data_value(self, decoder)
    191             assert callable(decoder), "You must provide a callable custom decoder for the data item {name}!"
--> 192             return decoder(self.in_stream)
    193         if encoder_name == "no_encoder":

~/anaconda3/envs/xgboost/lib/python3.9/site-packages/shap/explainers/_tree.py in __init__(self, model, data, data_missing, model_output)
    978         else:
--> 979             raise Exception("Model type not yet supported by TreeExplainer: " + str(type(model)))
    980 

Exception: Model type not yet supported by TreeExplainer: <class '_io.BufferedReader'>

During handling of the above exception, another exception occurred:

ValueError                                Traceback (most recent call last)
<ipython-input-33-7c0340515057> in <module>
----> 1 shap.Explainer.load(open(model_name, 'rb'), 
      2                     model_loader=shap.explainers._tree.TreeEnsemble)

~/anaconda3/envs/xgboost/lib/python3.9/site-packages/shap/explainers/_explainer.py in load(cls, in_file, model_loader, masker_loader, instantiate)
    418         """
    419         if instantiate:
--> 420             return cls._instantiated_load(in_file, model_loader=model_loader, masker_loader=masker_loader)
    421 
    422         kwargs = super().load(in_file, instantiate=False)

~/anaconda3/envs/xgboost/lib/python3.9/site-packages/shap/_serializable.py in _instantiated_load(cls, in_file, **kwargs)
     43 
     44         # here we call the constructor with all the arguments we have loaded
---> 45         constructor_args = obj_type.load(in_file, instantiate=False, **kwargs)
     46         used_args = inspect.getfullargspec(obj_type.__init__)[0]
     47         return obj_type(**{k: constructor_args[k] for k in constructor_args if k in used_args})

~/anaconda3/envs/xgboost/lib/python3.9/site-packages/shap/explainers/_explainer.py in load(cls, in_file, model_loader, masker_loader, instantiate)
    424             kwargs["model"] = s.load("model", model_loader)
    425             kwargs["masker"] = s.load("masker", masker_loader)
--> 426             kwargs["link"] = s.load("link")
    427         return kwargs
    428 

~/anaconda3/envs/xgboost/lib/python3.9/site-packages/shap/_serializable.py in __exit__(self, exception_type, exception_value, traceback)
    163             if end_token == "END_BLOCK___":
    164                 return
--> 165             self._load_data_value()
    166         raise ValueError(
    167             f"The data block end token wsa not found for the block {self.block_name}."

~/anaconda3/envs/xgboost/lib/python3.9/site-packages/shap/_serializable.py in _load_data_value(self, decoder)
    202             return cloudpickle.load(self.in_stream)
    203 
--> 204         raise ValueError(f"Unsupported encoder type found: {encoder_name}")

ValueError: Unsupported encoder type found: masker
```

Maybe `Exception: Model type not yet supported by TreeExplainer` is the worrying part ? :sweat:

**Comment by haochunchang** [comment]
Encountered the same issue.
Using `shap 0.40.0, xgb 1.5.0`, saving and loading the explainer like:
```python
explainer = shap.Explainer(model, x)
explainer.save(
    open(explainer_path, "wb"),
    model_saver="auto",
    masker_saver="auto")
explainer = shap.Explainer.load(
    open(explainer_path, "rb"),
    model_loader="auto",
    masker_loader="auto"
)
```
And got printed result and the error message:
```python
loaded_name model
loaded_name masker
loaded_name data
loaded_name max_samples
loaded_name clustering
loaded_name link
venv/lib/python3.9/site-packages/shap/explainers/_tree.py", line 979, in __init__
    raise Exception("Model type not yet supported by TreeExplainer: " + str(type(model)))
Exception: Model type not yet supported by TreeExplainer: <class 'shap.explainers._tree.TreeEnsemble'>
```

The default setting: `instantiate=True` will cause `shap.Explainer.load` to call `Serializable._instantiate_load`.
That leads to `shap.explainers._tree.TreeEnsemble` type to pass into the initialization of itself which expect the model to be type of various tree-based models.

I've also tried loading directly using:
```python
explainer = pickle.load(open(explainer_path, "rb"))
print(explainer)
```
And I got `<class 'shap.explainers._tree.Tree'>` which is not an instantiated object.

**Comment by dltemple** [comment]
Has there been any movement on this?
I've tried various combinations of masker loaders but still keep arriving at 

`  File "<ipython-input-7-77f26fcf401a>", line 2, in <module>
    explainer2 = shap.TreeExplainer.load(open(self.fname_shapley_explainer, 'rb'),
  File "/Users/dtemple/Repositories/ai-kato/venv/lib/python3.9/site-packages/shap/explainers/_explainer.py", line 432, in load
    return cls._instantiated_load(in_file, model_loader=model_loader, masker_loader=masker_loader)
  File "/Users/dtemple/Repositories/ai-kato/venv/lib/python3.9/site-packages/shap/_serializable.py", line 45, in _instantiated_load
    constructor_args = obj_type.load(in_file, instantiate=False, **kwargs)
  File "/Users/dtemple/Repositories/ai-kato/venv/lib/python3.9/site-packages/shap/explainers/_explainer.py", line 438, in load
    kwargs["link"] = s.load("link")
  File "/Users/dtemple/Repositories/ai-kato/venv/lib/python3.9/site-packages/shap/_serializable.py", line 165, in __exit__
    self._load_data_value()
  File "/Users/dtemple/Repositories/ai-kato/venv/lib/python3.9/site-packages/shap/_serializable.py", line 204, in _load_data_value
    raise ValueError(f"Unsupported encoder type found: {encoder_name}")
ValueError: Unsupported encoder type found: masker`

**Comment by ndrmahmoudi** [comment]
Hi everyone, 

I was just wondering if this issue has been resolved? I am getting the same error when logging the explainer using mlflow in Databricks. 

I have `shap==0.41.0` and `mlflow==2.1.1`.

Best regards,
Nader

**Comment by adivarma215** [comment]
### Working solution
Hi everyone,

I was facing the same issue. But I was able to work around this using joblib's dump and load methods. 
`with open(save_path + 'object_name', 'wb') as f:
    jbl.dump(explainer, f)

with open(save_path + 'object_name', 'rb') as f:
    loaded_explainer = jbl.load(f)
`
Hope this helps.

Regards,
Aditya

**Comment by fgalloway** [comment]
Recently come across this issue trying to log the explainer object in MLFlow using `shap==0.47.2`, `py-xgboost==2.1.4` and `mlflow==2.22.0`.

There is an attribute error when trying to save the explainer object:
```python
AttributeError: 'TreeEnsemble' object has no attribute 'save'
```

In testing, I found that this [commit](https://github.com/shap/shap/commit/06141f55fadefdac1ee59fdf9e7fec003bbd23b6) has fixed the issue with saving the explainer, but there is now an issue with loading the model:
```python
Traceback (most recent call last):
  File "/home/users/francis.galloway/.conda/envs/shap-bug/lib/python3.12/site-packages/shap/explainers/_explainer.py", line 531, in load
    kwargs["link"] = s.load("link")
                     ^^^^^^^^^^^^^^
  File "/home/users/francis.galloway/.conda/envs/shap-bug/lib/python3.12/site-packages/shap/_serializable.py", line 175, in load
    raise ValueError(
ValueError: The next data item in the file being loaded was supposed to be link, but the next block found was data.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/users/francis.galloway/Projects/shap-bug/shapsave.py", line 18, in <module>
    loaded_explainer = shap.TreeExplainer.load(f)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/users/francis.galloway/.conda/envs/shap-bug/lib/python3.12/site-packages/shap/explainers/_explainer.py", line 522, in load
    return cls._instantiated_load(in_file, model_loader=model_loader, masker_loader=masker_loader)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/users/francis.galloway/.conda/envs/shap-bug/lib/python3.12/site-packages/shap/_serializable.py", line 43, in _instantiated_load
    constructor_args = obj_type.load(in_file, instantiate=False, **kwargs)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/users/francis.galloway/.conda/envs/shap-bug/lib/python3.12/site-packages/shap/explainers/_explainer.py", line 525, in load
    with Deserializer(in_file, "shap.Explainer", min_version=0, max_version=0) as s:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/users/francis.galloway/.conda/envs/shap-bug/lib/python3.12/site-packages/shap/_serializable.py", line 165, in __exit__
    self._load_data_value()
  File "/home/users/francis.galloway/.conda/envs/shap-bug/lib/python3.12/site-packages/shap/_serializable.py", line 201, in _load_data_value
    raise ValueError(f"Unsupported encoder type found: {encoder_name}")
ValueError: Unsupported encoder type found: None
```

The above was generated in an environment with `python==3.12`, `py-xgboost==3.0.4` and `shap==git+ssh://git@github.com/shap/shap.git@d9b10f69baffeb55d9d1b34126bd7e189cae5116`. The following script should reproduce:
```python
import shap
import xgboost
from sklearn.datasets import make_regression
 
X, y = make_regression(n_samples=100, n_features=10, noise=0.1)
 
m = xgboost.XGBRegressor()
m.fit(X, y)
 
explainer = shap.TreeExplainer(m)
explanation = explainer(X[:5])
print(explanation.values)

with open('explainer.shap', 'wb') as f:
    explainer.save(f)
 
with open('explainer.shap', 'rb') as f:
    loaded_explainer = shap.TreeExplainer.load(f)
 
print(loaded_explainer(X[:5]).values)
```

I'm not sure if I've missed something in the use of the `save`/`load` methods of the `shap.Explainer`?

**Comment by CloseChoice** [comment]
### Triage Note

Tested on current master — `TreeExplainer.save()` now works:

```python
import shap, xgboost as xgb, io
from sklearn.datasets import load_iris

dtrain = xgb.DMatrix(*load_iris(return_X_y=True))
model = xgb.train({}, dtrain)
exp = shap.TreeExplainer(model)
exp.save(io.BytesIO())  # succeeds
```

This appears to have been fixed at some point. This issue can likely be closed.

---
<sub>This comment was drafted with LLM assistance and reviewed by @CloseChoice before posting.</sub>
