### ISSUE TITLE
DeepExplainer:  TypeError: Fetch argument None has invalid type <class 'NoneType'>

### ISSUE THREAD

**Issue by aendrs** [shap/shap#2217]
I'm trying to make DeepExplainer work with my keras model (that has custom layers). I got the following error when calculating shap_values.
(Shap  version 0.34.0)

```
shap_values = e.shap_values(x_test[0][0:4])

Traceback (most recent call last):

  File "<ipython-input-76-3f4d7f395630>", line 1, in <module>
    shap_values = e.shap_values(x_test[0][0:1])

  File "C:\Users\andre\.conda\envs\tf_test\lib\site-packages\shap\explainers\deep\__init__.py", line 119, in shap_values
    return self.explainer.shap_values(X, ranked_outputs, output_rank_order)

  File "C:\Users\andre\.conda\envs\tf_test\lib\site-packages\shap\explainers\deep\deep_tf.py", line 272, in shap_values
    sample_phis = self.run(self.phi_symbolic(feature_ind), self.model_inputs, joint_input)

  File "C:\Users\andre\.conda\envs\tf_test\lib\site-packages\shap\explainers\deep\deep_tf.py", line 299, in run
    return self.session.run(out, feed_dict)

  File "C:\Users\andre\.conda\envs\tf_test\lib\site-packages\tensorflow\python\client\session.py", line 929, in run
    run_metadata_ptr)

  File "C:\Users\andre\.conda\envs\tf_test\lib\site-packages\tensorflow\python\client\session.py", line 1137, in _run
    self._graph, fetches, feed_dict_tensor, feed_handles=feed_handles)

  File "C:\Users\andre\.conda\envs\tf_test\lib\site-packages\tensorflow\python\client\session.py", line 471, in __init__
    self._fetch_mapper = _FetchMapper.for_fetch(fetches)

  File "C:\Users\andre\.conda\envs\tf_test\lib\site-packages\tensorflow\python\client\session.py", line 261, in for_fetch
    return _ListFetchMapper(fetch)

  File "C:\Users\andre\.conda\envs\tf_test\lib\site-packages\tensorflow\python\client\session.py", line 370, in __init__
    self._mappers = [_FetchMapper.for_fetch(fetch) for fetch in fetches]

  File "C:\Users\andre\.conda\envs\tf_test\lib\site-packages\tensorflow\python\client\session.py", line 370, in <listcomp>
    self._mappers = [_FetchMapper.for_fetch(fetch) for fetch in fetches]

  File "C:\Users\andre\.conda\envs\tf_test\lib\site-packages\tensorflow\python\client\session.py", line 258, in for_fetch
    type(fetch)))

TypeError: Fetch argument None has invalid type <class 'NoneType'>
```

DeepExplainer works when I replicate the simple MNIST example from the documentation, but not with my model. Do you have any workaround? I see that a couple of persons had the same issue in the past, but didnt get a solution. Thanks

**Comment by Sarjhana** [comment]
Hey, have you found a fix for this? I'm trying to use GradientExplainer for a CNN model and I haven't been able to find a solution so far.
