### ISSUE TITLE
making an executable including SHAP

### ISSUE THREAD

**Issue by wiktorolszowy** [shap/shap#2304]
Thanks a lot for this great library! I was wondering if anyone has had success in making an executable including `SHAP`? I am using `pyinstaller` and I am running into an error. Importantly, to be able to use `matplotlib` with `pyinstaller`, I use `pyinstaller` dev version, following:

https://stackoverflow.com/a/67734977

In the local environment, I am able to run a code with `SHAP`. However, when I use `pyinstaller` to make an executable from `pyinstaller_problem_with_SHAP.py`:

```
import shap
```

I get an `.exe`, which after running returns:

```
Traceback (most recent call last):
  File "pyinstaller_problem_with_SHAP.py", line 2, in <module>
  File "PyInstaller\loader\pyimod03_importers.py", line 495, in exec_module
  File "shap\__init__.py", line 15, in <module>
  File "PyInstaller\loader\pyimod03_importers.py", line 495, in exec_module
  File "shap\explainers\__init__.py", line 3, in <module>
  File "PyInstaller\loader\pyimod03_importers.py", line 495, in exec_module
  File "shap\explainers\_tree.py", line 13, in <module>
  File "PyInstaller\loader\pyimod03_importers.py", line 495, in exec_module
  File "shap\utils\_legacy.py", line 4, in <module>
  File "PyInstaller\loader\pyimod03_importers.py", line 495, in exec_module
  File "sklearn\cluster\__init__.py", line 6, in <module>
  File "PyInstaller\loader\pyimod03_importers.py", line 495, in exec_module
  File "sklearn\cluster\_spectral.py", line 16, in <module>
  File "PyInstaller\loader\pyimod03_importers.py", line 495, in exec_module
  File "sklearn\neighbors\__init__.py", line 6, in <module>
  File "sklearn\neighbors\_ball_tree.pyx", line 1, in init sklearn.neighbors._ball_tree
ModuleNotFoundError: No module named 'sklearn.neighbors._partition_nodes'
[24760] Failed to execute script 'pyinstaller_problem_with_SHAP' due to unhandled exception!
```

I am using Windows, `pip` 21.3.1, `SHAP` 0.40.0, `matplotlib` 3.5.0, `scikit-learn` 1.0.1.

**Comment by Yoosangcheol3730** [comment]
I have same problem. Did you resolve this problem?

**Comment by wiktorolszowy** [comment]
I have solved it. Hidden submodules need to be loaded when building the executable:

`pyinstaller --hidden-import="sklearn.utils._typedefs" --hidden-import="sklearn.neighbors._partition_nodes" SCRIPT_NAME.py`

This is explained here:

https://stackoverflow.com/a/57108887/2339479

If there are errors regarding some other submodules, they need to be added one by one - as error messages appear mentioning which submodule causes problems.
