### ISSUE TITLE
reshape error in HAN model with multi inputs and timedistributed

### ISSUE THREAD

**Issue by lexy0093** [shap/shap#2346]
Hi, slundberg,

**versions：**
keras 2.2.4
tensorflow 1.12.0
python2.7.18
CPU
shap 0.28.5

**Code piece：**
```
word_embedding_layer = Embedding(WORD_VOCAB_LEN,
                            WORD_EMBEDDING_DIM,
                            input_length=MAX_SENT_LENGTH,
                            trainable=True)
                            #mask_zero=True)

tag_embedding_layer = Embedding(TAG_VOCAB_LEN,
                            TAG_EMBEDDING_DIM,
                            input_length=MAX_SENTS,
                            trainable=True)
                            #mask_zero=True)

class AttLayer(Layer):
    def __init__(self, attention_dim):
        self.init = initializers.get('normal')
        self.supports_masking = True
        self.attention_dim = attention_dim
        super(AttLayer, self).__init__()

    def build(self, input_shape):
        assert len(input_shape) == 3
        self.W = K.variable(self.init((input_shape[-1], self.attention_dim)), name='W')
        self.b = K.variable(self.init((self.attention_dim, )), name='b')
        self.u = K.variable(self.init((self.attention_dim, 1)), name='u')
        self.trainable_weights = [self.W, self.b, self.u]
        super(AttLayer, self).build(input_shape)

    def compute_mask(self, inputs, mask=None):
        return mask

    def call(self, x, mask=None):
        # size of x :[batch_size, sel_len, attention_dim]
        # size of u :[batch_size, attention_dim]
        # uit = tanh(xW+b)
        uit = K.tanh(K.bias_add(K.dot(x, self.W), self.b))
        ait = K.dot(uit, self.u)
        ait = K.squeeze(ait, -1)

        ait = K.exp(ait)

        if mask is not None:
            # Cast the mask to floatX to avoid float64 upcasting in theano
            ait *= K.cast(mask, K.floatx())
        aa = K.sum(ait, axis=1, keepdims=True)
        ait /= K.cast(aa + K.epsilon(), K.floatx())
        ait = K.expand_dims(ait)
        weighted_input = x * ait
        output = K.sum(weighted_input, axis=1)

        return output

    def compute_output_shape(self, input_shape):
        return (input_shape[0], input_shape[-1])


sentence_input = Input(shape=(MAX_SENT_LENGTH, ), dtype='int32')
tag_input      = Input(shape=(MAX_SENTS, ), dtype='int32')

embedded_sequences = word_embedding_layer(sentence_input)
l_lstm = Bidirectional(GRU(128, return_sequences=True))(embedded_sequences)
l_att = AttLayer(128)(l_lstm)
sentEncoder = Model(sentence_input, l_att)

review_input     = Input(shape=(MAX_SENTS, MAX_SENT_LENGTH), dtype='int32')
embedded_tags = tag_embedding_layer(tag_input)

review_encoder = TimeDistributed(sentEncoder)(review_input)
review_encoder_tag = concatenate([embedded_tags, review_encoder], axis = -1)
l_lstm_sent = Bidirectional(GRU(128, return_sequences=True))(review_encoder_tag)
l_att_sent = AttLayer(128)(l_lstm_sent)
preds = Dense(1, activation='sigmoid')(l_att_sent)
model = Model(inputs=[tag_input, review_input], outputs=preds)

model.compile(loss='binary_crossentropy',
              optimizer='adam',
              metrics=['accuracy'])

checkpoint_path = 'test_model/weights.{epoch:02d}-{val_loss:.2f}.hdf5'
cp_callback = keras.callbacks.ModelCheckpoint(filepath=checkpoint_path, save_weights_only=True, verbose=1)
tbCallBack = keras.callbacks.TensorBoard(log_dir="./log")

model.fit(x = [x1_train, x_train], y = y_train, validation_data=([x1_val, x_val], y_val),
          epochs=1, verbose=1, batch_size=128, callbacks=[cp_callback])

import shap
explainer = shap.DeepExplainer(model, [x1_train[:100], x_train[:100]], session = K.get_session())
shap_values = explainer.shap_values([x1_val[:1], x_val[:1]])

shap.initjs()

plot = shap.force_plot(explainer.expected_value[0], np.concatenate([shap_values[0][0], shap_values[0][1]], axis=1)[1])
shap.save_html("han.html", plot)

```
as follow error
```
Traceback (most recent call last):
  File "xx.py", line 170, in <module>
    shap_values = explainer.shap_values([x1_val[:1], x_val[:1]])
  File "xxx/anaconda3/envs/tensorflow_eval/lib/python2.7/site-packages/shap/explainers/deep/__init__.py", line 119, in shap_values
    return self.explainer.shap_values(X, ranked_outputs, output_rank_order)
  File "xxx/anaconda3/envs/tensorflow_eval/lib/python2.7/site-packages/shap/explainers/deep/deep_tf.py", line 273, in shap_values
    sample_phis = self.run(rr, self.model_inputs, joint_input)
  File "xxx/anaconda3/envs/tensorflow_eval/lib/python2.7/site-packages/shap/explainers/deep/deep_tf.py", line 293, in run
    return self.session.run(out, feed_dict)
  File "xxx/anaconda3/envs/tensorflow_eval/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 929, in run
    run_metadata_ptr)
  File "xxx/anaconda3/envs/tensorflow_eval/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1152, in _run
    feed_dict_tensor, options, run_metadata)
  File "xxx/anaconda3/envs/tensorflow_eval/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1327, in _do_run
    run_metadata)
  File "xxx/anaconda3/envs/tensorflow_eval/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1347, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Input to reshape is a tensor with 2000000 values, but the requested shape has 40000
	 [[node gradients/time_distributed_1/att_layer_1/Sum_grad/Reshape (defined at xxx/anaconda3/envs/tensorflow_eval/lib/python2.7/site-packages/shap/explainers/deep/deep_tf.py:211)  = Reshape[T=DT_FLOAT, Tshape=DT_INT32, _device="/job:localhost/replica:0/task:0/device:CPU:0"](gradients/time_distributed_1/att_layer_1/add_1_grad/Sum, gradients/time_distributed_1/att_layer_1/Sum_grad/DynamicStitch)]]
```
**much appreciate for any reply !!!!**

**Comment by lexy0093** [comment]
debug for long days....

**Comment by NadirZhang** [comment]
Experiencing the same problem, please ask you solve it? Any reply is welcome
[https://github.com/slundberg/shap/issues/2872](url)
