### ISSUE TITLE
Heatmap error

### ISSUE THREAD

**Issue by PARODBE** [shap/shap#2404]
Hi,

When I am using the heatmap plot, I am obtaining this error: The hclust order only supports 2D arrays right now!.

Could you help me? If I select the output shap values for first class for example for have 2D array I get the error:'numpy.ndarray' object has no attribute 'values'..

Could you help me please??

Thanks!

Pablo

**Comment by thatlittleboy** [comment]
Please provide a reproducible example. Will close the issue for now

**Comment by pwner-web** [comment]
I also encountered the same problem, How should I modify it?

>>> X.shape
torch.Size([1064, 60660])
>>> shap_values = explainer(X[:1000])
>>> shap_values.shape
(1000, 60660, 1)
>>> shap.plots.heatmap(shap_values, show=False, max_display=12)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "D:\Anaconda\envs\pytorch\Lib\site-packages\shap\plots\_heatmap.py", line 78, in heatmap
    instance_order = convert_ordering(instance_order, shap_values)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Anaconda\envs\pytorch\Lib\site-packages\shap\plots\_utils.py", line 23, in convert_ordering
    ordering = ordering.apply(Explanation(shap_values))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Anaconda\envs\pytorch\Lib\site-packages\shap\utils\_general.py", line 278, in apply
    obj = getattr(obj, op)(*args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Anaconda\envs\pytorch\Lib\site-packages\shap\_explanation.py", line 606, in hclust
    raise DimensionError("The hclust order only supports 2D arrays right now!")
shap.utils._exceptions.DimensionError: The hclust order only supports 2D arrays right now!
