### ISSUE TITLE
RuntimeError: element 0 of tensors does not require grad and does not have a grad_fn

### ISSUE THREAD

**Issue by gonkillu** [shap/shap#2430]
batch_x, batch_x_mark, dec_inp, batch_y_mark are the inputs of my model. Their type is torch.tensor and all the elements are float. 
When I run the code as follows: 
```
input_ = [batch_x, batch_x_mark, dec_inp, batch_y_mark]
ex = self.explain(self.model, input_)  
print(ex)                        
ex_values = ex.shap_values(input_)
print(ex_values)
```

It gives me: 
```
Traceback (most recent call last):
  File "/opt/conda/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/opt/conda/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/root/.vscode-server/extensions/ms-python.python-2022.2.1924087327/pythonFiles/lib/python/debugpy/__main__.py", line 45, in <module>
    cli.main()
  File "/root/.vscode-server/extensions/ms-python.python-2022.2.1924087327/pythonFiles/lib/python/debugpy/../debugpy/server/cli.py", line 444, in main
    run()
  File "/root/.vscode-server/extensions/ms-python.python-2022.2.1924087327/pythonFiles/lib/python/debugpy/../debugpy/server/cli.py", line 285, in run_file
    runpy.run_path(target_as_str, run_name=compat.force_str("__main__"))
  File "/opt/conda/lib/python3.7/runpy.py", line 263, in run_path
    pkg_name=pkg_name, script_name=fname)
  File "/opt/conda/lib/python3.7/runpy.py", line 96, in _run_module_code
    mod_name, mod_spec, pkg_name, script_name)
  File "/opt/conda/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/workspace/Autoformer-modify/run.py", line 119, in <module>
    exp.test(setting, test=1)
  File "/workspace/Autoformer-modify/exp/exp_main.py", line 262, in test
    ex_values = ex.shap_values(input_)
  File "/opt/conda/lib/python3.7/site-packages/shap/explainers/_deep/__init__.py", line 124, in shap_values
    return self.explainer.shap_values(X, ranked_outputs, output_rank_order, check_additivity=check_additivity)
  File "/opt/conda/lib/python3.7/site-packages/shap/explainers/_deep/deep_pytorch.py", line 185, in shap_values
    sample_phis = self.gradient(feature_ind, joint_x)
  File "/opt/conda/lib/python3.7/site-packages/shap/explainers/_deep/deep_pytorch.py", line 123, in gradient
    allow_unused=True)[0]
  File "/opt/conda/lib/python3.7/site-packages/torch/autograd/__init__.py", line 228, in grad
    inputs, allow_unused, accumulate_grad=False)
RuntimeError: element 0 of tensors does not require grad and does not have a grad_fn
``` 
I've tried this:
```
input_ = [Variable(batch_x, requires_grad=True),Variable(batch_x_mark, requires_grad=True),Variable(dec_inp, requires_grad=True),Variable(batch_y_mark, requires_grad=True)]
ex = self.explain(self.model, input_)
```
But it doesn't work.

Is there any solution please?

I have solved it. It is because I have 
```
with torch.no_grad():
```
before the codes.

**Comment by xioahua** [comment]
I have the same issue, but adding the `with torch.no_grad():` before my code does also not work. Are there any other solutions please?

**Comment by masterdezign** [comment]
> I have the same issue, but adding the with torch.no_grad(): before my code does also not work. 

It is the inverse: the code does not work because you add `torch.no_grad()`. Also you may want to check if the gradients are destroyed elsewhere too (e.g. converting from tensor to numpy array). See also [this](https://discuss.pytorch.org/t/element-0-of-tensors-does-not-require-grad-and-does-not-have-a-grad-fn-how-can-i-fix-this/140756/2).
