### ISSUE TITLE
Universal Sentence Encoder Input Error: 'str' object has no attribute 'shape'

### ISSUE THREAD

**Issue by zzj0402** [shap/shap#2605]
I am trying to explain a customly trained USE model from the TFHub.
The model takes string as inputs.
I get this while trying to call the explainer function:
```
root@d0c5d073d95f:/workspace# python use/explain.py 
Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
=================================================================
 keras_layer (KerasLayer)    (None, 512)               147354880 
                                                                 
 output (Dense)              (None, 5)                 2565      
                                                                 
=================================================================
Total params: 147,357,445
Trainable params: 147,357,445
Non-trainable params: 0
_________________________________________________________________
Traceback (most recent call last):
  File "/use/explain.py", line 31, in <module>
    shap_values = explainer([prompts[9], prompts[18]])
  File "/usr/local/lib/python3.8/dist-packages/shap/explainers/_permutation.py", line 82, in __call__
    return super().__call__(
  File "/usr/local/lib/python3.8/dist-packages/shap/explainers/_explainer.py", line 266, in __call__
    row_result = self.explain_row(
  File "/usr/local/lib/python3.8/dist-packages/shap/explainers/_permutation.py", line 92, in explain_row
    fm = MaskedModel(self.model, self.masker, self.link, self.linearize_link, *row_args)
  File "/usr/local/lib/python3.8/dist-packages/shap/utils/_masked_model.py", line 48, in __init__
    self._masker_cols = sum(np.prod(a.shape) for a in self.args)
  File "/usr/local/lib/python3.8/dist-packages/shap/utils/_masked_model.py", line 48, in <genexpr>
    self._masker_cols = sum(np.prod(a.shape) for a in self.args)
AttributeError: 'str' object has no attribute 'shape'
```
The prompts are two string inputs from the test set.

```
import shap

import json
import tensorflow as tf
import tensorflow_hub as hub
import os
import sys
import numpy as np


def load_model(path):
    """Loads a model from a .h5 file."""
    sys.path.append(os.path.dirname(path))
    return tf.keras.models.load_model(path, custom_objects={'KerasLayer': hub.KerasLayer})


def read_test_data(path):
    """Reads test data from a jsonl file."""
    return [json.loads(line) for line in open(path, 'r')]


model = load_model('use/model.h5')
model.summary()

data = read_test_data('test_mapped.jsonl')
prompts = [d['description'] for d in data]
truths = [d['label'] for d in data]

# explain the model on two sample inputs
explainer = shap.Explainer(model)
shap_values = explainer([prompts[9], prompts[18]])

# visualize the first prediction's explanation for the correct output class
shap.plots.text(shap_values[0, :, truths[9]])
```

**Comment by AymericBasset** [comment]
same issue
