### ISSUE TITLE
Using DeepExplainer for LSTM : AttributeError: 'Deep' object has no attribute 'masker'

### ISSUE THREAD

**Issue by vatsaltailor** [shap/shap#2614]
We need SHAP plots for our model following model:

![image](https://user-images.githubusercontent.com/37294848/178009757-a8285307-ac0d-4920-999d-96dc276b44a8.png)

![image](https://user-images.githubusercontent.com/37294848/178009873-f71e3e30-b45d-4ba8-b285-8b51a427ac60.png)

We attempt to use SHAP:
![image](https://user-images.githubusercontent.com/37294848/178010011-7508ab7d-f017-46f2-a055-a616f1b13d7e.png)

And face the following error:

In [56]: import shap
    ...: explainer = shap.DeepExplainer(model2, x_train_appended)
    ...: shap_values = explainer(x_train_appended)
WARNING:tensorflow:Layers in a Sequential model should only have a single input tensor, but we receive a <class 'list'> input: [<tf.Tensor: shape=(49586, 1, 23), dtype=float32, numpy=
array([[[0.40824828, 0.02564103, 0.03370786, ..., 0.4494382 ,
         0.43333334, 0.59210527]],

       [[0.        , 0.06410257, 0.05617978, ..., 0.4494382 ,
         0.43333334, 0.59210527]],

       [[0.5400617 , 0.06410257, 0.06741573, ..., 0.4494382 ,
         0.43333334, 0.59210527]],

       ...,

       [[0.5400617 , 0.01282051, 0.05617978, ..., 0.07865169,
         0.01111111, 0.05263158]],

       [[0.        , 0.02564103, 0.05617978, ..., 0.07865169,
         0.01111111, 0.05263158]],

       [[0.        , 0.02564103, 0.05617978, ..., 0.07865169,
         0.01111111, 0.05263158]]], dtype=float32)>]
Consider rewriting this model with the Functional API.
Traceback (most recent call last):

  File "<ipython-input-56-eb8375f15ecb>", line 3, in <module>
    shap_values = explainer(x_train_appended)

  File "/home/kiton/.local/lib/python3.8/site-packages/shap/explainers/_explainer.py", line 207, in __call__
    if issubclass(type(self.masker), maskers.OutputComposite) and len(args)==2:

AttributeError: 'Deep' object has no attribute 'masker'

It seems like the explainer(x_train_appended) is responsible for this error. 
We are using:
numba                        0.55.1
numpy                        1.18.5
shap                         0.40.0
Keras                        2.4.3

**Comment by remo-help** [comment]
I've gotten this error before when an explainer could not take a sparse vector representation (not deep explainer).
Are you using a dense array or a sparse array? If the latter try a dense array, just to see if that will fix it.

Also, consider trying shap 0.41, the new update fixed some issues I was having

**Comment by vatsaltailor** [comment]
Hi Remo, Thanks a lot for your response. We are using Numpy Array. 
We did not upgrade our shap to 0.41 because it demanded newer versions of Numba and it was rendering Keras to not work. 

Let me try to convert our Numpy Array to a Dense SciPy array and see if that helps, I will update you.

Thanks a lot for the time!

**Comment by remo-help** [comment]
A numpy array should be dense already, if you're not sure that it is, you can call `your_data.toarray()`

**Comment by vatsaltailor** [comment]
Thanks a lot Remo! Yes it is already dense. Do you have any idea what else
might be causing it? Thanks a lot for the help!

**Comment by remo-help** [comment]
The masker error should be related to the background distribution you pass. I think it might be solved in shap == 0.41

There are a few things I would try:

- 1. Pass the models predict function directly, instead of the model
`explainer = shap.DeepExplainer(model_2.predict, x_train_append)`

- 2. You can try not calling the DeepExplainer, but just let SHAP select an explainer, like so:
`explainer = shap.Explainer(model_2, x_train_append)`

- 3. You can test if your problem is explainer specific, by using a model agnostic explainer:
`explainer = shap.explainers.Sampling(model_2.predict, shap.kmeans(x_train_append,50))`

**Comment by remo-help** [comment]
One last thing, regarding this warning:
`WARNING:tensorflow:Layers in a Sequential model should only have a single input tensor, but we receive a <class 'list'>`

Are you passing the input as a list somehow? If this is the case, then that would probably break the explainer. Your input should be one array, not a list of arrays.

**Comment by vatsaltailor** [comment]
Thanks a ton, Remo! This is very helpful, Let us try these out.

**Comment by vatsaltailor** [comment]
Hi @remo-help, thanks a lot for the above suggestions, I tried all 3 of them, and I realized from the errors, that the problem might have something to do with the shape of the input (we are not using a list but a 3d NumPy array).  

SHAP's documentation states the following: (https://shap.readthedocs.io/en/latest/example_notebooks/tabular_examples/neural_networks/Census%20income%20classification%20with%20Keras.html)

"SHAP expects model functions to take a 2D NumPy array as input, so we define a wrapper function around the original Keras predict function"

Thus when we try: shap.DeepExplainer(model_2, x_train_append) , the DeepExplainer wants x_train_append to be 2D NumPy array where as the model_2 wants the data to be 3D since LSTM expects inputs to be 3D.

We would appreciate any of your thoughts on this Remo! Thanks a ton for your time!

**Comment by remo-help** [comment]
Yes, if you are using a 3D array, then this is likely to be the issue.

You can copy what the authors do in the documentation and define a wrapper function that you pass into the explainer instead of the predict method.

Without knowing your feature structure and model I can't give you a suggestion on what that wrapper would look like. I assume your features are 3D so you can have batch-size as one dimension? If that's the case you can try copy the documentation code, I reckon.

**Comment by vatsaltailor** [comment]
Yes @remo-help you are right, it has batch size as one dimension. Let me try copying the documentation code and go ahead from there.
Thanks a lot for your help!

**Comment by wuyanglee** [comment]
use `shap_values = explainer.shap_values(X)` to get these shap_values. make a try.

**Comment by kwtk86** [comment]
for me, the question was caused by the minor inconsistency between the model structure for training and the model structure used in SHAP.
the question got solved after I consistified the structures

**Comment by AliWaheed** [comment]
> use `shap_values = explainer.shap_values(X)` to get these shap_values. make a try.

This actually solves the issue ... thanks

I was facing the error "AttributeError: 'Kernel' object has no attribute 'masker'" and this recommendation solved it.

**Comment by jintiandefanzhenhaochi** [comment]
@vatsaltailor Hello, I encountered the same problem when training the lstm model. I see that your previous solution is that deepexplainer requires 2D Numpy input, and the model is 3D input. So how to change the input dimension to be suitable for deepexplainer ?  And my current network input shape is ( None, 128, 2 ) thank you~~

**Comment by remo-help** [comment]
@jintiandefanzhenhaochi since one of your dimensions is none, try:
`new_vector = torch.squeeze(your_model_output)`
`shap_input = new_vector.numpy()`

**Comment by jintiandefanzhenhaochi** [comment]
@remo-help Thank you very much for your timely help ! I 'll try it right now. I consulted other materials and saw an article explaining the problem of lstm application shap, which should be the problem of input dimension ! Seeing that you have helped solve a lot of problems under the relevant issues, you are so enthusiastic and helpful !

**Comment by mnissen1337** [comment]
Hi. Does one have a solution to this problem? Currently I am training a RNN and LSTM with a sequence length of 24 and 49 features. Therefore, I have data like this (number of samples, 24, 49). This I can do fine

``
import shap
n_traing_samples = 2
explainer = shap.DeepExplainer(model, X_train)
shap_values = explainer.shap_values(X_train[:n_traing_samples]
``
and if I want to use a summary plot, this works

``
shap.summary_plot(shap_values[:, :, :, 0].reshape(n_traing_samples*24, 49), X_train[:2].reshape(n_traing_samples*24, 49), plot_type='bar', feature_names=FEATURES, plot_size=(10, 5))
``

but I can't do a beeswarm-plot or dependence plot since it requires an Explanation object and I won't allow me to do this

``
explainer = shap.DeepExplainer(model, X_train)
shap_obj = explainer(X_train[:n_traing_samples])
``
or this

``
explainer = shap.DeepExplainer(model, X_train)
shap_obj = explainer(X_train[:n_traing_samples].reshape(n_traing_samples*24, 49))
``
