### ISSUE TITLE
SKLearn ElasticNetCV model not supported.

### ISSUE THREAD

**Issue by Exitare** [shap/shap#2620]
Hello,

I´ve used this code to train an ElasticNet model and then use Shap to visualize a waterfall plot.

```

    model = ElasticNetCV(cv=5, random_state=0)
    model.fit(train_data.drop('Case', axis=1), train_data["Case"])

    explainer = shap.Explainer(model)
    shap_values = explainer(train_data.drop('Case', axis=1))

    # visualize the first prediction's explanation
    shap.plots.waterfall(shap_values[0])

```
However,  this code throws the following exception:

Traceback (most recent call last):

>   File "biopsy_prediction.py", line 39, in <module>
>     explainer = shap.Explainer(model)
>   File "/venv/lib/python3.9/site-packages/shap/explainers/_explainer.py", line 173, in __init__
>     raise TypeError("The passed model is not callable and cannot be analyzed directly with the given masker! Model: " + str(model))
> TypeError: The passed model is not callable and cannot be analyzed directly with the given masker! Model: ElasticNetCV(cv=5, random_state=0)

Is this not supported or do I use Shap in a non-intended way?

**Comment by sroener** [comment]
I have the same problem.
