### ISSUE TITLE
Getting error when trying to import SHAP

### ISSUE THREAD

**Issue by SaraAbbaspour** [shap/shap#2708]
It has been a long time I am using SHAP package in Python and had no problem importing it.
But today I get error when trying to import SHAP and I cannot figure out how to solve this issue.
My shap version is 0.39.0 and my python is 3.8

2022-09-29 14:59:27.468815: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'cudart64_110.dll'; dlerror: cudart64_110.dll not found
2022-09-29 14:59:27.468897: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
Traceback (most recent call last):

import shap

  File "C:\Users\srabb\anaconda3\lib\site-packages\shap\__init__.py", line 15, in <module>
    from .explainers._explainer import Explainer

  File "C:\Users\srabb\anaconda3\lib\site-packages\shap\explainers\__init__.py", line 1, in <module>
    from ._permutation import Permutation

  File "C:\Users\srabb\anaconda3\lib\site-packages\shap\explainers\_permutation.py", line 3, in <module>
    from ._explainer import Explainer

  File "C:\Users\srabb\anaconda3\lib\site-packages\shap\explainers\_explainer.py", line 8, in <module>
    from .. import models

  File "C:\Users\srabb\anaconda3\lib\site-packages\shap\models\__init__.py", line 2, in <module>
    from ._teacher_forcing import TeacherForcing

  File "C:\Users\srabb\anaconda3\lib\site-packages\shap\models\_teacher_forcing.py", line 15, in <module>
    import tensorflow as tf

  File "C:\Users\srabb\anaconda3\lib\site-packages\tensorflow\__init__.py", line 41, in <module>
    from tensorflow.python.tools import module_util as _module_util

  File "C:\Users\srabb\anaconda3\lib\site-packages\tensorflow\python\__init__.py", line 49, in <module>
    from tensorflow.python.feature_column import feature_column_lib as feature_column

  File "C:\Users\srabb\anaconda3\lib\site-packages\tensorflow\python\feature_column\feature_column_lib.py", line 22, in <module>
    from tensorflow.python.feature_column.feature_column import *

  File "C:\Users\srabb\anaconda3\lib\site-packages\tensorflow\python\feature_column\feature_column.py", line 147, in <module>
    from tensorflow.python.layers import base

  File "C:\Users\srabb\anaconda3\lib\site-packages\tensorflow\python\layers\base.py", line 20, in <module>
    from tensorflow.python.keras.legacy_tf_layers import base

  File "C:\Users\srabb\anaconda3\lib\site-packages\tensorflow\python\keras\__init__.py", line 25, in <module>
    from tensorflow.python.keras import models

  File "C:\Users\srabb\anaconda3\lib\site-packages\tensorflow\python\keras\models.py", line 20, in <module>
    from tensorflow.python.keras import metrics as metrics_module

  File "C:\Users\srabb\anaconda3\lib\site-packages\tensorflow\python\keras\metrics.py", line 34, in <module>
    from tensorflow.python.keras import activations

  File "C:\Users\srabb\anaconda3\lib\site-packages\tensorflow\python\keras\activations.py", line 18, in <module>
    from tensorflow.python.keras.layers import advanced_activations

  File "C:\Users\srabb\anaconda3\lib\site-packages\tensorflow\python\keras\layers\__init__.py", line 29, in <module>
    from tensorflow.python.keras.layers.preprocessing.image_preprocessing import CenterCrop

  File "C:\Users\srabb\anaconda3\lib\site-packages\tensorflow\python\keras\layers\preprocessing\image_preprocessing.py", line 29, in <module>
    from tensorflow.python.keras.preprocessing import image as image_preprocessing

  File "C:\Users\srabb\anaconda3\lib\site-packages\tensorflow\python\keras\preprocessing\__init__.py", line 26, in <module>
    from tensorflow.python.keras.utils import all_utils as utils

  File "C:\Users\srabb\anaconda3\lib\site-packages\tensorflow\python\keras\utils\all_utils.py", line 34, in <module>
    from tensorflow.python.keras.utils.multi_gpu_utils import multi_gpu_model

  File "C:\Users\srabb\anaconda3\lib\site-packages\tensorflow\python\keras\utils\multi_gpu_utils.py", line 19, in <module>
    from tensorflow.python.keras.engine.training import Model

  File "C:\Users\srabb\anaconda3\lib\site-packages\tensorflow\python\keras\engine\training.py", line 53, in <module>
    from tensorflow.python.keras.saving import save

  File "C:\Users\srabb\anaconda3\lib\site-packages\tensorflow\python\keras\saving\save.py", line 30, in <module>
    import h5py

  File "C:\Users\srabb\anaconda3\lib\site-packages\h5py\__init__.py", line 34, in <module>
    from . import version

  File "C:\Users\srabb\anaconda3\lib\site-packages\h5py\version.py", line 17, in <module>
    from . import h5 as _h5

  File "h5py\h5.pyx", line 41, in init h5py.h5

AttributeError: type object 'h5py.h5.H5PYConfig' has no attribute '__reduce_cython__'

**Comment by CloseChoice** [comment]
Thanks for the report and sorry for the late answer. To me this seems not like a problem with shap but with h5. Trying to import h5 should already throw this problem. I'll mark this as waiting for feedback and it might be close within the next three months if there is no further activity. If you still encounter problems, feel free to comment so that this issue does not get lost.

**Comment by SaraAbbaspour** [comment]
Thank you for your response. I reported this issue a while ago and unfortunately, I don't recall the specific steps I took to resolve it. Nevertheless, I appreciate your reply.

**Comment by CloseChoice** [comment]
Alright, then I'll close this issue. If you encounter any more problems with shap, feel free to open new issues anytime.
