### ISSUE TITLE
Use shap.GPUTreeExplaine on Windows

### ISSUE THREAD

**Issue by MichaelChaoLi-cpu** [shap/shap#2746]
Dear Developers:

The ```shap.GPUTreeExplaine``` can be used on Ubuntu, but little information I know is about running it on Windows.   

My code is:
```
explainerGPU = shap.GPUTreeExplainer(model, seed=1)
shap_values = explainerGPU.shap_values(X.iloc[0:10,:])
```

Direct running returns the message:
```
cuda extension was not built during install!
Traceback (most recent call last):

  File "C:\Users\XXX\AppData\Local\Temp\ipykernel_23528\1948042088.py", line 1, in <cell line: 1>
    shap_values = explainerGPU.shap_values(X.iloc[0:10,:])

  File "D:\Anaconda3\envs\Usegdal\lib\site-packages\shap\explainers\_gpu_tree.py", line 105, in shap_values
    assert_import("cext_gpu")

  File "D:\Anaconda3\envs\Usegdal\lib\site-packages\shap\utils\_general.py", line 25, in assert_import
    raise e

  File "D:\Anaconda3\envs\Usegdal\lib\site-packages\IPython\core\interactiveshell.py", line 3552, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)

  File "C:\Users\XXX\AppData\Local\Temp\ipykernel_23528\1948042088.py", line 1, in <cell line: 1>
    shap_values = explainerGPU.shap_values(X.iloc[0:10,:])

  File "D:\Anaconda3\envs\Usegdal\lib\site-packages\shap\explainers\_gpu_tree.py", line 105, in shap_values
    assert_import("cext_gpu")

  File "D:\Anaconda3\envs\Usegdal\lib\site-packages\shap\utils\_general.py", line 25, in assert_import
    raise e

  File "D:\Anaconda3\envs\Usegdal\lib\site-packages\IPython\core\interactiveshell.py", line 3552, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)

  File "C:\Users\XXX\AppData\Local\Temp\ipykernel_23528\1948042088.py", line 1, in <cell line: 1>
    shap_values = explainerGPU.shap_values(X.iloc[0:10,:])

  File "D:\Anaconda3\envs\Usegdal\lib\site-packages\shap\explainers\_gpu_tree.py", line 105, in shap_values
    assert_import("cext_gpu")

  File "D:\Anaconda3\envs\Usegdal\lib\site-packages\shap\utils\_general.py", line 25, in assert_import
    raise e

  File "D:\Anaconda3\envs\Usegdal\lib\site-packages\IPython\core\interactiveshell.py", line 3552, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)

  File "C:\Users\XXX\AppData\Local\Temp\ipykernel_23528\1675054601.py", line 1, in <cell line: 1>
    shap_values = explainerGPU(X.iloc[0:10,:])

  File "D:\Anaconda3\envs\Usegdal\lib\site-packages\shap\explainers\_tree.py", line 217, in __call__
    v = self.shap_values(X, y=y, from_call=True, check_additivity=check_additivity, approximate=self.approximate)

  File "D:\Anaconda3\envs\Usegdal\lib\site-packages\shap\explainers\_gpu_tree.py", line 105, in shap_values
    assert_import("cext_gpu")

  File "D:\Anaconda3\envs\Usegdal\lib\site-packages\shap\utils\_general.py", line 25, in assert_import
    raise e

  File "D:\Anaconda3\envs\Usegdal\lib\site-packages\shap\explainers\_gpu_tree.py", line 6, in <module>
    from .. import _cext_gpu

ImportError: cannot import name '_cext_gpu' from partially initialized module 'shap' (most likely due to a circular import) (D:\Anaconda3\envs\Usegdal\lib\site-packages\shap\__init__.py)
```
How to config ```shap```?

My GPU is NVIDIA GeForce GTX 1080. Is it okay?

Thank you.

**Comment by DaBingNai2** [comment]
hello! I think u should renew the shap to 0.43.0 . Another way is download the Git from Github, and use 'python setup.py install ' in CMD of window. Care about the information in CMD, maybe u need to add cuda path or vs path(cl.exe) in 'environment Path'.Try it!

**Comment by fewfgegfuegf555** [comment]
hello, I have also encountered this problem. Have you solved it

**Comment by MichaelChaoLi-cpu** [comment]
Thank you.
It does not work any way. I booted an Ubuntu. It is solved.

------------------------------------------------------------------------------------
Chao Li (Mike)
Researcher
Urban Institute, Kyushu University
Data Scientist
aiESG, Inc.
*My Google Sholar Profile:*
https://scholar.google.co.jp/citations?hl=zh-CN&user=mU7VIn8AAAAJ
*ORCID:* https://orcid.org/my-orcid?orcid=0000-0002-6854-4456
*Github: *https://github.com/MichaelChaoLi-cpu
*My Website:* http://plum-data.com/
744 Motooka, Nishi-ku, Fukuoka 819-0395 Japan
Tel: 090-8304-8953
E-mail: ***@***.***
            ***@***.***
-------------------------------------------------------------------------------------
李潮（リ チョウ）
九州大学 都市研究センター 研究員
株式会社 aiESG  データサイエンティスト
-------------------------------------------------------------------------------------


fewfgegfuegf555 ***@***.***>于2024年10月24日 周四17:06写道：

**Comment by fewfgegfuegf555** [comment]
Okay, thank you for your reply
