### ISSUE TITLE
Could not compile cuda extensions on Linux Ubuntu 20.04

### ISSUE THREAD

**Issue by MichaelChaoLi-cpu** [shap/shap#2776]
Hi, all,

Thank you for reading my issue.

I am trying to install ```shap``` and use GPU to accelerate. I follow this:

Check to makes sure you have the NVIDA CUDA Toolkit installed by running the nvcc command (the CUDA compiler) from the terminal. If this command is not found then you need to install it with something like sudo apt install nvidia-cuda-toolkit.

Once the NVIDA CUDA Toolkit is installed you need to set the CUDA_PATH environment variable. If which nvcc produces /usr/bin/nvcc then you can run ```export CUDA_PATH=/usr```.

Build SHAP with CUDA support by cloning the shap repo using git clone https://github.com/slundberg/shap.git then running python setup.py install --user.

Here I test both both ```export CUDA_PATH=/usr``` and ```export CUDA_PATH=/usr/```.

However I cannot complete install it:

During the installation:
```
(ForShap) mike@mike-desktop:~/shap$ python setup.py install --user
NVCC ==>  /usr/bin/nvcc
Compiling cuda extension, calling nvcc with arguments:
['/usr/bin/nvcc', 'shap/cext/_cext_gpu.cu', '-lib', '-o', 'build/lib_cext_gpu.a', '-Xcompiler', '-fPIC', '-I/home/mike/anaconda3/envs/ForShap/include/python3.9', '--std', 'c++14', '--expt-extended-lambda', '--expt-relaxed-constexpr', '-arch=sm_37', '-gencode=arch=compute_37,code=sm_37', '-gencode=arch=compute_70,code=sm_70', '-gencode=arch=compute_75,code=sm_75', '-gencode=arch=compute_75,code=compute_75']
nvcc warning : The 'compute_35', 'compute_37', 'compute_50', 'sm_35', 'sm_37' and 'sm_50' architectures are deprecated, and may be removed in a future release (Use -Wno-deprecated-gpu-targets to suppress warning).
/usr/include/c++/11/bits/std_function.h:435:145: error: parameter packs not expanded with ‘...’:
  435 |         function(_Functor&& __f)
      |                                                                                                                                                 ^ 
/usr/include/c++/11/bits/std_function.h:435:145: note:         ‘_ArgTypes’
/usr/include/c++/11/bits/std_function.h:530:146: error: parameter packs not expanded with ‘...’:
  530 |         operator=(_Functor&& __f)
      |                                                                                                                                                  ^ 
/usr/include/c++/11/bits/std_function.h:530:146: note:         ‘_ArgTypes’
Error building cuda module: CalledProcessError(1, ['/usr/bin/nvcc', 'shap/cext/_cext_gpu.cu', '-lib', '-o', 'build/lib_cext_gpu.a', '-Xcompiler', '-fPIC', '-I/home/mike/anaconda3/envs/ForShap/include/python3.9', '--std', 'c++14', '--expt-extended-lambda', '--expt-relaxed-constexpr', '-arch=sm_37', '-gencode=arch=compute_37,code=sm_37', '-gencode=arch=compute_70,code=sm_70', '-gencode=arch=compute_75,code=sm_75', '-gencode=arch=compute_75,code=compute_75'])
WARNING: Could not compile cuda extensions
......
``` 

Then I run the code to test:
```
import shap
import xgboost

# get a dataset on income prediction
X,y = shap.datasets.adult()

# train an XGBoost model (but any other model type would also work)
model = xgboost.XGBClassifier()
model.fit(X, y)
# build a Permutation explainer and explain the model predictions on the given dataset
explainer = shap.explainers.GPUTree(model, X)
```

The first error comes:
```
>>> explainer = shap.explainers.GPUTree(model, X)
C extension was not built during install!
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/mike/shap/shap/explainers/_tree.py", line 149, in __init__
    self.model = TreeEnsemble(model, self.data, self.data_missing, model_output)
  File "/home/mike/shap/shap/explainers/_tree.py", line 837, in __init__
    self.trees = xgb_loader.get_trees(data=data, data_missing=data_missing)
  File "/home/mike/shap/shap/explainers/_tree.py", line 1540, in get_trees
    trees.append(SingleTree({
  File "/home/mike/shap/shap/explainers/_tree.py", line 1141, in __init__
    assert_import("cext")
  File "/home/mike/shap/shap/utils/_general.py", line 25, in assert_import
    raise e
  File "/home/mike/shap/shap/explainers/_tree.py", line 25, in <module>
    from .. import _cext
ImportError: cannot import name '_cext' from partially initialized module 'shap' (most likely due to a circular import) (/home/mike/shap/shap/__init__.py)

```

Then I check ```conda list```:
```
(ForShap) mike@mike-desktop:~/shap$ conda list
# packages in environment at /home/mike/anaconda3/envs/ForShap:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                        main  
_openmp_mutex             5.1                       1_gnu  
_py-xgboost-mutex         2.0                       cpu_0  
blas                      1.0                         mkl  
ca-certificates           2022.10.11           h06a4308_0  
certifi                   2022.9.24        py39h06a4308_0  
cloudpickle               2.2.0                    pypi_0    pypi
fftw                      3.3.9                h27cfd23_1  
intel-openmp              2021.4.0          h06a4308_3561  
joblib                    1.2.0                    pypi_0    pypi
ld_impl_linux-64          2.38                 h1181459_1  
libffi                    3.3                  he6710b0_2  
libgcc-ng                 11.2.0               h1234567_1  
libgfortran-ng            11.2.0               h00389a5_1  
libgfortran5              11.2.0               h1234567_1  
libgomp                   11.2.0               h1234567_1  
libstdcxx-ng              11.2.0               h1234567_1  
libxgboost                1.5.0                h6a678d5_2  
llvmlite                  0.39.1                   pypi_0    pypi
mkl                       2021.4.0           h06a4308_640  
mkl-service               2.4.0            py39h7f8727e_0  
mkl_fft                   1.3.1            py39hd3c417c_0  
mkl_random                1.2.2            py39h51133e4_0  
ncurses                   6.3                  h5eee18b_3  
numba                     0.56.4                   pypi_0    pypi
numpy                     1.23.4           py39h14f4228_0  
numpy-base                1.23.4           py39h31eccc5_0  
openssl                   1.1.1s               h7f8727e_0  
packaging                 21.3                     pypi_0    pypi
pandas                    1.5.2                    pypi_0    pypi
pip                       22.2.2           py39h06a4308_0  
py-xgboost                1.5.0            py39h06a4308_2  
pyparsing                 3.0.9                    pypi_0    pypi
python                    3.9.15               haa1d7c7_0  
python-dateutil           2.8.2                    pypi_0    pypi
pytz                      2022.6                   pypi_0    pypi
readline                  8.2                  h5eee18b_0  
scikit-learn              1.1.3                    pypi_0    pypi
scipy                     1.9.3                    pypi_0    pypi
setuptools                65.5.0           py39h06a4308_0  
six                       1.16.0                   pypi_0    pypi
slicer                    0.0.7                    pypi_0    pypi
sqlite                    3.40.0               h5082296_0  
threadpoolctl             3.1.0                    pypi_0    pypi
tk                        8.6.12               h1ccaba5_0  
tqdm                      4.64.1                   pypi_0    pypi
tzdata                    2022f                h04d1e81_0  
wheel                     0.37.1             pyhd3eb1b0_0  
xgboost                   1.5.0            py39h06a4308_2  
xz                        5.2.6                h5eee18b_0  
zlib                      1.2.13               h5eee18b_0  
```
I try to install ```gcc``` to solve, by ```conda install -c conda-forge gcc```.

Then the error in installation:
```
(ForShap) mike@mike-desktop:~/shap$ python setup.py install --user
NVCC ==>  /usr/bin/nvcc
Compiling cuda extension, calling nvcc with arguments:
['/usr/bin/nvcc', 'shap/cext/_cext_gpu.cu', '-lib', '-o', 'build/lib_cext_gpu.a', '-Xcompiler', '-fPIC', '-I/home/mike/anaconda3/envs/ForShap/include/python3.9', '--std', 'c++14', '--expt-extended-lambda', '--expt-relaxed-constexpr', '-arch=sm_37', '-gencode=arch=compute_37,code=sm_37', '-gencode=arch=compute_70,code=sm_70', '-gencode=arch=compute_75,code=sm_75', '-gencode=arch=compute_75,code=compute_75']
nvcc warning : The 'compute_35', 'compute_37', 'compute_50', 'sm_35', 'sm_37' and 'sm_50' architectures are deprecated, and may be removed in a future release (Use -Wno-deprecated-gpu-targets to suppress warning).
gcc: fatal error: cannot execute 'cc1plus': execvp: No such file or directory
compilation terminated.
nvcc fatal   : Failed to preprocess host compiler properties.
Error building cuda module: CalledProcessError(1, ['/usr/bin/nvcc', 'shap/cext/_cext_gpu.cu', '-lib', '-o', 'build/lib_cext_gpu.a', '-Xcompiler', '-fPIC', '-I/home/mike/anaconda3/envs/ForShap/include/python3.9', '--std', 'c++14', '--expt-extended-lambda', '--expt-relaxed-constexpr', '-arch=sm_37', '-gencode=arch=compute_37,code=sm_37', '-gencode=arch=compute_70,code=sm_70', '-gencode=arch=compute_75,code=sm_75', '-gencode=arch=compute_75,code=compute_75'])
WARNING: Could not compile cuda extensions
......
```

Still does not work.

Please help me! Thank you for reading my long log.

**Comment by RuiPedroFerreira** [comment]
I have the same issue. :\

**Comment by znacer** [comment]
I get the same error, even when I am not trying to specifically try to make an installation for CUDA.
Running `pip install -e .` or `pip install -e ".[test-core]"` raises the error.

I suspect the arguments to not be what they should in this part of code : 
https://github.com/shap/shap/blob/ca08229b8bb93ae05311532b7cc84f21ea8a8043/setup.py#L76C1-L82C6

**Comment by noxthot** [comment]
I think you should not add `gcc` to your conda environment (imo the environment should contain exactly what is proposed by the shap package). I would rather suggest to install `g++` directly in Ubuntu:
```bash
sudo apt install g++
```

`gcc` is mainly used for compiling `C`-code and might be missing links to relevant parts for compiling `C++` code (like e.g. `cc1plus`).

Disclaimer: I am not an expert, but since this issue is quite old and obviously still lacks a solution, I just try to help. In case this helps, I would suggest to update the docs to reflect this requirement in Ubuntu.

**Comment by znacer** [comment]
Concerning my case, I was missing `python-devel`(RHEL, `python-dev` for ubuntu users).
