### ISSUE TITLE
 X,y = shap.datasets.california(n_points=1000)-->PicklingError

### ISSUE THREAD

**Issue by Erwachen6** [shap/shap#2793]
code:
"""
import shap
import sklearn

# a classic housing price dataset
X,y = shap.datasets.california(n_points=1000)

X100 = shap.utils.sample(X, 100) # 100 instances for use as the background distribution

# a simple linear model
model = sklearn.linear_model.LinearRegression()
model.fit(X, y)
"""

When I run it, the error:

  File "E:\Anaconda\lib\site-packages\spyder\utils\site\sitecustomize.py", line 705, in runfile
    execfile(filename, namespace)

  File "E:\Anaconda\lib\site-packages\spyder\utils\site\sitecustomize.py", line 102, in execfile
    exec(compile(f.read(), filename, 'exec'), namespace)

  File "C:/Users/pc/Desktop/毕业设计/code/SHAP1.py", line 12, in <module>
    X,y = shap.datasets.california()

  File "E:\Anaconda\lib\site-packages\shap\datasets.py", line 42, in california
    d = sklearn.datasets.fetch_california_housing()

  File "C:\Users\pc\AppData\Roaming\Python\Python36\site-packages\sklearn\utils\validation.py", line 63, in inner_f
    return f(*args, **kwargs)

  File "C:\Users\pc\AppData\Roaming\Python\Python36\site-packages\sklearn\datasets\_california_housing.py", line 145, in fetch_california_housing
    joblib.dump(cal_housing, filepath, compress=6)

  File "C:\Users\pc\AppData\Roaming\Python\Python36\site-packages\joblib\numpy_pickle.py", line 479, in dump
    NumpyPickler(f, protocol=protocol).dump(value)

  File "E:\Anaconda\lib\pickle.py", line 409, in dump
    self.save(obj)

  File "C:\Users\pc\AppData\Roaming\Python\Python36\site-packages\joblib\numpy_pickle.py", line 270, in save
    Pickler.save(self, wrapper)

  File "E:\Anaconda\lib\pickle.py", line 521, in save
    self.save_reduce(obj=obj, *rv)

  File "E:\Anaconda\lib\pickle.py", line 605, in save_reduce
    save(cls)

  File "C:\Users\pc\AppData\Roaming\Python\Python36\site-packages\joblib\numpy_pickle.py", line 284, in save
    return Pickler.save(self, obj)

  File "E:\Anaconda\lib\pickle.py", line 476, in save
    f(self, obj) # Call unbound method with explicit self

  File "E:\Anaconda\lib\pickle.py", line 978, in save_type
    return self.save_global(obj)

  File "E:\Anaconda\lib\pickle.py", line 927, in save_global
    (obj, module_name, name))

PicklingError: Can't pickle <class 'joblib.numpy_pickle.NumpyArrayWrapper'>: it's not the same object as joblib.numpy_pickle.NumpyArrayWrapper

and my joblib version is 1.1.1, shap version is 0.41.0, python version is 3.6.5.
How can I solve this problem?

**Comment by dsgibbons** [comment]
I cannot replicate your issue. Please note that SHAP is only supported for Python 3.7+.

**Comment by dsgibbons** [comment]
Closing, as no feedback was received.

**Comment by ammarsaf** [comment]
I am running from Google Colab, the same line of downloading California dataset; the following error showed

```
---------------------------------------------------------------------------
HTTPError                                 Traceback (most recent call last)
[<ipython-input-11-e7a77a91cdc5>](https://localhost:8080/#) in <cell line: 1>()
----> 1 X, y = shap.datasets.california()
      2 X100 = shap.utils.sample(X, 100)
      3 
      4 model = sklearn.linear_model.LinearRegression()
      5 model.fit(X, y)

9 frames
[/usr/lib/python3.10/urllib/request.py](https://localhost:8080/#) in http_error_default(self, req, fp, code, msg, hdrs)
    641 class HTTPDefaultErrorHandler(BaseHandler):
    642     def http_error_default(self, req, fp, code, msg, hdrs):
--> 643         raise HTTPError(req.full_url, code, msg, hdrs, fp)
    644 
    645 class HTTPRedirectHandler(BaseHandler):

HTTPError: HTTP Error 403: Forbidden
```
