### ISSUE TITLE
shap.DeepExplainer Error on LSM :  'TFDeep' object has no attribute 'between_tensors' Exception encountered when calling layer "lstm" " 

### ISSUE THREAD

**Issue by technqvi** [shap/shap#2808]
Hi

I use LSTM to  predict  time series but , face error , the last part is my source code
**This is my code to use DeepExplainer Function, it is very simple.**
```
import shap
# Use the training data for deep explainer => can use fewer instances
explainer_ = shap.DeepExplainer(model, x_train)
shap_values_ = explainer_.shap_values(x_test)

```

**This is given error information.How to fix it?**

```
`tf.keras.backend.set_learning_phase` is deprecated and will be removed after 2020-10-11. To update it, simply pass a True/False value to the `training` argument of the `__call__` method of your layer or model.
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
Input In [33], in <cell line: 1>()
----> 1 shap_values_ = explainer_.shap_values(x_test)

File D:\ProgramData\Anaconda3\envs\ml-ai\lib\site-packages\shap\explainers\_deep\__init__.py:124, in Deep.shap_values(self, X, ranked_outputs, output_rank_order, check_additivity)
     90 def shap_values(self, X, ranked_outputs=None, output_rank_order='max', check_additivity=True):
     91     """ Return approximate SHAP values for the model applied to the data given by X.
     92 
     93     Parameters
   (...)
    122         were chosen as "top".
    123     """
--> 124     return self.explainer.shap_values(X, ranked_outputs, output_rank_order, check_additivity=check_additivity)

File D:\ProgramData\Anaconda3\envs\ml-ai\lib\site-packages\shap\explainers\_deep\deep_tf.py:312, in TFDeep.shap_values(self, X, ranked_outputs, output_rank_order, check_additivity)
    310 # run attribution computation graph
    311 feature_ind = model_output_ranks[j,i]
--> 312 sample_phis = self.run(self.phi_symbolic(feature_ind), self.model_inputs, joint_input)
    314 # assign the attributions to the right part of the output arrays
    315 for l in range(len(X)):

File D:\ProgramData\Anaconda3\envs\ml-ai\lib\site-packages\shap\explainers\_deep\deep_tf.py:372, in TFDeep.run(self, out, model_inputs, X)
    369         tf_execute.record_gradient = tf_backprop.record_gradient
    371     return final_out
--> 372 return self.execute_with_overridden_gradients(anon)

File D:\ProgramData\Anaconda3\envs\ml-ai\lib\site-packages\shap\explainers\_deep\deep_tf.py:408, in TFDeep.execute_with_overridden_gradients(self, f)
    406 # define the computation graph for the attribution values using a custom gradient-like computation
    407 try:
--> 408     out = f()
    409 finally:
    410     # reinstate the backpropagatable check
    411     if hasattr(tf_gradients_impl, "_IsBackpropagatable"):

File D:\ProgramData\Anaconda3\envs\ml-ai\lib\site-packages\shap\explainers\_deep\deep_tf.py:365, in TFDeep.run.<locals>.anon()
    363     v = tf.constant(data, dtype=self.model_inputs[i].dtype)
    364     inputs.append(v)
--> 365 final_out = out(inputs)
    366 try:
    367     tf_execute.record_gradient = tf_backprop._record_gradient

File D:\ProgramData\Anaconda3\envs\ml-ai\lib\site-packages\tensorflow\python\util\traceback_utils.py:153, in filter_traceback.<locals>.error_handler(*args, **kwargs)
    151 except Exception as e:
    152   filtered_tb = _process_traceback_frames(e.__traceback__)
--> 153   raise e.with_traceback(filtered_tb) from None
    154 finally:
    155   del filtered_tb

File C:\Users\ADMINI~1\AppData\Local\Temp\2\__autograph_generated_filer893dmpf.py:16, in outer_factory.<locals>.inner_factory.<locals>.tf__grad_graph(shap_rAnD)
     14 with ag__.ld(tf).GradientTape(watch_accessed_variables=False) as tape:
     15     ag__.converted_call(ag__.ld(tape).watch, (ag__.ld(shap_rAnD),), None, fscope)
---> 16     out = ag__.converted_call(ag__.ld(self).model, (ag__.ld(shap_rAnD),), None, fscope)
     18     def get_state():
     19         return (out,)

File D:\ProgramData\Anaconda3\envs\ml-ai\lib\site-packages\keras\utils\traceback_utils.py:70, in filter_traceback.<locals>.error_handler(*args, **kwargs)
     67     filtered_tb = _process_traceback_frames(e.__traceback__)
     68     # To get the full stack trace, call:
     69     # `tf.debugging.disable_traceback_filtering()`
---> 70     raise e.with_traceback(filtered_tb) from None
     71 finally:
     72     del filtered_tb

File D:\ProgramData\Anaconda3\envs\ml-ai\lib\site-packages\shap\explainers\_deep\deep_tf.py:378, in TFDeep.custom_grad(self, op, *grads)
    375 """ Passes a gradient op creation request to the correct handler.
    376 """
    377 type_name = op.type[5:] if op.type.startswith("shap_") else op.type
--> 378 out = op_handlers[type_name](self, op, *grads) # we cut off the shap_ prefex before the lookup
    379 return out

File D:\ProgramData\Anaconda3\envs\ml-ai\lib\site-packages\shap\explainers\_deep\deep_tf.py:667, in linearity_with_excluded.<locals>.handler(explainer, op, *grads)
    666 def handler(explainer, op, *grads):
--> 667     return linearity_with_excluded_handler(input_inds, explainer, op, *grads)

File D:\ProgramData\Anaconda3\envs\ml-ai\lib\site-packages\shap\explainers\_deep\deep_tf.py:674, in linearity_with_excluded_handler(input_inds, explainer, op, *grads)
    672 for i in range(len(op.inputs)):
    673     if i in input_inds or i - len(op.inputs) in input_inds:
--> 674         assert not explainer._variable_inputs(op)[i], str(i) + "th input to " + op.name + " cannot vary!"
    675 if op.type.startswith("shap_"):
    676     op.type = op.type[5:]

File D:\ProgramData\Anaconda3\envs\ml-ai\lib\site-packages\shap\explainers\_deep\deep_tf.py:224, in TFDeep._variable_inputs(self, op)
    222     out = np.zeros(len(op.inputs), dtype=np.bool)
    223     for i,t in enumerate(op.inputs):
--> 224         out[i] = t.name in self.between_tensors
    225     self._vinputs[op] = out
    226 return self._vinputs[op]

AttributeError: in user code:

    File "D:\ProgramData\Anaconda3\envs\ml-ai\lib\site-packages\shap\explainers\_deep\deep_tf.py", line 247, in grad_graph  *
        out = self.model(shap_rAnD)
    File "D:\ProgramData\Anaconda3\envs\ml-ai\lib\site-packages\keras\utils\traceback_utils.py", line 70, in error_handler  **
        raise e.with_traceback(filtered_tb) from None
    File "D:\ProgramData\Anaconda3\envs\ml-ai\lib\site-packages\shap\explainers\_deep\deep_tf.py", line 378, in custom_grad
        out = op_handlers[type_name](self, op, *grads) # we cut off the shap_ prefex before the lookup
    File "D:\ProgramData\Anaconda3\envs\ml-ai\lib\site-packages\shap\explainers\_deep\deep_tf.py", line 667, in handler
        return linearity_with_excluded_handler(input_inds, explainer, op, *grads)
    File "D:\ProgramData\Anaconda3\envs\ml-ai\lib\site-packages\shap\explainers\_deep\deep_tf.py", line 674, in linearity_with_excluded_handler
        assert not explainer._variable_inputs(op)[i], str(i) + "th input to " + op.name + " cannot vary!"
    File "D:\ProgramData\Anaconda3\envs\ml-ai\lib\site-packages\shap\explainers\_deep\deep_tf.py", line 224, in _variable_inputs
        out[i] = t.name in self.between_tensors

    AttributeError: Exception encountered when calling layer "lstm" "                 f"(type LSTM).
    
    'TFDeep' object has no attribute 'between_tensors'
    
    Call arguments received by layer "lstm" "                 f"(type LSTM):
      • inputs=tf.Tensor(shape=(4184, 44, 4), dtype=float32)
      • mask=None
      • training=False
      • initial_state=None



```

I have 4 features and price is the target value. and the sequence to look back is 44 
the below show the shape of both train and test data
x_train.shape, y_train.shape=(2092, 44, 4) (2092,)   and x_test.shape, y_test.shape= (534, 44,4) (534,)

**_this is model architecture as code below_**
```
model = Sequential()

n_neurons = x_train.shape[1] * x_train.shape[2]
print(n_neurons, x_train.shape[1], x_train.shape[2])

model.add(LSTM(n_neurons, return_sequences=False, input_shape=(x_train.shape[1], x_train.shape[2])))
model.add(Dense(1))

model.compile(optimizer='adam',loss='mean_squared_error')


history = model.fit(x_train, y_train, 
                        batch_size=batch_size, 
                        epochs=epochs,shuffle=False,
                        validation_data=(x_test, y_test)
                       )

```

<img width="405" alt="image" src="https://user-images.githubusercontent.com/38780060/208466227-183a4ce8-45b3-486a-87ef-5c5254ae89ac.png">

**Comment by uebenes** [comment]
I can confirm, that I have the same problem with Tensorflow 2.8 and SHAP 0.41.0
The problem only occurs with LSTM Layers - with Dense Layers the DeepExplainer works fine.

**Comment by technqvi** [comment]
> I can confirm, that I have the same problem with Tensorflow 2.8 and SHAP 0.41.0 The problem only occurs with LSTM Layers - with Dense Layers the DeepExplainer works fine.


Yes , totally agree with you.  

### **_It seems that Shap  can not apply to LSTM (Time series)_** 

**On the other hand,I try it on MLP , it works so well as figure below.  
Apart from that  ,I ask this question on [https://stackoverflow.com/questions/74858635/shap-deepexplainer-error-tfdeep-object-has-no-attribute-between-tensors-ex
](https://stackoverflow.com/questions/74858635/shap-deepexplainer-error-tfdeep-object-has-no-attribute-between-tensors-ex
)    , So far nobody can fix my issue.

what other ways can we use to explain LSTM model?**
![image](https://user-images.githubusercontent.com/38780060/208904909-9d2fa794-9853-408c-941b-42396e5b6ab1.png)

**Comment by CesarPereiraa** [comment]
I ran into the same problem trying to use shap and lstm. 
Has anyone found a solution in order to get the importance of features?

**Comment by gerardkr** [comment]
I also ran into this same problem.  I get this error for both LSTM and GRU models.  It occurs in 
```
 File ".../python3.9/site-packages/shap/explainers/_deep/deep_tf.py", line 224, in _variable_inputs
        out[i] = t.name in self.between_tensors
 ```

I've spent a number of hours trying to figure out what's going wrong, but have only partially figured out a few things. 
- `self.between_tensors` is a property of the object, but it doesn't exist when `_variable_inputs` asks for it. 
- The only place `between_tensors` is defined is in method `_init_between_tensors`
- I set a breakpoint on `_init_between_tensors`, but it is never called. 
- It is apparently looking for tensors defined between model input and output.  LSTM and GRU models must not have the kind of contents SHAP is looking for (but I don't understand exactly what that is).

**Comment by technqvi** [comment]
All of us ran into the same error,  but it seems like we have not gotten any response from the owner to tell us the way out of this issue.

If the owner has acknowledged, inform me what is going on, if there is no solution any longer we will close this question.

**Comment by nagarindkx** [comment]
> I also ran into this same problem. I get this error for both LSTM and GRU models. It occurs in
> 
> ```
>  File ".../python3.9/site-packages/shap/explainers/_deep/deep_tf.py", line 224, in _variable_inputs
>         out[i] = t.name in self.between_tensors
> ```
> 
> I've spent a number of hours trying to figure out what's going wrong, but have only partially figured out a few things.
> 
> * `self.between_tensors` is a property of the object, but it doesn't exist when `_variable_inputs` asks for it.
> * The only place `between_tensors` is defined is in method `_init_between_tensors`
> * I set a breakpoint on `_init_between_tensors`, but it is never called.
> * It is apparently looking for tensors defined between model input and output.  LSTM and GRU models must not have the kind of contents SHAP is looking for (but I don't understand exactly what that is).

I have the trained model of Dense, Conv1d, RNN, LSTM, GRU
to test with timeseries data of shape 
(1435, 6 ,13)
(1435, 12 ,13)
(1435, 48 ,13)
(1435, 72 ,13)

with 
```
import shap

shap.initjs()
explainer = shap.DeepExplainer(model, np.array(bg))
shap_values=explainer.shap_values(np.array(bg))
expected_value=explainer.expected_value
```

I found that,

|data shape|Dense|Conv1d|RNN|LSTM|GRU|
|-|-|-|-|-|-|
|(1435, 6 ,13)|:white_check_mark:|:white_check_mark:|:white_check_mark:|:x:|:white_check_mark:|
|(1435, 12 ,13)|:white_check_mark:|:white_check_mark:|:white_check_mark:|:x:|:white_check_mark:|
|(1435, 48 ,13)|:white_check_mark:|:white_check_mark:|:x:|:white_check_mark:|:x:|
|(1435, 72 ,13)|:white_check_mark:|:white_check_mark:|:white_check_mark:|:x:|:x:|

Hmmmm, randomly error.

**Comment by nagarindkx** [comment]
Well, I've tried to ask chatGPT to solve the problem, it said that 'Without more information about where this attribute is being used and in what context, it's difficult to provide a more detailed explanation.'

Poor, chatGPT :-)

**Comment by gerardkr** [comment]
Any updates or progress?

**Comment by kdsharmaai** [comment]
Issue still persist,

`AttributeError: Exception encountered when calling layer 'forward_lstm' (type LSTM).
 'TFDeep' object has no attribute 'between_tensors'`

**Comment by squidcrash** [comment]
Have seen the same with GRU after a concat layer that produces this shape.

```
inputs=tf.Tensor(shape=(172, 2, 227), dtype=float32)
      • mask=None
      • training=False
      • initial_state=None
```

**Comment by CatherineHao** [comment]
I ran into the same error with LSTM.

AttributeError: Exception encountered when calling layer 'lstm' (type LSTM).
    Call arguments received by layer 'lstm' (type LSTM):
      • inputs=tf.Tensor(shape=(200, 720, 1), dtype=float32)
      • mask=None
      • training=False
      • initial_state=None

**Comment by makovez** [comment]
`tf.compat.v1.disable_v2_behavior() `adding this line after import tensorflow seems solving the issue, but it only supports cpu. Otherwise this library seems helpful too https://github.com/feedzai/timeshap, but still need to try it.

**Comment by nagarindkx** [comment]
Finally, I have to do it by:

Using another Docker container with TensorFlow 1.14.
Compiling a new model and training it with TensorFlow 1.14.
Then, SHAP will work fine.
I think SHAP has already been discontinued.

**Comment by AMasetti** [comment]
Thank you @makovez the `tf.compat.v1.disable_v2_behavior()` after import solved the issue in my case!

**Comment by jintiandefanzhenhaochi** [comment]
I encountered the same problem in the lstm layer. I see that when obtaining **shap _ values**, a related article uses `shap_values = explainer ( data ), `and some articles use `shap_values=explainer.shap _ values ( data )`, and these two will produce different errors.
For the first, this error will occur`'DeepExplainer' object has no attribute 'masker'`
For the second, this error will occur.`AttributeError: Exception encountered when calling layer "lstm1" (type LSTM). 'TFDeep' object has no attribute 'between_tensors'`
Through the information I consulted on the Internet, I found that the first type of error probability is due to the input dimension problem. The SHAP interpreter is more expected to have a two-dimensional input, like this `( batchsize, input ),` and the lstm layer is often a three-dimensional input, such as` ( batchsize, timesteps, input _ dim ).`
The solution I personally think of at present is to use the first method, that is `shap_values = explainer ( data ),`. Then change the input dimension, you can refer to this article, it is helpful for me。https://zhuanlan.zhihu.com/p/338526488

**Comment by jintiandefanzhenhaochi** [comment]
> Finally, I have to do it by:
> 
> Using another Docker container with TensorFlow 1.14. Compiling a new model and training it with TensorFlow 1.14. Then, SHAP will work fine. I think SHAP has already been discontinued.

Hello, I tried to use tf1.14 to load the trained model, however, there is the question"Unknown Layer:Functional". Then I found the question need to upgrade the tf1.14 to tf2.3. I feel sad.
Then I tried to compiling the model and train it with tf1.14, the new question is that cudnnlstm can't accelerate, the network will use gnu to instead lstm.

**Comment by CloseChoice** [comment]
related to #3344

**Comment by nickparative** [comment]
> `tf.compat.v1.disable_v2_behavior() `adding this line after import tensorflow seems solving the issue, but it only supports cpu. Otherwise this library seems helpful too https://github.com/feedzai/timeshap, but still need to try it.

Has anyone had luck with timeshap? When I went to follow the timeshap tutorial I was not able to get the package to run correctly, however I am using a sliding window numpy array for my data. 

Also I trained my model using `tf.compat.v1.disable_v2_behavior()` and got a model trained, but running DeepExplainer triggers errors.

**Comment by clash-ira23** [comment]
> > I also ran into this same problem. I get this error for both LSTM and GRU models. It occurs in
> > ```
> >  File ".../python3.9/site-packages/shap/explainers/_deep/deep_tf.py", line 224, in _variable_inputs
> >         out[i] = t.name in self.between_tensors
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > I've spent a number of hours trying to figure out what's going wrong, but have only partially figured out a few things.
> > 
> > * `self.between_tensors` is a property of the object, but it doesn't exist when `_variable_inputs` asks for it.
> > * The only place `between_tensors` is defined is in method `_init_between_tensors`
> > * I set a breakpoint on `_init_between_tensors`, but it is never called.
> > * It is apparently looking for tensors defined between model input and output.  LSTM and GRU models must not have the kind of contents SHAP is looking for (but I don't understand exactly what that is).
> 
> I have the trained model of Dense, Conv1d, RNN, LSTM, GRU to test with timeseries data of shape (1435, 6 ,13) (1435, 12 ,13) (1435, 48 ,13) (1435, 72 ,13)
> 
> with
> 
> ```
> import shap
> 
> shap.initjs()
> explainer = shap.DeepExplainer(model, np.array(bg))
> shap_values=explainer.shap_values(np.array(bg))
> expected_value=explainer.expected_value
> ```
> 
> I found that,
> 
> data shape	Dense	Conv1d	RNN	LSTM	GRU
> (1435, 6 ,13)	✅	✅	✅	❌	✅
> (1435, 12 ,13)	✅	✅	✅	❌	✅
> (1435, 48 ,13)	✅	✅	❌	✅	❌
> (1435, 72 ,13)	✅	✅	✅	❌	❌
> Hmmmm, randomly error.





https://pythondev.space/questions/i-cannot-find-the-shape-attribute-for-a-list-attributeerror-list-object-does-not-have-an-attribute-shape
