### ISSUE TITLE
AssertionError: The SHAP explanations do not sum up to the model's output!

### ISSUE THREAD

**Issue by Danish366** [shap/shap#3363]
### Issue Description

Hi,

I was trying to use this amazing `shap` library with my Deep Learning model (Regression Task, input is 2D array), however I encountered the following error:

```
AssertionError: The SHAP explanations do not sum up to the model's output! This is either because of a rounding error or because an operator in your computation graph was not fully supported. If the sum difference of %f is significant compared to the scale of your model outputs, please post as a github issue, with a reproducible example so we can debug it. Used framework: tensorflow - Max. diff: 1607.4127197265625 - Tolerance: 0.01.
```

### Minimal Reproducible Example

```python
import shap

print("SHAP version is:", shap.__version__)
print("Tensorflow version is:", tf.__version__)

background = train_points[np.random.choice(train_points.shape[0], 100, replace=False), :]

shap.initjs()

dl_explainer = shap.DeepExplainer(model, background)
dl_shap_values = dl_explainer.shap_values(test_points)
```

### Traceback

```shell
SHAP version is: 0.43.0
Tensorflow version is: 2.10.1

---------------------------------------------------------------------------
AssertionError                            Traceback (most recent call last)
Cell In [15], line 26
     13 # dl_explainer = shap.DeepExplainer(model_dl, pd.DataFrame(train_X_norm, columns=var_col_names))
     14 # dl_shap_values = dl_explainer.shap_values(pd.DataFrame(test_X_norm, columns=var_col_names))
     15 
   (...)
     21 #                                   background.reshape((background.shape[0], 1, background.shape[1])))
     22 # dl_shap_values = dl_explainer.shap_values(test_X_norm.reshape((test_X_norm.shape[0], 1, test_X_norm.shape[1])))
     24 dl_explainer = shap.DeepExplainer(model,
     25                                   background)
---> 26 dl_shap_values = dl_explainer.shap_values(test_points)
     28 dl_shap_values.shape

File ~\AppData\Local\Programs\Python\Python310\lib\site-packages\shap\explainers\_deep\__init__.py:125, in DeepExplainer.shap_values(self, X, ranked_outputs, output_rank_order, check_additivity)
     91 def shap_values(self, X, ranked_outputs=None, output_rank_order='max', check_additivity=True):
     92     """ Return approximate SHAP values for the model applied to the data given by X.
     93 
     94     Parameters
   (...)
    123         were chosen as "top".
    124     """
--> 125     return self.explainer.shap_values(X, ranked_outputs, output_rank_order, check_additivity=check_additivity)

File ~\AppData\Local\Programs\Python\Python310\lib\site-packages\shap\explainers\_deep\deep_tf.py:327, in TFDeep.shap_values(self, X, ranked_outputs, output_rank_order, check_additivity)
    324     else:
    325         model_output = self.model(X)
--> 327     _check_additivity(self, model_output, output_phis)
    329 if not self.multi_output:
    330     return output_phis[0]

File ~\AppData\Local\Programs\Python\Python310\lib\site-packages\shap\explainers\_deep\deep_utils.py:20, in _check_additivity(explainer, model_output_values, output_phis)
     16         diffs -= output_phis[l][i].sum(axis=tuple(range(1, output_phis[l][i].ndim)))
     18 maxdiff = np.abs(diffs).max()
---> 20 assert maxdiff < TOLERANCE, "The SHAP explanations do not sum up to the model's output! This is either because of a " \
     21                             "rounding error or because an operator in your computation graph was not fully supported. If " \
     22                             "the sum difference of %f is significant compared to the scale of your model outputs, please post " \
     23                             f"as a github issue, with a reproducible example so we can debug it. Used framework: {explainer.framework} - Max. diff: {maxdiff} - Tolerance: {TOLERANCE}"

AssertionError: The SHAP explanations do not sum up to the model's output! This is either because of a rounding error or because an operator in your computation graph was not fully supported. If the sum difference of %f is significant compared to the scale of your model outputs, please post as a github issue, with a reproducible example so we can debug it. Used framework: tensorflow - Max. diff: 1607.4127197265625 - Tolerance: 0.01
```

### Bug report checklist

- [X] I have checked that this issue has not already been reported.
- [X] I have confirmed this bug exists on the [latest release](https://github.com/shap/shap/releases) of shap.
- [ ] I have confirmed this bug exists on the [master branch](https://github.com/shap/shap/blob/master/CONTRIBUTING.md#installing-from-the-master-branch) of shap.
- [ ] I'd be interested in making a PR to fix this bug

### Installed Versions

`0.43.0`

**Comment by cfyeung-dojjy** [comment]
Is your model a regression model?
I also have this issue for regression model.
I think _check_additivity is only for classification models, your can pass check_additivity=False to dl_explainer.shap_values() to skip the checking.

**Comment by CloseChoice** [comment]
Thanks for the bug report. Could you please provide a reproducible example, so that we can investigate this further. We would need a definition of the model and data.

**Comment by oegedijk** [comment]
I have another reproducible example (using the skorch wrapper):

```python
import numpy as np
import pandas as pd

from sklearn.datasets import make_classification, make_regression
import torch
from torch import nn
from skorch import NeuralNetClassifier, NeuralNetRegressor
import shap

X, y = make_regression(100, 5, n_informative=3, random_state=0)
X = X.astype(np.float32)
y = y / np.std(y)
y = y.reshape(-1, 1).astype(np.float32)

X_df = pd.DataFrame(X, columns=['col'+str(i) for i in range(X.shape[1])])

class MyModule(nn.Module):
    def __init__(self, input_units=5, num_units=5, nonlin=nn.functional.relu):
        super(MyModule, self).__init__()

        self.dense0 = nn.Linear(input_units, num_units)
        self.nonlin = nonlin
        self.dense1 = nn.Linear(num_units, num_units)
        self.output = nn.Linear(num_units, 1)

    def forward(self, X, **kwargs):
        X = self.nonlin(self.dense0(X))
        X = self.nonlin(self.dense1(X))
        X = self.output(X)
        return X

model = NeuralNetRegressor(
    MyModule,
    max_epochs=20,
    lr=0.2,
    iterator_train__shuffle=True,
)

model.fit(X_df.values, y)

shap_explainer = shap.DeepExplainer(
                    model.module_,
                    torch.tensor(shap.sample(X_df, 5).values),
                )
shap_explainer.shap_values(torch.tensor(X_df.values), check_additivity=True)
```

Outputs:

```
epoch    train_loss    valid_loss     dur
-------  ------------  ------------  ------
      1        1.0909        1.3938  0.0048
      2        0.9976        1.2962  0.0047
      3        0.9404        1.2258  0.0064
      4        0.8999        1.1571  0.0058
      5        0.8579        1.0873  0.0061
      6        0.8117        1.0083  0.0064
      7        0.7570        0.9218  0.0041
      8        0.6886        0.8152  0.0040
      9        0.6015        0.6841  0.0074
     10        0.5074        0.5461  0.0062
     11        0.4128        0.4162  0.0097
     12        0.3221        0.3203  0.0057
     13        0.2491        0.2491  0.0058
     14        0.1953        0.1997  0.0043
     15        0.1576        0.1644  0.0034
     16        0.1294        0.1399  0.0041
     17        0.1098        0.1220  0.0084
     18        0.0959        0.1100  0.0043
     19        0.0858        0.1009  0.0053
     20        0.0780        0.0954  0.0052
---------------------------------------------------------------------------
AssertionError                            Traceback (most recent call last)
Cell In[32], line 47
     41 model.fit(X_df.values, y)
     43 shap_explainer = shap.DeepExplainer(
     44                     model.module_,
     45                     torch.tensor(shap.sample(X_df, 5).values),
     46                 )
---> 47 shap_explainer.shap_values(torch.tensor(X_df.values), check_additivity=True)

File ~/projects/explainerdashboard/venv/lib/python3.10/site-packages/shap/explainers/_deep/__init__.py:125, in DeepExplainer.shap_values(self, X, ranked_outputs, output_rank_order, check_additivity)
     91 def shap_values(self, X, ranked_outputs=None, output_rank_order='max', check_additivity=True):
     92     """ Return approximate SHAP values for the model applied to the data given by X.
     93 
     94     Parameters
   (...)
    123         were chosen as "top".
    124     """
--> 125     return self.explainer.shap_values(X, ranked_outputs, output_rank_order, check_additivity=check_additivity)

File ~/projects/explainerdashboard/venv/lib/python3.10/site-packages/shap/explainers/_deep/deep_pytorch.py:219, in PyTorchDeep.shap_values(self, X, ranked_outputs, output_rank_order, check_additivity)
    216         with torch.no_grad():
    217             model_output_values = self.model(*X)
--> 219     _check_additivity(self, model_output_values.cpu(), output_phis)
    221 if not self.multi_output:
    222     return output_phis[0]

File ~/projects/explainerdashboard/venv/lib/python3.10/site-packages/shap/explainers/_deep/deep_utils.py:20, in _check_additivity(explainer, model_output_values, output_phis)
     16         diffs -= output_phis[t][i].sum(axis=tuple(range(1, output_phis[t][i].ndim)))
     18 maxdiff = np.abs(diffs).max()
---> 20 assert maxdiff < TOLERANCE, "The SHAP explanations do not sum up to the model's output! This is either because of a " \
     21                             "rounding error or because an operator in your computation graph was not fully supported. If " \
     22                             "the sum difference of %f is significant compared to the scale of your model outputs, please post " \
     23                             f"as a github issue, with a reproducible example so we can debug it. Used framework: {explainer.framework} - Max. diff: {maxdiff} - Tolerance: {TOLERANCE}"

AssertionError: The SHAP explanations do not sum up to the model's output! This is either because of a rounding error or because an operator in your computation graph was not fully supported. If the sum difference of %f is significant compared to the scale of your model outputs, please post as a github issue, with a reproducible example so we can debug it. Used framework: pytorch - Max. diff: 1.2907098717987537 - Tolerance: 0.01
```

**Comment by barkincavdaroglu** [comment]
Same problem with a GCN model and Planetoid dataset. The max. diff is ~0.13. It's a node classification problem with Softmax (log softmax resulted in a much larger difference).

**Comment by MatthijsdeJ** [comment]
I've encountered this problem too. The GradientExplainer or PermutationExplainer do work well.

**Comment by armlesscoder98** [comment]
Did you guys find a solution for that? Because I'm also having trouble with the same issue!

**Comment by rajeshkalakoti** [comment]
I encountered this problem as well. Did anyone find a solution?

```py
Error executing job with overrides: []
Traceback (most recent call last):
  File "/illukas/home/rkalak/xai_evaluation/project/explainableFedLearnIoT/main_fed_shap.py", line 165, in main
    c_shap_values, s_shap_values = compute_shap_values(
  File "/illukas/home/rkalak/xai_evaluation/project/explainableFedLearnIoT/main_fed_shap.py", line 101, in compute_shap_values
    c_shap_values = get_shap_values(model=client_model, train_data=tr_data, val_data=validation_sample,batch_size=batch_size)
  File "/illukas/home/rkalak/xai_evaluation/project/explainableFedLearnIoT/main_fed_shap.py", line 59, in get_shap_values
    shap_values_list = [[] for _ in range(len(explainer.shap_values(val_data[:1])))]
  File "/illukas/home/rkalak/xai_evaluation/project/explainableFedLearnIoT/env/lib/python3.9/site-packages/shap/explainers/_deep/__init__.py", line 125, in shap_values
    return self.explainer.shap_values(X, ranked_outputs, output_rank_order, check_additivity=check_additivity)
  File "/illukas/home/rkalak/xai_evaluation/project/explainableFedLearnIoT/env/lib/python3.9/site-packages/shap/explainers/_deep/deep_pytorch.py", line 219, in shap_values
    _check_additivity(self, model_output_values.cpu(), output_phis)
  File "/illukas/home/rkalak/xai_evaluation/project/explainableFedLearnIoT/env/lib/python3.9/site-packages/shap/explainers/_deep/deep_utils.py", line 20, in _check_additivity
    assert maxdiff < TOLERANCE, "The SHAP explanations do not sum up to the model's output! This is either because of a " \
AssertionError: The SHAP explanations do not sum up to the model's output! This is either because of a rounding error or because an operator in your computation graph was not fully supported. If the sum difference of %f is significant compared to the scale of your model outputs, please post as a github issue, with a reproducible example so we can debug it. Used framework: pytorch - Max. diff: 405.76129573059734 - Tolerance: 0.01

Set the environment variable HYDRA_FULL_ERROR=1 for a complete stack trace.
```
