### ISSUE TITLE
BUG: Incorrect reshape behavior in shap/plots/_image.py, v0.43.0

### ISSUE THREAD

**Issue by cfyeung-dojjy** [shap/shap#3366]
### Issue Description

In  shap/plots/_image.py
```   
95  if labels is not None:
96       if isinstance(labels, list):
97            labels = np.array(labels).reshape(1, -1)```

```
If the passed in labels is a list, this code will destroy the structure, making it a 1-d array, leading to the following error message
```
Traceback (most recent call last):
  File "/mnt/azureml/cr/j/1e7bc96644ab43af9d312340b05c2fda/exe/wd/scripts/train_image_to_pom_model.py", line 421, in <module>
    main()
  File "/mnt/azureml/cr/j/1e7bc96644ab43af9d312340b05c2fda/exe/wd/scripts/train_image_to_pom_model.py", line 395, in main
    plot_shap_deep_explainer_image(pom2d_pred, train_dataset)
  File "/mnt/azureml/cr/j/1e7bc96644ab43af9d312340b05c2fda/exe/wd/scripts/train_image_to_pom_model.py", line 293, in plot_shap_deep_explainer_image
    shap.image_plot(shap_values=[pom_explanations.reshape((32, size, size, 1)) for pom_explanations, height_explanations in shap_values],
  File "/opt/miniconda/envs/phm/lib/python3.10/site-packages/shap/plots/_image.py", line 166, in image
    axes[row, i + 1].set_title(labels[row, i], **label_kwargs)
IndexError: index 1 is out of bounds for axis 0 with size 1

```
work-around:
convert labels to np.array() manually before passing in.

### Minimal Reproducible Example

```python
passing labels as a 2d list to shap.image_plot()
```

### Bug report checklist

- [X] I have checked that this issue has not already been reported.
- [X] I have confirmed this bug exists on the [latest release](https://github.com/shap/shap/releases) of shap.
- [ ] I have confirmed this bug exists on the [master branch](https://github.com/shap/shap/blob/master/CONTRIBUTING.md#installing-from-the-master-branch) of shap.
- [ ] I'd be interested in making a PR to fix this bug

### Installed Versions

0.43.0

**Comment by CloseChoice** [comment]
Thanks for the bug report and the analysis. Could you help us with a reproducible example?

**Comment by cfyeung-dojjy** [comment]
Sorry but the code is confidential, while it is caused by the label reshape
converting the input labels list
e.g.
```
labels=[
    ['a', 'b', 'c'],
    ['a', 'b', 'c'],
]
```
into
```
np.array(['a', 'b', 'c', 'a', b', 'c'])
```
distorting the array

**Comment by CloseChoice** [comment]
I see but just any reproducible example with dummy data would help us. Otherwise we would need to reverse engineer the problem which takes a lot of time and might cause this bug to be de-prioritized.

**Comment by cfyeung-dojjy** [comment]
Thank you for the reply, I will try constructing a dummy example when I have time.
Meanwhile I will leave this issue here so that when someone encountered the same error, they will know it is related to `labels`, instead of the input data.
I wasted a day trying to debug this lol.

**Comment by cfyeung-dojjy** [comment]
Reproduction code, using shap==0.43.0
```
    train_loader, val_loader = my_cls.init_dataloader(train_dataset, val_split=0.2)
    # training data
    train_x, _ = next(iter(train_loader))
    train_imgs = train_x[0].to(device)
    train_feature_2 = train_x[1].to(device).float()
    e = shap.DeepExplainer(my_cls.model, [train_imgs, train_feature_2 ])

    shap_values: list[list, list] = e.shap_values([train_imgs, train_feature_2 ], check_additivity=False)
    # shap_values[0][0].shape = (32, 1, 400, 400)
    # ! MUST reshape to (32, size, size, 1) else the code will break
    # https://shap-lrjball.readthedocs.io/en/latest/generated/shap.image_plot.html
    shap.image_plot(shap_values=[explanations.reshape(32, size, size, 1) for explanations, explanations_feature_2 in shap_values],
                    pixel_values=train_imgs.cpu().numpy().reshape(32, size, size, 1),
                    width=300, labels=np.array([my_cls.targets]*32), # The structure of labels will get destroyed by the image_plot function if it is a list, convert to np.array before passing in
                    show=False)  # Do not call plt.show() before function return
```
**labels** passed into the function is a list of length 32, with sub-lists of length 13

In **shap.image_plot()**, if the **labels** passed into the function is a list, it will convert it to a np.array() while reshaping it to a 1-d array. 
(32, 13) -> ( , 32*13)

While in later part of the function, it calls a 2-d slice of the label matrix to retrieve a label name to be put into plt-subplot, causing an IndexError.
