### ISSUE TITLE
BUG: Error while installing shap into pypy's docker image

### ISSUE THREAD

**Issue by iamshreeram** [shap/shap#3428]
### Issue Description

We encountered an error during the installation of the shap package in the pypy:latest docker image. The error message states: 
```
 RuntimeError: Could not find a `llvm-config` binary. There are a number of reasons this could occur, please see: https://llvmlite.readthedocs.io/en/latest/admin-guide/install.html#using-pip
```
Since the pypy:latest image employs debian aarch64, the installation of llvmlite was unsuccessful. Could you kindly provide instructions on how to install **shap** in pypy:latest?

### Minimal Reproducible Example

```python
1. download docker `pypy:latest`
2. run the image
3. install shap via pip `pip3 install shap`
4. Error encountered
```

### Traceback

```shell
numba/_dispatcher.cpp:670:21: warning: control reaches end of non-void function [-Wreturn-type]
        670 |     trace_info.code = NULL; // not initialized
            |                     ^
      error: command '/usr/bin/gcc' failed with exit code 1
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for numba
  Running setup.py clean for numba
  Building wheel for llvmlite (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [11 lines of output]
      running bdist_wheel
      /opt/pypy/bin/pypy3 /tmp/pip-install-7gusp46v/llvmlite_9f2c3a172e64488c9176af17d4f6890c/ffi/build.py
      LLVM version... Traceback (most recent call last):
        File "/tmp/pip-install-7gusp46v/llvmlite_9f2c3a172e64488c9176af17d4f6890c/ffi/build.py", line 228, in <module>
          main()
        File "/tmp/pip-install-7gusp46v/llvmlite_9f2c3a172e64488c9176af17d4f6890c/ffi/build.py", line 218, in main
          main_posix('linux', '.so')
        File "/tmp/pip-install-7gusp46v/llvmlite_9f2c3a172e64488c9176af17d4f6890c/ffi/build.py", line 135, in main_posix
          raise RuntimeError(msg) from None
      RuntimeError: Could not find a `llvm-config` binary. There are a number of reasons this could occur, please see: https://llvmlite.readthedocs.io/en/latest/admin-guide/install.html#using-pip for help.
      error: command '/opt/pypy/bin/pypy3' failed with exit code 1
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for llvmlite
  Running setup.py clean for llvmlite
Successfully built shap
Failed to build numba llvmlite
Installing collected packages: tqdm, slicer, packaging, llvmlite, cloudpickle, numba, shap
  Running setup.py install for llvmlite ... error
  error: subprocess-exited-with-error

  × Running setup.py install for llvmlite did not run successfully.
  │ exit code: 1
  ╰─> [16 lines of output]
      running install
      /opt/pypy/lib/pypy3.10/site-packages/setuptools/command/install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
        warnings.warn(
      running build
      got version from file /tmp/pip-install-7gusp46v/llvmlite_9f2c3a172e64488c9176af17d4f6890c/llvmlite/_version.py {'version': '0.41.1', 'full': '42db9b74c8e8ca012cb4394cbf941f2f9e4ae12b'}
      running build_ext
      /opt/pypy/bin/pypy3 /tmp/pip-install-7gusp46v/llvmlite_9f2c3a172e64488c9176af17d4f6890c/ffi/build.py
      LLVM version... Traceback (most recent call last):
        File "/tmp/pip-install-7gusp46v/llvmlite_9f2c3a172e64488c9176af17d4f6890c/ffi/build.py", line 228, in <module>
          main()
        File "/tmp/pip-install-7gusp46v/llvmlite_9f2c3a172e64488c9176af17d4f6890c/ffi/build.py", line 218, in main
          main_posix('linux', '.so')
        File "/tmp/pip-install-7gusp46v/llvmlite_9f2c3a172e64488c9176af17d4f6890c/ffi/build.py", line 135, in main_posix
          raise RuntimeError(msg) from None
      RuntimeError: Could not find a `llvm-config` binary. There are a number of reasons this could occur, please see: https://llvmlite.readthedocs.io/en/latest/admin-guide/install.html#using-pip for help.
      error: command '/opt/pypy/bin/pypy3' failed with exit code 1
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: legacy-install-failure

× Encountered error while trying to install package.
╰─> llvmlite
```

### Expected Behavior

Able to install shap successfully

### Bug report checklist

- [X] I have checked that this issue has not already been reported.
- [X] I have confirmed this bug exists on the [latest release](https://github.com/shap/shap/releases) of shap.
- [X] I have confirmed this bug exists on the [master branch](https://github.com/shap/shap/blob/master/CONTRIBUTING.md#installing-from-the-master-branch) of shap.
- [ ] I'd be interested in making a PR to fix this bug

### Installed Versions

latest - 0.44.0

**Comment by iamshreeram** [comment]
Hi, I have successfully installed **llvmlite-39** on my **pypy:latest** version, but it appears that numba is not compatible with pypy. Consequently, I am wondering if this means shap won't function on **pypy** either, considering its strong reliance on numba.
