### ISSUE TITLE
BUG: shap does not work with Embeddings and tf.version >= 2.4

### ISSUE THREAD

**Issue by CloseChoice** [shap/shap#3440]
### Issue Description

The deepexplainer fails with an embedding layer since this always outputs `None` (which cannot be cast to a numpy object afterwards).

PR https://github.com/shap/shap/pull/540 might point to a solution.

### Minimal Reproducible Example

```python
import tensorflow as tf
import shap
import numpy as np

input1 = tf.keras.layers.Input((10,))
emb = tf.keras.layers.Embedding(1000, 64)(input1)
output = tf.keras.layers.Dense(1)(tf.reshape(emb, (-1, 640)))

model = tf.keras.models.Model(input1, output)

input_array = np.random.randint(1000, size=(1000, 10))
model.compile('rmsprop', 'mse')

input_array = np.random.randint(1000, size=(32, 10))

input_array_ex = input_array.reshape((input_array.shape[0], input_array.shape[1], 1))
explainer = shap.DeepExplainer(model, input_array_ex[:20])

# this fails since the embedding is not supported
# their output always result in None if the NN is applied with overwritten gradients
_shap_values = explainer.shap_values(input_array_ex[-20:])
```

### Traceback

```shell
Your TensorFlow version is newer than 2.4.0 and so graph support has been removed in eager mode and some static graphs may not be supported. See PR #1483 for discussion.
`tf.keras.backend.set_learning_phase` is deprecated and will be removed after 2020-10-11. To update it, simply pass a True/False value to the `training` argument of the `__call__` method of your layer or model.
Traceback (most recent call last):
  File "C:\Users\Tobias Pitters\programming\shap\bugs\embedding.py", line 21, in <module>
    _shap_values = explainer.shap_values(input_array_ex[-20:])
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Tobias Pitters\programming\shap\shap\explainers\_deep\__init__.py", line 125, in shap_values
    return self.explainer.shap_values(X, ranked_outputs, output_rank_order, check_additivity=check_additivity)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Tobias Pitters\programming\shap\shap\explainers\_deep\deep_tf.py", line 313, in shap_values
    sample_phis = self.run(self.phi_symbolic(feature_ind), self.model_inputs, joint_input)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Tobias Pitters\programming\shap\shap\explainers\_deep\deep_tf.py", line 364, in run
    return self.execute_with_overridden_gradients(anon)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Tobias Pitters\programming\shap\shap\explainers\_deep\deep_tf.py", line 416, in execute_with_overridden_gradients
    return [v.numpy() for v in out]
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Tobias Pitters\programming\shap\shap\explainers\_deep\deep_tf.py", line 416, in <listcomp>
    return [v.numpy() for v in out]
            ^^^^^^^
AttributeError: 'NoneType' object has no attribute 'numpy'
```

### Bug report checklist

- [X] I have checked that this issue has not already been reported.
- [X] I have confirmed this bug exists on the [latest release](https://github.com/shap/shap/releases) of shap.
- [X] I have confirmed this bug exists on the [master branch](https://github.com/shap/shap/blob/master/CONTRIBUTING.md#installing-from-the-master-branch) of shap.
- [ ] I'd be interested in making a PR to fix this bug

### Installed Versions

tensorflow==2.15.0
tensorflow-estimator==2.15.0
tensorflow-intel==2.15.0
tensorflow-io-gcs-filesystem==0.31.0

**Comment by indigoplane** [comment]
hi, is there any fix or workaround for this issue

**Comment by CloseChoice** [comment]
As of now there is only a very manual way and this only works if the embedding layer is at the beginning or end of the model:
recreate another model with the same weights without the embeddings (basically cut off the embeddings) and, calculate the shap values for that and then sum up the shap values of the embeddings which should recover the values for the pre-embedding inputs.

**Comment by CloseChoice** [comment]
Something worth looking for when tackling this issue is what happend to `_isBackpropagatable`, see [this comment](https://github.com/shap/shap/blob/master/shap/explainers/_deep/deep_tf.py#L412-L413):
```python
        # In TensorFlow 1.10 they started pruning out nodes that they think can't be backpropped
        # unfortunately that includes the index of embedding layers so we disable that check here
        if hasattr(tf_gradients_impl, "_IsBackpropagatable"):
            orig_IsBackpropagatable = tf_gradients_impl._IsBackpropagatable
            tf_gradients_impl._IsBackpropagatable = lambda tensor: True
```

**Comment by indigoplane** [comment]
Thank you ! I will try this workaround
