### ISSUE TITLE
BUG: grad can be implicitly created only for scalar outputs

### ISSUE THREAD

**Issue by yaba-hun** [shap/shap#3449]
### Issue Description

I am encountering an issue while attempting to explain image data using the DeepExplainer with an FCN model. The shape of my feature data is [batch, 7, 256, 256], and the label data has a shape of [batch, 1, 256, 256]. Interestingly, during training with my custom model, everything works as expected. However, when I use the DeepExplainer for explanation, unexpected issues arise. Any insights into what might be causing this discrepancy would be greatly appreciated.

### Minimal Reproducible Example

```python
def train(model, device, train_loader, optimizer, epoch):
    model.train()
    batch_num = len(train_loader)
    criterion = nn.MSELoss()
    for batch in range(batch_num):
        feature, label, _ = train_loader()
        feature, label = feature.to(device), label.to(device)
        output = model(feature)
        optimizer.zero_grad()
        loss = criterion(output, label)
        loss.backward()
        optimizer.step()
        print('batch: ', batch, 'loss: ', loss.item())

batch = data_loader()
feature, label, _ = batch
feature, label = feature.to(device), label.to(device)
# explainer = shap.GradientExplainer(model, feature[:10])
explainer = shap.DeepExplainer(model, feature[:10])
shap_values = explainer.shap_values(feature[11:12])
shap.image_plot(shap_values, -feature)
```

### Traceback

```shell
Traceback (most recent call last):
  File "/home/admin1/Softwares/anaconda3/envs/MTL/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/admin1/Softwares/anaconda3/envs/MTL/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/admin1/.vscode-server/extensions/ms-python.python-2023.22.1/pythonFiles/lib/python/debugpy/adapter/../../debugpy/launcher/../../debugpy/__main__.py", line 39, in <module>
    cli.main()
  File "/home/admin1/.vscode-server/extensions/ms-python.python-2023.22.1/pythonFiles/lib/python/debugpy/adapter/../../debugpy/launcher/../../debugpy/../debugpy/server/cli.py", line 430, in main
    run()
  File "/home/admin1/.vscode-server/extensions/ms-python.python-2023.22.1/pythonFiles/lib/python/debugpy/adapter/../../debugpy/launcher/../../debugpy/../debugpy/server/cli.py", line 284, in run_file
    runpy.run_path(target, run_name="__main__")
  File "/home/admin1/.vscode-server/extensions/ms-python.python-2023.22.1/pythonFiles/lib/python/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_runpy.py", line 321, in run_path
    return _run_module_code(code, init_globals, run_name,
  File "/home/admin1/.vscode-server/extensions/ms-python.python-2023.22.1/pythonFiles/lib/python/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_runpy.py", line 135, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "/home/admin1/.vscode-server/extensions/ms-python.python-2023.22.1/pythonFiles/lib/python/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_runpy.py", line 124, in _run_code
    exec(code, run_globals)
  File "/home/admin1/Projects/MultiTasklearning/Codes/CircuitNet-Single/shap_test.py", line 84, in <module>
    shap_values = explainer.shap_values(feature[11:12])
  File "/home/admin1/Softwares/anaconda3/envs/MTL/lib/python3.9/site-packages/shap/explainers/_deep/__init__.py", line 125, in shap_values
    return self.explainer.shap_values(X, ranked_outputs, output_rank_order, check_additivity=check_additivity)
  File "/home/admin1/Softwares/anaconda3/envs/MTL/lib/python3.9/site-packages/shap/explainers/_deep/deep_pytorch.py", line 191, in shap_values
    sample_phis = self.gradient(feature_ind, joint_x)
  File "/home/admin1/Softwares/anaconda3/envs/MTL/lib/python3.9/site-packages/shap/explainers/_deep/deep_pytorch.py", line 125, in gradient
    grad = torch.autograd.grad(selected, x,
  File "/home/admin1/Softwares/anaconda3/envs/MTL/lib/python3.9/site-packages/torch/autograd/__init__.py", line 288, in grad
    grad_outputs_ = _make_grads(t_outputs, grad_outputs_, is_grads_batched=is_grads_batched)
  File "/home/admin1/Softwares/anaconda3/envs/MTL/lib/python3.9/site-packages/torch/autograd/__init__.py", line 88, in _make_grads
    raise RuntimeError("grad can be implicitly created only for scalar outputs")
RuntimeError: grad can be implicitly created only for scalar outputs
```

### Bug report checklist

- [X] I have checked that this issue has not already been reported.
- [X] I have confirmed this bug exists on the [latest release](https://github.com/shap/shap/releases) of shap.
- [X] I have confirmed this bug exists on the [master branch](https://github.com/shap/shap/blob/master/CONTRIBUTING.md#installing-from-the-master-branch) of shap.
- [X] I'd be interested in making a PR to fix this bug

### Installed Versions

shap 0.44.0

**Comment by CloseChoice** [comment]
Thanks for the report @yaba-hun. From the code you posted I cannot understand what is going wrong and in your example there are a few things missing for us to reproduce it. We would need the definition of the model + loading of the data to reproduce this.

**Comment by ncuxomun** [comment]
I have the same error output. I have a 1D CNN model that outputs (Batch, #Signals, #Signal Length)

**Comment by CloseChoice** [comment]
@ncuxomun Would you be so kind to provide an example that reproduces the error? Including the definition of the data and the model?

**Comment by ncuxomun** [comment]
> @ncuxomun Would you be so kind to provide an example that reproduces the error? Including the definition of the data and the model?

Please find an example as requested:

```
# pytorch relates imports
import torch
import torch.nn as nn
import torch.optim as optim

import shap
# %%
X_train = torch.randn(size=(100, 5, 30))
y_train = torch.randn(size=(100, 1, 30))

# %%
X_train = torch.FloatTensor(X_train)
y_train = torch.FloatTensor(y_train)

datasets = torch.utils.data.TensorDataset(X_train, y_train)
train_iter = torch.utils.data.DataLoader(datasets, batch_size=10, shuffle=True)
# %%
batch_size = 16
num_epochs = 200
learning_rate = 0.0001
size_hidden1 = 100
size_hidden2 = 50

# %%
class dummy_model(nn.Module):
    def __init__(self, in_c=5, out_c=1, dp_rate=0.025, lr=2e-4):
        super().__init__()
        self.model = nn.Sequential(
            nn.Conv1d(in_channels=in_c, out_channels=in_c*3, kernel_size=3, stride=1, padding=0),
            nn.ReLU(),
            nn.Dropout(dp_rate),
            nn.Conv1d(in_channels=in_c*3, out_channels=in_c*4, kernel_size=2, stride=1, padding=2),
            nn.ReLU(),
            nn.Dropout(dp_rate),
            nn.Conv1d(in_channels=in_c*4, out_channels=out_c, kernel_size=2, stride=1, padding=0),
        )

    def forward(self, input):
        return self.model(input)
    
model = dummy_model()
model.train()
# %%
criterion = nn.MSELoss(reduction='mean')

def train(model_inp, num_epochs = num_epochs):
    optimizer = torch.optim.RMSprop(model_inp.parameters(), lr=learning_rate)
    for epoch in range(num_epochs):  # loop over the dataset multiple times
        running_loss = 0.0
        for inputs, labels in train_iter:
            # forward pass
            outputs = model_inp(inputs)
            # defining loss
            loss = criterion(outputs, labels)
            # zero the parameter gradients
            optimizer.zero_grad()
            # computing gradients
            loss.backward()
            # accumulating running loss
            running_loss += loss.item()
            # updated weights based on computed gradients
            optimizer.step()
        if epoch % 20 == 0:    
            print('Epoch [%d]/[%d] running accumulative loss across all batches: %.3f' %
                  (epoch + 1, num_epochs, running_loss))
        running_loss = 0.0

# %%
      
train(model)
# %%
explainer = shap.DeepExplainer(model=model, data=X_train[:50])
shap_values = explainer.shap_values(X=X_train[:50])
```

**Comment by ThanosAthanasiadis** [comment]
Hello all. I have exactly the same issue. The output of my model is 2D images that each pixel represents the most probable class (0-5) after applying argmax. When i try to appy the deepExplainer like this '' explainer = shap.DeepExplainer(model, background[:100]) '' , i get the same error.  Has anyone found a solution yet?  Thanks

**Comment by PoorOtterBob** [comment]
I have the same error. It seems that the output of our model should be a 'scaler' ?

**Comment by anshch22** [comment]
Hi @yaba-hun,

I'm reaching out regarding a potential issue I encountered while using GradientExplainer for SHAP analysis with PyTorch. I couldn't see a fix in the latest release, but I implemented a workaround that might be helpful.

Context:

I'm using PyTorch with GradientExplainer for SHAP analysis.
I downloaded and explicitly imported the SHAP library in my notebook due to necessary code modifications.
Identified Issue:

I encountered the same error originating because of line 483 within the def gradient(self, idx, inputs) function in shap/explainers/_gradient.py (https://github.com/shap/shap/blob/master/shap/explainers/_gradient.py).

The line selected = [val for val in outputs[:, idx]] appears to be returning a list of vector values instead of scalar values, causing the error.

Proposed Fix:

To address this, I modified the line to convert the vector values to scalars using .sum() or .mean(). Here's the adjusted code:

selected = [val.sum() for val in outputs[:, idx]]

This change assumes val is a single value vector, and .sum() simplifies it to a scalar value.

This fix effectively resolved the issue in my case. I believe it could potentially benefit others facing a similar problem.
