### ISSUE TITLE
BUG: unable to use SHAP with CUDA support on Windows10/11 machine for calculating Shapley values

### ISSUE THREAD

**Issue by madakkmi** [shap/shap#3646]
### Issue Description

I am trying to install shap with CUDA support on a Windows 10 Enterprise (64bit) machine. I cloned the shap repository version 0.45.1 and built SHAP using `python -m pip install ./shap` (`python setup.py install --user` is deprecated in the newer version of `setuptools`). The installation seems to successful and I am even able to see `_cext.cp312-win_amd64.pyd` and `_cext_gpu.cp312-win_amd64.pyd` in `..\Lib\site-packages\shap`.  However when I try to use `explainer.shap_values(X,y),` I get the error "cuda extension was not built during install!"

### Minimal Reproducible Example

```python
On a Windows 10 enterprise machine
----------------------------------

1. Install the latest version of Visual Studio  (version 17.9.6) with "Desktop development with C++ workload".
2. Install the latest version of CMake (version 3.29.2)
3. Install the latest version of CUDA Toolkit (version 12.4.1)
4. Include the path of cl.exe (host x64, target x64) in the environment variable 'Path'
5. Create a venv environment (Python 12.0.0) 
6. Activate the environment
6. git clone https://github.com/shap/shap.git
7. python -m pip install ./shap
8. pip install xgboost
9. invoke python
10  run the following code:

import shap
from sklearn.datasets import fetch_california_housing

import xgboost as xgb

# Fetch dataset using sklearn
data = fetch_california_housing()
print(data.DESCR)
X = data.data
y = data.target

num_round = 500

param = {
    "eta": 0.05,
    "max_depth": 10,

    "tree_method": "hist",
    "device": "cuda",
}

# GPU accelerated training
dtrain = xgb.DMatrix(X, label=y, feature_names=data.feature_names)
model = xgb.train(param, dtrain, num_round)

# Compute shap values using GPU with xgboost
model.set_param({"device": "cuda"})
shap_values = model.predict(dtrain, pred_contribs=True) # this is successful and uses GPU

xplainer = shap.explainers.GPUTree(model) # this line does not throw any error
shap_values = xplainer.shap_values(X, y) # this line throws errors
```

### Traceback

```shell
>>> shap_values = C_explainer.shap_values(X, y)
cuda extension was not built during install!
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\mimi\mypy_venv\llpower_gpu_312\Lib\site-packages\shap\explainers\_gpu_tree.py", line 76, in shap_values
    assert_import("cext_gpu")
  File "C:\Users\mimi\mypy_venv\llpower_gpu_312\Lib\site-packages\shap\utils\_general.py", line 19, in assert_import
    raise e
  File "C:\Users\mimi\mypy_venv\llpower_gpu_312\Lib\site-packages\shap\explainers\_gpu_tree.py", line 13, in <module>
    from .. import _cext_gpu
ImportError: DLL load failed while importing _cext_gpu: The specified module could not be found.
```

### Expected Behavior

`shap_values = xplainer.shap_values(X, y)` should not result in any error and the variable `shap_values` will be initialized with Shapley values

### Bug report checklist

- [X] I have checked that this issue has not already been reported.
- [X] I have confirmed this bug exists on the [latest release](https://github.com/shap/shap/releases) of shap.
- [x] I have confirmed this bug exists on the [master branch](https://github.com/shap/shap/blob/master/CONTRIBUTING.md#installing-from-the-master-branch) of shap.
- [ ] I'd be interested in making a PR to fix this bug

### Installed Versions

OS: Windows 10 Enterprise
GPU: NVIDIA Quadro RTX 4000
Visual Studio  (version 17.9.6) with "Desktop development with C++ workload"
CUDA Toolkit: 12.4.1
Python: 3.12.0 (tags/v3.12.0:0fb18b0, Oct  2 2023, 13:03:39) [MSC v.1935 64 bit (AMD64)]
packaging : 24.0
pip: 23.2.1
numpy: 1.26.4
numba" 0.59.1
llvmlite: 0.42.0
scikit-learn:1.4.2

**Comment by madakkmi** [comment]
Upgrading Windows 10 to 11 does not solve the issue.

**Comment by fingoldo** [comment]
Having the same issue now with Windows Server 2019, Python 3.11.5, Cuda 11.7

One suspicious place in the logs I noticed is

> R:\ProgramData\anaconda3\Lib\site-packages\setuptools\command\build_py.py:207: _Warning: Package 'shap.cext' is absent from the `packages` configuration.
> !!
> 
>         ********************************************************************************
>         ############################
>         # Package would be ignored #
>         ############################
>         Python recognizes 'shap.cext' as an importable package[^1],
>         but it is absent from setuptools' `packages` configuration.

But right after that, it goes

> copying shap\cext\_cext.cc -> build\lib.win-amd64-cpython-311\shap\cext
> copying shap\cext\_cext_gpu.cc -> build\lib.win-amd64-cpython-311\shap\cext
> copying shap\cext\_cext_gpu.cu -> build\lib.win-amd64-cpython-311\shap\cext
> copying shap\cext\gpu_treeshap.h -> build\lib.win-amd64-cpython-311\shap\cext
> copying shap\cext\_cext.cc -> build\lib.win-amd64-cpython-311\shap\cext
> copying shap\cext\_cext_gpu.cc -> build\lib.win-amd64-cpython-311\shap\cext
> copying shap\cext\_cext_gpu.cu -> build\lib.win-amd64-cpython-311\shap\cext
> copying shap\cext\gpu_treeshap.h -> build\lib.win-amd64-cpython-311\shap\cext
> running build_ext

Any clues, anyone?

**Comment by fingoldo** [comment]
To clarify, I run

```python
import xgboost

import shap

# get a dataset on income prediction
X, y = shap.datasets.adult()

model = xgboost.XGBClassifier()
model.fit(X, y)
```

Now, implicit

```python
model.set_params(**{"device": "cuda"})


# shap will call the GPU accelerated version as long as the device parameter is set to
# "cuda"
explainer = shap.TreeExplainer(model)

for _ in range(1000):
    shap_values = explainer.shap_values(X)
```

runs and I can see it's utilizing GPU. Ah wait, GPU utilization probably stems just from the fact that prediction is done on GPU, as calculated Shapley values are the same as with vanilla TreeExplainer.

But explicit 

```python
explainer = shap.explainers.GPUTree(model, X)
shap_values = explainer(X)
```

fails with 

> File ~\AppData\Roaming\Python\Python311\site-packages\shap-0.0.0-py3.11-win-amd64.egg\shap\explainers\_gpu_tree.py:14
>       6 from ._tree import (
>       7     TreeExplainer,
>       8     _xgboost_cat_unsupported,
>       9     feature_perturbation_codes,
>      10     output_transform_codes,
>      11 )
>      13 try:
> ---> 14     from .. import _cext_gpu  # type: ignore
>      15 except ImportError as e:
>      16     record_import_error("cext_gpu", "cuda extension was not built during install!", e)
> 
> ImportError: DLL load failed while importing _cext_gpu: The specified module could not be found.
> 

Do we really need that check? is it implemented correctly?

**Comment by fingoldo** [comment]
Another thing. I tried building GPU-featured version on Ubuntu 22.04 - another failure.
Does ANYONE have it working on Win or Ubuntu?

> python3 setup.py install --user
> Attempting to build SHAP: with_binary=True, with_cuda=True (Attempt 1)
> NVCC ==>  /usr/local/cuda-12.5/bin/nvcc
> Compiling cuda extension, calling nvcc with arguments:
> ['/usr/local/cuda-12.5/bin/nvcc', '-allow-unsupported-compiler', 'shap/cext/_cext_gpu.cu', '-lib', '-o', 'build/lib_cext_gpu.a', '-Xcompiler', '-fPIC', '--include-path', '/usr/include/python3.10', '--std', 'c++14', '--expt-extended-lambda', '--expt-relaxed-constexpr', '-gencode=arch=compute_60,code=sm_60', '-gencode=arch=compute_70,code=sm_70', '-gencode=arch=compute_75,code=sm_75', '-gencode=arch=compute_75,code=compute_75', '-gencode=arch=compute_80,code=sm_80']
> running install
> /usr/lib/python3/dist-packages/setuptools/command/install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
>   warnings.warn(
> /usr/lib/python3/dist-packages/setuptools/command/easy_install.py:158: EasyInstallDeprecationWarning: easy_install command is deprecated. Use build and pip and other standards-based tools.
>   warnings.warn(
> running bdist_egg
> running egg_info
> writing UNKNOWN.egg-info/PKG-INFO
> writing dependency_links to UNKNOWN.egg-info/dependency_links.txt
> writing top-level names to UNKNOWN.egg-info/top_level.txt
> reading manifest file 'UNKNOWN.egg-info/SOURCES.txt'
> reading manifest template 'MANIFEST.in'
> no previously-included directories found matching '.github'
> no previously-included directories found matching 'appveyor'
> no previously-included directories found matching 'data'
> no previously-included directories found matching 'docs'
> no previously-included directories found matching 'javascript'
> no previously-included directories found matching 'notebooks'
> warning: no previously-included files found matching '.git-blame-ignore-revs'
> warning: no previously-included files found matching '.gitattributes'
> warning: no previously-included files found matching '.gitignore'
> warning: no previously-included files found matching '.pre-commit-config.yaml'
> warning: no previously-included files found matching '.readthedocs.yml'
> warning: no previously-included files found matching 'CONTRIBUTING.md'
> warning: no previously-included files found matching 'requirements.txt'
> adding license file 'LICENSE'
> writing manifest file 'UNKNOWN.egg-info/SOURCES.txt'
> installing library code to build/bdist.linux-x86_64/egg
> running install_lib
> running build_ext
> building 'shap._cext_gpu' extension
> x86_64-linux-gnu-gcc -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -g -fwrapv -O2 -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -I/usr/local/lib/python3.10/dist-packages/numpy/core/include -I/usr/include/python3.10 -c shap/cext/_cext_gpu.cc -o build/temp.linux-x86_64-3.10/shap/cext/_cext_gpu.o -fPIC
> In file included from shap/cext/_cext_gpu.cc:5:
> shap/cext/tree_shap.h: In function ‘void dense_tree_interactions_path_dependent(const TreeEnsemble&, const ExplanationDataset&, tfloat*, tfloat (*)(tfloat, tfloat))’:
> shap/cext/tree_shap.h:1321:36: warning: comparison of integer expressions of different signedness: ‘unsigned int’ and ‘int’ [-Wsign-compare]
>  1321 |             for (unsigned l = 0; l < amount_of_unique_features; ++l) {
>       |                                  ~~^~~~~~~~~~~~~~~~~~~~~~~~~~~
> shap/cext/tree_shap.h:1351:36: warning: comparison of integer expressions of different signedness: ‘unsigned int’ and ‘int’ [-Wsign-compare]
>  1351 |             for (unsigned k = 0; k < amount_of_unique_features; ++k) {
>       |                                  ~~^~~~~~~~~~~~~~~~~~~~~~~~~~~
> x86_64-linux-gnu-g++ -shared -Wl,-O1 -Wl,-Bsymbolic-functions -Wl,-Bsymbolic-functions -g -fwrapv -O2 -Wl,-Bsymbolic-functions -g -fwrapv -O2 -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 build/temp.linux-x86_64-3.10/shap/cext/_cext_gpu.o -Lbuild -L/usr/local/cuda-12.5/lib64 -l_cext_gpu -lcudart -o build/lib.linux-x86_64-3.10/shap/_cext_gpu.cpython-310-x86_64-linux-gnu.so
> creating build/bdist.linux-x86_64/egg
> creating build/bdist.linux-x86_64/egg/shap
> copying build/lib.linux-x86_64-3.10/shap/_cext.cpython-310-x86_64-linux-gnu.so -> build/bdist.linux-x86_64/egg/shap
> copying build/lib.linux-x86_64-3.10/shap/_cext_gpu.cpython-310-x86_64-linux-gnu.so -> build/bdist.linux-x86_64/egg/shap
> creating stub loader for shap/_cext.cpython-310-x86_64-linux-gnu.so
> creating stub loader for shap/_cext_gpu.cpython-310-x86_64-linux-gnu.so
> byte-compiling build/bdist.linux-x86_64/egg/shap/_cext.py to _cext.cpython-310.pyc
> byte-compiling build/bdist.linux-x86_64/egg/shap/_cext_gpu.py to _cext_gpu.cpython-310.pyc
> creating build/bdist.linux-x86_64/egg/EGG-INFO
> copying UNKNOWN.egg-info/PKG-INFO -> build/bdist.linux-x86_64/egg/EGG-INFO
> copying UNKNOWN.egg-info/SOURCES.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
> copying UNKNOWN.egg-info/dependency_links.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
> copying UNKNOWN.egg-info/top_level.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
> writing build/bdist.linux-x86_64/egg/EGG-INFO/native_libs.txt
> zip_safe flag not set; analyzing archive contents...
> shap.__pycache__._cext.cpython-310: module references __file__
> shap.__pycache__._cext_gpu.cpython-310: module references __file__
> creating 'dist/UNKNOWN-0.0.0-py3.10-linux-x86_64.egg' and adding 'build/bdist.linux-x86_64/egg' to it
> removing 'build/bdist.linux-x86_64/egg' (and everything under it)
> Processing UNKNOWN-0.0.0-py3.10-linux-x86_64.egg
> removing '/home/test/.local/lib/python3.10/site-packages/UNKNOWN-0.0.0-py3.10-linux-x86_64.egg' (and everything under it)
> creating /home/test/.local/lib/python3.10/site-packages/UNKNOWN-0.0.0-py3.10-linux-x86_64.egg
> Extracting UNKNOWN-0.0.0-py3.10-linux-x86_64.egg to /home/test/.local/lib/python3.10/site-packages
> UNKNOWN 0.0.0 is already the active version in easy-install.pth
> 
> Installed /home/test/.local/lib/python3.10/site-packages/UNKNOWN-0.0.0-py3.10-linux-x86_64.egg
> Processing dependencies for UNKNOWN==0.0.0
> Finished processing dependencies for UNKNOWN==0.0.0

**Comment by madakkmi** [comment]
@fingoldo, I've Ubuntu 20.04.6 on Win 11 as WSL and I was able to successfully install SHAP with CUDA support.
