### ISSUE TITLE
BUG: AssertionError, the SHAP explanations do not sum up to the model's output!

### ISSUE THREAD

**Issue by joao-ferreira-dc** [shap/shap#3679]
### Issue Description

AssertionError: The SHAP explanations do not sum up to the model's output! This is either because of a rounding error or because an operator in your computation graph was not fully supported. If the sum difference of %f is significant compared to the scale of your model outputs, please post as a github issue, with a reproducible example so we can debug it. Used framework: pytorch - Max. diff: 0.2749565706762951 - Tolerance: 0.01

### Minimal Reproducible Example

```python
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, LabelEncoder
import torch
import torch.nn as nn
import torch.optim as optim
import shap

# Data Preprocessing Class
class TitanicData:
    def __init__(self, url):
        self.data = pd.read_csv(url)
        self.label_encoders = {}
        self.scaler = StandardScaler()
        self.preprocess()

    def preprocess(self):
        print(self.data.columns)
        self.data['Age'] = self.data['Age'].fillna(self.data['Age'].median())
        
        # Drop the 'Name' column as it is not useful for prediction
        self.data.drop(['Name'], axis=1, inplace=True)
        
        # Encode categorical features
        for column in ['Sex']:
            le = LabelEncoder()
            self.data[column] = le.fit_transform(self.data[column])
            self.label_encoders[column] = le
        
        # Split data into features and target
        self.X = self.data.drop('Survived', axis=1).values
        self.y = self.data['Survived'].values
        
        # Standardize features
        self.X = self.scaler.fit_transform(self.X)
        
        # Split into train and test sets
        self.split_data()

    def split_data(self, test_size=0.2, random_state=42):
        self.X_train, self.X_test, self.y_train, self.y_test = train_test_split(
            self.X, self.y, test_size=test_size, random_state=random_state
        )
        self.X_train = torch.tensor(self.X_train, dtype=torch.float32)
        self.X_test = torch.tensor(self.X_test, dtype=torch.float32)
        self.y_train = torch.tensor(self.y_train, dtype=torch.float32).view(-1, 1)
        self.y_test = torch.tensor(self.y_test, dtype=torch.float32).view(-1, 1)

# Neural Network Class
class TitanicNN(nn.Module):
    def __init__(self, input_size):
        super(TitanicNN, self).__init__()
        self.fc1 = nn.Linear(input_size, 128)
        self.fc2 = nn.Linear(128, 64)
        self.fc3 = nn.Linear(64, 1)
        
    def forward(self, x):
        x = torch.relu(self.fc1(x))
        x = torch.relu(self.fc2(x))
        x = torch.sigmoid(self.fc3(x))
        return x

# Training and Evaluation Class
class TitanicModel:
    def __init__(self, net, criterion, optimizer):
        self.net = net
        self.criterion = criterion
        self.optimizer = optimizer

    def train(self, X_train, y_train, epochs=20):
        self.net.train()
        for epoch in range(epochs):
            self.optimizer.zero_grad()
            outputs = self.net(X_train)
            loss = self.criterion(outputs, y_train)
            loss.backward()
            self.optimizer.step()
            print(f'Epoch {epoch+1}/{epochs}, Loss: {loss.item():.4f}')

    def evaluate(self, X_test, y_test):
        self.net.eval()
        with torch.no_grad():
            outputs = self.net(X_test)
            predicted = (outputs > 0.5).float()
            accuracy = (predicted == y_test).sum().item() / y_test.size(0)
            print(f'Accuracy: {accuracy * 100:.2f}%')
        return predicted

# Explain the model's predictions using SHAP
class SHAPExplainer:
    def __init__(self, model, data):
        self.model = model
        self.data = data
        self.explainer = shap.DeepExplainer(self.model.net, self.data.X_train)
        
    def explain(self, X_test):
        shap_values = self.explainer.shap_values(X_test)
        shap.summary_plot(shap_values, X_test.numpy())

# Main Execution
if __name__ == "__main__":
    url = 'https://web.stanford.edu/class/archive/cs/cs109/cs109.1166/stuff/titanic.csv'
    data = TitanicData(url)
    net = TitanicNN(input_size=data.X_train.shape[1])
    criterion = nn.BCELoss()
    optimizer = optim.Adam(net.parameters(), lr=0.001)
    model = TitanicModel(net, criterion, optimizer)
    model.train(data.X_train, data.y_train, epochs=20)
    predictions = model.evaluate(data.X_test, data.y_test)
    shap_explainer = SHAPExplainer(model, data)
    shap_explainer.explain(data.X_test)
```

### Traceback

```shell
Traceback (most recent call last):
  File "c:\Users\Joao Ferreira\Documents\Titanic_Explainability\main.py", line 112, in <module>
    shap_explainer.explain(data.X_test)
  File "c:\Users\Joao Ferreira\Documents\Titanic_Explainability\main.py", line 98, in explain
    shap_values = self.explainer.shap_values(X_test)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Joao Ferreira\anaconda3\envs\Work\Lib\site-packages\shap\explainers\_deep\__init__.py", line 159, in shap_values
    return self.explainer.shap_values(X, ranked_outputs, output_rank_order, check_additivity=check_additivity)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Joao Ferreira\anaconda3\envs\Work\Lib\site-packages\shap\explainers\_deep\deep_pytorch.py", line 214, in shap_values
    _check_additivity(self, model_output_values.cpu(), output_phis)
  File "C:\Users\Joao Ferreira\anaconda3\envs\Work\Lib\site-packages\shap\explainers\_deep\deep_utils.py", line 20, in _check_additivity
    assert maxdiff < TOLERANCE, "The SHAP explanations do not sum up to the model's output! This is either because of a " \
           ^^^^^^^^^^^^^^^^^^^
AssertionError: The SHAP explanations do not sum up to the model's output! This is either because of a rounding error or because an operator in your computation graph was not fully supported. If the sum difference of %f is significant compared to the scale of your model outputs, please post as a github issue, with a reproducible example so we can debug it. Used framework: pytorch - Max. diff: 0.2749565706762951 - Tolerance: 0.01
```

### Bug report checklist

- [X] I have checked that this issue has not already been reported.
- [X] I have confirmed this bug exists on the [latest release](https://github.com/shap/shap/releases) of shap.
- [X] I have confirmed this bug exists on the [master branch](https://github.com/shap/shap/blob/master/CONTRIBUTING.md#installing-from-the-master-branch) of shap.
- [ ] I'd be interested in making a PR to fix this bug

### Installed Versions

shap==0.45.1

**Comment by Siyuan-Shen** [comment]
Same issue here when I run shap on a residual CNN regression model.

**Comment by robiim** [comment]
Same issue when running deep explainer on a network with the following structure:

- Masking(self.constant_value, input_shape=(nsteps, nfeatures)

- tf.keras.layers.LSTM(n, return_sequences=True),

-  tf.keras.layers.Dropout(a),

-  tf.keras.layers.LSTM(w, return_sequences=True),

-  AttentionLayer(),

-  tf.keras.layers.Dense(1, activation='sigmoid', bias_initializer=None)


I also tried GradientExplainer there was not any error message, but I had the same issue: the sum between shap values and the base value did not match the model output

**Comment by jasonw-w** [comment]
Hi. Does anyone find a solution for this issue? I have a similar issue with it but it is just a very simple CNN network:

- torch.conv2d
- torch.maxpool2d
- nn.relu
- torch.conv2d
- torch.maxpool2d
- nn.relu
- x.view(-1, output)
- nn.Linear
I believe that this is a really simple network, but no matter how I change it (activation func, flatten -> x.view, amount of layers) It just doesnt work and the shap value seems inaccurate

**Comment by caenrigen** [comment]
For future readers, see my comments on these two other issues:

https://github.com/shap/shap/issues/3938#issuecomment-3205824703 (this one seem to apply here)
https://github.com/shap/shap/issues/3735#issuecomment-3205861143 (this is good to keep in mind)
