### ISSUE TITLE
BUG: Sphinx docs fails to build with myst

### ISSUE THREAD

**Issue by thatlittleboy** [shap/shap#3750]
Sphinx build fails on a fresh install at the moment,

```sh
$ git clone git@github.com/shap/shap
$ cd shap && python -m venv venv
$ pip install -e '.[test,plots,docs]'
$ cd docs && make html
# see logs below
```

### Sphinx logs

```
# Platform:         darwin; (macOS-14.0-arm64-arm-64bit)
# Sphinx version:   7.2.6
# Python version:   3.10.13 (CPython)
# Docutils version: 0.20.1
# Jinja2 version:   3.1.4
# Pygments version: 2.18.0

# Last messages:
#   venv/lib/python3.10/site-packages/bleach/_vendor/README
#

#   reading sources... [ 81%]
#   venv/lib/python3.10/site-packages/bleach/_vendor/html5lib-1.1.dist-info/AUTHORS
#

#   reading sources... [ 81%]
#   venv/lib/python3.10/site-packages/huggingface_hub/templates/datasetcard_template
#

# Loaded extensions:
#   sphinx.ext.mathjax (7.2.6)
#   alabaster (0.7.16)
#   sphinxcontrib.applehelp (1.0.8)
#   sphinxcontrib.devhelp (1.0.6)
#   sphinxcontrib.htmlhelp (2.0.5)
#   sphinxcontrib.serializinghtml (1.1.10)
#   sphinxcontrib.qthelp (1.0.7)
#   sphinx.ext.autodoc.preserve_defaults (7.2.6)
#   sphinx.ext.autodoc.type_comment (7.2.6)
#   sphinx.ext.autodoc.typehints (7.2.6)
#   sphinx.ext.autodoc (7.2.6)
#   sphinx.ext.autosectionlabel (7.2.6)
#   sphinx.ext.autosummary (7.2.6)
#   sphinxcontrib.jquery (4.1)
#   sphinx_rtd_theme (unknown version)
#   numpydoc (1.7.0)
#   nbsphinx (0.9.3)
#   myst_parser (2.0.0)
#   sphinx_github_changelog (1.2.1)

# Traceback:
Traceback (most recent call last):
  File "/Users/xxx/shap/docs/venv/lib/python3.10/site-packages/sphinx/cmd/build.py", line 298, in build_main
    app.build(args.force_all, args.filenames)
  File "/Users/xxx/shap/docs/venv/lib/python3.10/site-packages/sphinx/application.py", line 355, in build
    self.builder.build_update()
  File "/Users/xxx/shap/docs/venv/lib/python3.10/site-packages/sphinx/builders/__init__.py", line 293, in build_update
    self.build(to_build,
  File "/Users/xxx/shap/docs/venv/lib/python3.10/site-packages/sphinx/builders/__init__.py", line 313, in build
    updated_docnames = set(self.read())
  File "/Users/xxx/shap/docs/venv/lib/python3.10/site-packages/sphinx/builders/__init__.py", line 420, in read
    self._read_serial(docnames)
  File "/Users/xxx/shap/docs/venv/lib/python3.10/site-packages/sphinx/builders/__init__.py", line 441, in _read_serial
    self.read_doc(docname)
  File "/Users/xxx/shap/docs/venv/lib/python3.10/site-packages/sphinx/builders/__init__.py", line 498, in read_doc
    publisher.publish()
  File "/Users/xxx/shap/docs/venv/lib/python3.10/site-packages/docutils/core.py", line 234, in publish
    self.document = self.reader.read(self.source, self.parser,
  File "/Users/xxx/shap/docs/venv/lib/python3.10/site-packages/sphinx/io.py", line 105, in read
    self.parse()
  File "/Users/xxx/shap/docs/venv/lib/python3.10/site-packages/docutils/readers/__init__.py", line 76, in parse
    self.parser.parse(self.input, document)
  File "/Users/xxx/shap/docs/venv/lib/python3.10/site-packages/myst_parser/parsers/sphinx_.py", line 62, in parse
    topmatter = read_topmatter(inputstring)
  File "/Users/xxx/shap/docs/venv/lib/python3.10/site-packages/myst_parser/config/main.py", line 583, in read_topmatter
    metadata = yaml.safe_load("".join(top_matter))
  File "/Users/xxx/shap/docs/venv/lib/python3.10/site-packages/yaml/__init__.py", line 125, in safe_load
    return load(stream, SafeLoader)
  File "/Users/xxx/shap/docs/venv/lib/python3.10/site-packages/yaml/__init__.py", line 81, in load
    return loader.get_single_data()
  File "/Users/xxx/shap/docs/venv/lib/python3.10/site-packages/yaml/constructor.py", line 51, in get_single_data
    return self.construct_document(node)
  File "/Users/xxx/shap/docs/venv/lib/python3.10/site-packages/yaml/constructor.py", line 60, in construct_document
    for dummy in generator:
  File "/Users/xxx/shap/docs/venv/lib/python3.10/site-packages/yaml/constructor.py", line 413, in construct_yaml_map
    value = self.construct_mapping(node)
  File "/Users/xxx/shap/docs/venv/lib/python3.10/site-packages/yaml/constructor.py", line 218, in construct_mapping
    return super().construct_mapping(node, deep=deep)
  File "/Users/xxx/shap/docs/venv/lib/python3.10/site-packages/yaml/constructor.py", line 141, in construct_mapping
    raise ConstructorError("while constructing a mapping", node.start_mark,
yaml.constructor.ConstructorError: while constructing a mapping
  in "<unicode string>", line 3, column 1:
    {{ card_data }}
    ^
found unhashable key
  in "<unicode string>", line 3, column 2:
    {{ card_data }}
     ^
```

**Comment by thatlittleboy** [comment]
The reason for this is that `Sphinx` is reading sources from my `venv` directory (in the project root), and it collected the ["huggingface_hub/templates/datasetcard_template.md" file](https://raw.githubusercontent.com/huggingface/huggingface_hub/main/src/huggingface_hub/templates/datasetcard_template.md), as seen from the logs:

```
venv/lib/python3.10/site-packages/huggingface_hub/templates/datasetcard_template
```

And the Jinja templating in the header is throwing off the yaml parser invoked by Myst.

ps: ignore me, just realized I installed the venv in the docs/ folder. :x
