### ISSUE TITLE
`ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()` in `shap.plots.beeswarm` 

### ISSUE THREAD

**Issue by harupy** [shap/shap#3901]
## Reproduction:

```python
import shap

shap.plots.beeswarm(shap.Explanation([[1, 2, 3]]), show=False, color_bar=True)
```

## Traceback

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.9/site-packages/shap/plots/_beeswarm.py", line 117, in beeswarm
    color = convert_color(color)
  File "/usr/local/lib/python3.9/site-packages/shap/plots/_utils.py", line 10, in convert_color
    if color == "shap_red":
ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()
```

## Package information

```
root@8482a3f67cc2:/# pip list | grep '\(shap\|numpy\)'
numpy               2.0.2
shap                0.46.0
```

**Comment by harupy** [comment]
Explicitly specifying the color works:

```python
shap.plots.beeswarm(shap.Explanation([[1, 2, 3]]), show=False, color_bar=True, color="cool")
```

**Comment by CloseChoice** [comment]
Hi,
and thanks for reporting this. Could you please provide an example to reproduce this issue?

**Comment by harupy** [comment]
@CloseChoice You can run this code:

```python
import shap

shap.plots.beeswarm(shap.Explanation([[1, 2, 3]]), show=False, color_bar=True)
```

**Comment by CloseChoice** [comment]
@harupy thanks, I somehow missed that this is a complete example. Thanks for reporting. I added a PR to fix this.
