### ISSUE TITLE
TreeEnsemble instance has no attribute 'values' in LightGBM

### ISSUE THREAD

**Issue by prabod** [shap/shap#480]
I got following error while running shap_interaction_values. but shap_values is running fine.
I tried with both lgb 2.2.2 and 2.2.3 with shap 0.28.5 it returns the same error.

----> 1 shap_interaction_values = explainer.shap_interaction_values(train_features)

/home/prabod/anaconda2/lib/python2.7/site-packages/shap/explainers/tree.pyc in shap_interaction_values(self, X, y, tree_limit)
    334 
    335         if tree_limit < 0 or tree_limit > self.model.values.shape[0]:
--> 336             tree_limit = self.model.values.shape[0]
    337 
    338         # run the core algorithm using the C extension

AttributeError: TreeEnsemble instance has no attribute 'values'

**Comment by slundberg** [comment]
I just checked and it worked for me on 2.2.2, could you share a full working example of the issue?

**Comment by prabod** [comment]
Hi I just checked with various test cases. It only happens when we use 'categorical_feature' in lightgbm.
You can confirm from the [colab](https://colab.research.google.com/drive/1NAYbySlFJQwYgp58WCqtwSWxAgH2HNwx
) notebook below.
[Colab Notebook](https://colab.research.google.com/drive/1NAYbySlFJQwYgp58WCqtwSWxAgH2HNwx
) 

Thanks

**Comment by saj1919** [comment]
I am facing the same issue with CatBoost model. I tried using categorical_feature and without it. Did not work in either case. 

Everything else worked fine as explained [here](https://github.com/slundberg/shap) in README.md

Code
`shap.TreeExplainer(model).shap_interaction_values(x_train)`

Error
```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-48-8228de989cbd> in <module>
----> 1 shap.TreeExplainer(model).shap_interaction_values(x_train)

/mnt/anaconda3/lib/python3.7/site-packages/shap/explainers/tree.py in shap_interaction_values(self, X, y, tree_limit)
    334 
    335         if tree_limit < 0 or tree_limit > self.model.values.shape[0]:
--> 336             tree_limit = self.model.values.shape[0]
    337 
    338         # run the core algorithm using the C extension

AttributeError: 'TreeEnsemble' object has no attribute 'values'
```

**Comment by Sebber123** [comment]
Hi,

I am having the same problem with LGBM and categorical features. Is the only fix to one hot encode them for now?

Thanks in advance

**Comment by cbeauhilton** [comment]
Just giving a +1 to this. LightGBM w/ categorical features. Tried a good ol'-fashioned `conda update conda --all` and it did not fix it. Will try a fresh environment and see what happens.

**Comment by NancyLele** [comment]
@slundberg 
I met the same problem with lightgbm.LGBMClassifier and  categorical features. And the version of shap is 0.29.1.

**Comment by MichaelMoravetz** [comment]
Same problem with the most recent version of catboost and most recent shap as well. Also, shap_interaction_values doesnt want to play nice with Pool object.  getting an attribute error regarding it not having a dtype from line 329.  I resolved a similar issue with the pool object when calculating shap values by making the categorical features all pandas category types.  However I dont recall the exact error as it resolved easily.  This seems to be different.  Ill let you know if I get my head around this when I have the time to get back to it.  I upgraded basically everything im using, maybe I should try going back to an older version of something? :(

**Comment by DigitalPig** [comment]
I spent some time digging into this issue. And unfortunately I don't think it would be an easy fix:

1. The cause of this error is because the `TreeEnsemble` does not have `values` property [here](https://github.com/slundberg/shap/blob/837f4847e22603ac986678f8c94b8315a375ce36/shap/explainers/tree.py#L769).
2. The reason why it does not have `values` property is because the split information in LightGBM is written as "cat A || cat B" and `shap` [cannot handle it at this moment](https://github.com/slundberg/shap/blob/837f4847e22603ac986678f8c94b8315a375ce36/shap/explainers/tree.py#L602-L605).

Therefore, `shap`'s `Tree` class needs to be updated to handle categorical split first to fix this bug.

**Comment by slundberg** [comment]
Thanks @DigitalPig ! You are right that about the categorical variable splits being a lot of work to support. The core TreeExplainer code assumes that trees split on individual features based on a threshold. To support 'categorical splits', we will need to add support for not just a threshold decision, but a set membership decision. This can be done, but will require some thought and some updates to the C++ code of SHAP. I am adding help wanted here, but please note this would require a serious C++ coding commitment (i.e. you probably need to be a c++ dev who needs this feature for work).

**Comment by neverfox** [comment]
Dang this is a huge issue for SHAP's lightGBM support, since modeling categorical features is a huge part of lightGBM's offerings. Hopefully someone can fix this.

**Comment by aymoawad** [comment]
Any update on this issue?

**Comment by FRUEHNI1** [comment]
I think you can call model.predict(x, return_contrib=True)

**Comment by aymoawad** [comment]
Sorry, I should have mentioned I'm working with a Catboost model. Catboost does compute interaction values too but does not have the same level of detail in the output. It would be nice to have the treeExplainer work on Catboost models.

**Comment by slundberg** [comment]
Just to clarify here, categorical features are supported in LightGBM with `feature_perturbation="tree_path_dependent"`, it is just not supported when `feature_perturbation="interventional"`. Since tree_path_dependent only works when explaining the margin output of a model (as opposed to say the probability), the current limitation is that for lightGBM models we can only explain the margin. Fixing this is something we want to do.

**Comment by slundberg** [comment]
@aymoawad CatBoost models are also supported with TreeExplainer in the same way as for LightGBM.

I just added a new more informative error message that should help future users here.

**Comment by aymoawad** [comment]
@slundberg For SHAP values generation I think it works fine because in tree.py the `shap_values` function takes the shortcut of calling Catboost `get_feature_importance` calculation of shap values. But when calling `explainer.shap_interaction_values(Pool(X,cat_features=categorical_features_indices))` for a Catboost model problems arise:
1. line 392 of tree.py `if X.dtype != self.model.input_dtype:` would crash because of the Pool, you can get it to pass this part with some tricks but then.
2. line 398 `if tree_limit < 0 or tree_limit > self.model.values.shape[0]:` crashes because there is no explainer.model.values.

Catboost does compute shap interactions their way through the specification of `type='Interaction'` when calling `get_feature_importance` (perhaps you want to implement that shortcut). However, the level of fidelity is not the same, the output is not in tensor form like yours and the interpretation is different with no main component effects, etc... Ideally, you want consistency in the interaction calculation output across models and that's what I was referring too (or hoping for!)

Let me know if that makes sense or if I'm missing something.

**Comment by slundberg** [comment]
@aymoawad excellent points! Yes I think the right thing to do is add support for categorical splits into the core SHAP C++ code. Then we can support a consistent interface for interaction effects as well.

**Comment by ChintanDonda** [comment]
Facing the same issue using **CatBoostRegressor**.
FYI, **CatBoost = v0.23.2 | Shapley = v0.34.0**

This is how I'm doing & it works fine:
### Fit/Predict Shapley on X_train
explainer = shap.TreeExplainer(model)
train_shap_values = explainer.shap_values(X_train)

However, it fails with error: "**AttributeError: 'TreeEnsemble' object has no attribute 'values'**" when I try to predict shapely values on **X_test** using the above explainer like this:
### Predict shapley on X_test
test_shap_values = explainer.shap_values(X_test)

Basically I'm training shapley on X_train data & want the explainer to predict on X_test in future calls so that I don't need to retrain shapley again.
What I'm trying to achieve is, train shapley once on X_train & save the explainer into pickle file.
Load the shapley model back in the scoring pipeline.

FYI, below snippet works using **RandomForestRegressor**:
explainer = shap.TreeExplainer(model)
train_shap_values = explainer.shap_values(X_train)
test_shap_values = explainer.shap_values(X_test)

Please help me clarify if this is the right approach or not ?

**Comment by nickcorona** [comment]
> Facing the same issue using **CatBoostRegressor**.
> FYI, **CatBoost = v0.23.2 | Shapley = v0.34.0**
> 
> This is how I'm doing & it works fine:
> 
> ### Fit/Predict Shapley on X_train
> explainer = shap.TreeExplainer(model)
> train_shap_values = explainer.shap_values(X_train)
> 
> However, it fails with error: "**AttributeError: 'TreeEnsemble' object has no attribute 'values'**" when I try to predict shapely values on **X_test** using the above explainer like this:
> 
> ### Predict shapley on X_test
> test_shap_values = explainer.shap_values(X_test)
> 
> Basically I'm training shapley on X_train data & want the explainer to predict on X_test in future calls so that I don't need to retrain shapley again.
> What I'm trying to achieve is, train shapley once on X_train & save the explainer into pickle file.
> Load the shapley model back in the scoring pipeline.
> 
> FYI, below snippet works using **RandomForestRegressor**:
> explainer = shap.TreeExplainer(model)
> train_shap_values = explainer.shap_values(X_train)
> test_shap_values = explainer.shap_values(X_test)
> 
> Please help me clarify if this is the right approach or not ?

I get the same issue.

**Comment by bratan05** [comment]
With CatBoost you can:
```python
from catboost import EFstrType, Pool
shap_values = model.get_feature_importance(Pool(data[Xtrain.columns]),type=EFstrType.ShapValues,verbose=100)
shap_interaction_values = model.get_feature_importance(Pool(data[Xtrain.columns]),type=EFstrType.ShapInteractionValues,verbose=100)
```

Doesn't solve the original problem I guess, but still gives you something

**Comment by brunofacca** [comment]
I'm getting this issue with CatBoost without any categorical features. Using `TreeExplainer` with `feature_perturbation='interventional'` and `model_output='log_loss'`.

**Comment by pford221** [comment]
I had the a similar issue.

1.) No categorical variables
2.) LightGBM back-end

I did have some boolean variables in the dataset, and when I set them to floats, the error disappeared.

**Comment by ThomasWolf0701** [comment]
Same for me with catboost, no categorial variables, yet still the following error on a regression model:
explainer = shap.TreeExplainer(bestModel["m"], data=transformedMatrix, model_output='raw', feature_perturbation='interventional') 

Traceback (most recent call last):

  File "<ipython-input-187-c058102f617a>", line 1, in <module>

    explainer = shap.TreeExplainer(bestModel["m"], data=transformedMatrix, model_output='raw', feature_perturbation='interventional')

  File "C:\Users\Thomas Wolf\anaconda3\envs\ChemPipeline\lib\site-packages\shap\explainers\_tree.py", line 177, in __init__
    self.expected_value = self.model.predict(self.data).mean(0)

  File "C:\Users\Thomas Wolf\anaconda3\envs\ChemPipeline\lib\site-packages\shap\explainers\_tree.py", line 1091, in predict
    tree_limit = self.values.shape[0]

AttributeError: 'TreeEnsemble' object has no attribute 'values'

**Comment by brunofacca** [comment]
I'm getting this error again, this time with LightGBM 3.2.1 with Ranfom Forest boosting type (`boosting_type='rf'`) and SHAP 0.39.0. There are no categorical or boolean values in the dataset, only floats.

**Comment by banderlog** [comment]
Same problem with lightgbm-3.3.0 and shap-0.40.0

**Comment by niazch** [comment]
> Same problem with lightgbm-3.3.0 and shap-0.40.0

Same here

**Comment by seakelle** [comment]
> Just to clarify here, categorical features are supported in LightGBM with `feature_perturbation="tree_path_dependent"`, it is just not supported when `feature_perturbation="interventional"`. Since tree_path_dependent only works when explaining the margin output of a model (as opposed to say the probability), the current limitation is that for lightGBM models we can only explain the margin. Fixing this is something we want to do.

Seems like this error still exists with the [GPUTree](https://shap.readthedocs.io/en/latest/generated/shap.explainers.GPUTree.html#shap-explainers-gputree) explainer even with `feature_perturbation="tree_path_dependent"`.

Here's the dockerfile I use:
```docker
FROM nvidia/cuda:10.2-devel-ubuntu18.04
ENV PATH="/root/miniconda3/bin:${{PATH}}"
ARG PATH="/root/miniconda3/bin:${{PATH}}"
RUN apt-get update && \
apt-get install -y fuse && \
apt-get install -y build-essential && \
apt-get install -y python3-dev && \
apt-get install -y wget && \
apt-get install -y git && \
rm -rf /var/lib/apt/lists/* && \
wget \
https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh && \
mkdir /root/.conda && \
bash Miniconda3-latest-Linux-x86_64.sh -b && \
rm -f Miniconda3-latest-Linux-x86_64.sh && \
conda init bash && \
. ~/.bashrc && \
conda create -n shapgpu python=3.7 && \
conda activate shapgpu && \
apt-get install -y g++ && \
printenv && \
echo "which nvcc: " && \
which nvcc && \
pip install numpy==1.20.3 && \
pip install azureml-defaults && \
pip install azureml-telemetry && \
pip install azureml-interpret && \
pip install pandas==1.3.5 && \
cd /usr/local/src && \
git clone https://github.com/slundberg/shap.git --single-branch && \
cd shap && \
git reset --hard 690245c6ab043edf40cfce3d8438a62e29ab599f && \
mkdir build && \
python setup.py install --user && \
pip uninstall -y lightgbm && \
pip install lightgbm==3.3.2 \
```

Repro code:
```py
import lightgbm
import shap

# display=True to keep categorical features as is
X, y = shap.datasets.adult(display=True)

model = lightgbm.LGBMClassifier()
model.fit(X, y)

X_shap = X.sample(n=100)
explainer = shap.TreeExplainer(model, feature_perturbation="tree_path_dependent")
shap_values = explainer.shap_values(X_shap) # works

explainer = shap.explainers.GPUTree(model, feature_perturbation="tree_path_dependent")
shap_values = explainer.shap_values(X_shap) # fails
```

**Comment by seakelle** [comment]
Update to my last comment, I've confirmed with the NVIDIA team behind the SHAP [GPUTree](https://shap.readthedocs.io/en/latest/generated/shap.explainers.GPUTree.html#shap-explainers-gputree) explainer implementation that it **does not** work with categorical features.

However, [cuML](https://docs.rapids.ai/api/cuml/stable/) does have an implementation of TreeExplainer which does work with categorical features: https://docs.rapids.ai/api/cuml/nightly/api.html#cuml.explainer.TreeExplainer. 

Although I have not tested it yet, hopefully this can serve as a workaround for anyone who encounters the same issue.

**Comment by beckernick** [comment]
As a note, cuML's TreeExplainer is built on top of GPUTreeShap and also [doesn't support categorical features today](https://docs.rapids.ai/api/cuml/nightly/api.html#cuml.explainer.TreeExplainer).

```
Parameters: model object
The tree based machine learning model. XGBoost, LightGBM, cuml random forest and sklearn random forest models are supported. Categorical features in XGBoost or LightGBM models are natively supported.
```

If you're interested in this functionality in cuML or GPUTreeShap, please consider [opening a feature request](https://github.com/rapidsai/cuml/issues)!

**Comment by seakelle** [comment]
@beckernick Based on my conversation with NVIDIA and the documentation, including the quote you included, categorical features should be supported. I just haven't been able to test it yet.

Here's the explanation:
> Why does this version support categoricals and not the shap package version? We rebuilt this version of TreeExplainer in cuml using TreeLite as an intermediate tree model format. This means that we outsource all of the tricky model conversion code (sklearn RF, xgboost, LightGBM, etc,) to TreeLite and only have to apply the shap algorithm to the TreeLite generic representation. 

If you have tested it and it actually _doesn't_ work, that would be great information and I implore you to include repro here!

**Comment by beckernick** [comment]
Nope, you're right. Thanks for the sanity check. I'm out of date and misread cuML's documentation :)

**Comment by drtobybrown** [comment]
Same issue:
- CatBoost
- No categorical features

```
from catboost import CatBoostRegressor
import shap 
import pandas as pd

# Initialize data

train_data = pd.DataFrame([[1, 4, 5, 6],
              [4, 5, 6, 7],
              [30, 40, 50, 60]])

eval_data = pd.DataFrame([[2, 4, 6, 8],
             [1, 4, 50, 60]])

train_labels = [10, 20, 30]
# Initialize CatBoostRegressor
model = CatBoostRegressor(iterations=2,
                          learning_rate=1,
                          depth=2)
# Fit model
model.fit(train_data, train_labels)
# Get predictions
preds = model.predict(eval_data)


explainer = shap.TreeExplainer(
    model, data=train_data, feature_perturbation="interventional", approximate=True, seed=1
) 
```

throws error:

```
---> 25 explainer = shap.TreeExplainer(
     26     model, data=train_data, feature_perturbation="interventional", approximate=True, seed=1
     27 )

~/.conda/envs/base/lib/python3.9/site-packages/shap/explainers/_tree.py in __init__(self, model, data, model_output, feature_perturbation, feature_names, approximate, **deprecated_options)
    179         elif data is not None:
    180             try:
--> 181                 self.expected_value = self.model.predict(self.data).mean(0)
    182             except ValueError:
    183                 raise ExplainerError("Currently TreeExplainer can only handle models with categorical splits when " \

~/.conda/envs/base/lib/python3.9/site-packages/shap/explainers/_tree.py in predict(self, X, y, output, tree_limit)
   1105 
   1106         if tree_limit < 0 or tree_limit > self.values.shape[0]:
-> 1107             tree_limit = self.values.shape[0]
   1108 
   1109         if output == "logloss":

AttributeError: 'TreeEnsemble' object has no attribute 'values'
```

**Comment by fingoldo** [comment]
Looks like  SHAP package is abandoned by the author.

**Comment by hanhanwu** [comment]
I had the same problem when using Catboost and try to get SHAP in probability in SHAP. If doesn't require SHAP values in probability format there's no problem to me. So I can convert the SHAP values by using `np.exp(shap_value)/(1+np.exp(shap_value))`, because the non-probability output is log odds. I have validated the results, seems work.

**Comment by bhvieira** [comment]
Users currently have to guess if SHAP will work with their quite standard LightGBM models. I think it would be good to add error messages and tests for these cases.
