### ISSUE TITLE
tensorflow:Cannot use 'gradients_2/f_count_1' as input to 'gradients_2/f_count' because they are in different while loops

### ISSUE THREAD

**Issue by galenwilkerson** [shap/shap#502]
Hi, I'm getting a strange error when I try to use shap on this particular keras LSTM model (with tensorflow backend).  Thanks for suggestions.

Some environment info:  
python 3.6

`tensorflow.__version__`
> 1.12.0

`keras.__version__`
> 2.2.4

Error:

'INFO:tensorflow:Cannot use 'gradients_2/f_count_1' as input to 'gradients_2/f_count' because they are in different while loops.

gradients_2/f_count_1 while context: lstm_4/while/while_context
gradients_2/f_count while context: gradients_1/lstm_3/while/while_context

Traceback for gradients_2/f_count_1:
  File "/home/galen/anaconda3/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/galen/anaconda3/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/galen/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py", line 16, in <module>
    app.launch_new_instance()
  File "/home/galen/anaconda3/lib/python3.6/site-packages/traitlets/config/application.py", line 658, in launch_instance
    app.start()
  File "/home/galen/anaconda3/lib/python3.6/site-packages/ipykernel/kernelapp.py", line 486, in start
    self.io_loop.start()
  File "/home/galen/anaconda3/lib/python3.6/site-packages/tornado/platform/asyncio.py", line 127, in start
    self.asyncio_loop.run_forever()
  File "/home/galen/anaconda3/lib/python3.6/asyncio/base_events.py", line 422, in run_forever
    self._run_once()
  File "/home/galen/anaconda3/lib/python3.6/asyncio/base_events.py", line 1432, in _run_once
    handle._run()
  File "/home/galen/anaconda3/lib/python3.6/asyncio/events.py", line 145, in _run
    self._callback(*self._args)
  File "/home/galen/anaconda3/lib/python3.6/site-packages/tornado/platform/asyncio.py", line 117, in _handle_events
    handler_func(fileobj, events)
  File "/home/galen/anaconda3/lib/python3.6/site-packages/tornado/stack_context.py", line 276, in null_wrapper
    return fn(*args, **kwargs)
  File "/home/galen/anaconda3/lib/python3.6/site-packages/zmq/eventloop/zmqstream.py", line 450, in _handle_events
    self._handle_recv()
  File "/home/galen/anaconda3/lib/python3.6/site-packages/zmq/eventloop/zmqstream.py", line 480, in _handle_recv
    self._run_callback(callback, msg)
  File "/home/galen/anaconda3/lib/python3.6/site-packages/zmq/eventloop/zmqstream.py", line 432, in _run_callback
    callback(*args, **kwargs)
  File "/home/galen/anaconda3/lib/python3.6/site-packages/tornado/stack_context.py", line 276, in null_wrapper
    return fn(*args, **kwargs)
  File "/home/galen/anaconda3/lib/python3.6/site-packages/ipykernel/kernelbase.py", line 283, in dispatcher
    return self.dispatch_shell(stream, msg)
  File "/home/galen/anaconda3/lib/python3.6/site-packages/ipykernel/kernelbase.py", line 233, in dispatch_shell
    handler(stream, idents, msg)
  File "/home/galen/anaconda3/lib/python3.6/site-packages/ipykernel/kernelbase.py", line 399, in execute_request
    user_expressions, allow_stdin)
  File "/home/galen/anaconda3/lib/python3.6/site-packages/ipykernel/ipkernel.py", line 208, in do_execute
    res = shell.run_cell(code, store_history=store_history, silent=silent)
  File "/home/galen/anaconda3/lib/python3.6/site-packages/ipykernel/zmqshell.py", line 537, in run_cell
    return super(ZMQInteractiveShell, self).run_cell(*args, **kwargs)
  File "/home/galen/anaconda3/lib/python3.6/site-packages/IPython/core/interactiveshell.py", line 2662, in run_cell
    raw_cell, store_history, silent, shell_futures)
  File "/home/galen/anaconda3/lib/python3.6/site-packages/IPython/core/interactiveshell.py", line 2785, in _run_cell
    interactivity=interactivity, compiler=compiler, result=result)
  File "/home/galen/anaconda3/lib/python3.6/site-packages/IPython/core/interactiveshell.py", line 2909, in run_ast_nodes
    if self.run_code(code, result):
  File "/home/galen/anaconda3/lib/python3.6/site-packages/IPython/core/interactiveshell.py", line 2963, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-27-f764a88bbadf>", line 1, in <module>
    shap_values = explainer.shap_values(X)
  File "/home/galen/anaconda3/lib/python3.6/site-packages/shap/explainers/deep/__init__.py", line 119, in shap_values
    return self.explainer.shap_values(X, ranked_outputs, output_rank_order)
  File "/home/galen/anaconda3/lib/python3.6/site-packages/shap/explainers/deep/deep_tf.py", line 262, in shap_values
    sample_phis = self.run(self.phi_symbolic(feature_ind), self.model_inputs, joint_input)
  File "/home/galen/anaconda3/lib/python3.6/site-packages/shap/explainers/deep/deep_tf.py", line 202, in phi_symbolic
    self.phi_symbolics[i] = tf.gradients(out, self.model_inputs)
  File "/home/galen/anaconda3/lib/python3.6/site-packages/tensorflow/python/ops/gradients_impl.py", line 630, in gradients
    gate_gradients, aggregation_method, stop_gradients)
  File "/home/galen/anaconda3/lib/python3.6/site-packages/tensorflow/python/ops/gradients_impl.py", line 698, in _GradientsHelper
    to_ops, from_ops, colocate_gradients_with_ops, func_graphs, xs)
  File "/home/galen/anaconda3/lib/python3.6/site-packages/tensorflow/python/ops/gradients_impl.py", line 194, in _PendingCount
    between_op_list, between_ops, colocate_gradients_with_ops)
  File "/home/galen/anaconda3/lib/python3.6/site-packages/tensorflow/python/ops/control_flow_ops.py", line 1445, in MaybeCreateControlFlowState
    loop_state.AddWhileContext(op, between_op_list, between_ops)
  File "/home/galen/anaconda3/lib/python3.6/site-packages/tensorflow/python/ops/control_flow_ops.py", line 1257, in AddWhileContext
    grad_state = GradLoopState(forward_ctxt, outer_grad_state)
  File "/home/galen/anaconda3/lib/python3.6/site-packages/tensorflow/python/ops/control_flow_ops.py", line 834, in __init__
    cnt, forward_index = forward_ctxt.AddForwardLoopCounter(outer_grad_state)
  File "/home/galen/anaconda3/lib/python3.6/site-packages/tensorflow/python/ops/control_flow_ops.py", line 2583, in AddForwardLoopCounter
    name="f_count")
  File "/home/galen/anaconda3/lib/python3.6/site-packages/tensorflow/python/ops/control_flow_ops.py", line 258, in _Enter
    data, frame_name, is_constant, parallel_iterations, name=name)
  File "/home/galen/anaconda3/lib/python3.6/site-packages/tensorflow/python/ops/gen_control_flow_ops.py", line 179, in enter
    parallel_iterations=parallel_iterations, name=name)
  File "/home/galen/anaconda3/lib/python3.6/site-packages/tensorflow/python/framework/op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File "/home/galen/anaconda3/lib/python3.6/site-packages/tensorflow/python/util/deprecation.py", line 488, in new_func
    return func(*args, **kwargs)
  File "/home/galen/anaconda3/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 3274, in create_op
    op_def=op_def)
  File "/home/galen/anaconda3/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 1770, in __init__
    self._traceback = tf_stack.extract_stack()

Traceback for gradients_2/f_count:
  File "/home/galen/anaconda3/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/galen/anaconda3/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/galen/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py", line 16, in <module>
    app.launch_new_instance()
  File "/home/galen/anaconda3/lib/python3.6/site-packages/traitlets/config/application.py", line 658, in launch_instance
    app.start()
  File "/home/galen/anaconda3/lib/python3.6/site-packages/ipykernel/kernelapp.py", line 486, in start
    self.io_loop.start()
  File "/home/galen/anaconda3/lib/python3.6/site-packages/tornado/platform/asyncio.py", line 127, in start
    self.asyncio_loop.run_forever()
  File "/home/galen/anaconda3/lib/python3.6/asyncio/base_events.py", line 422, in run_forever
    self._run_once()
  File "/home/galen/anaconda3/lib/python3.6/asyncio/base_events.py", line 1432, in _run_once
    handle._run()
  File "/home/galen/anaconda3/lib/python3.6/asyncio/events.py", line 145, in _run
    self._callback(*self._args)
  File "/home/galen/anaconda3/lib/python3.6/site-packages/tornado/platform/asyncio.py", line 117, in _handle_events
    handler_func(fileobj, events)
  File "/home/galen/anaconda3/lib/python3.6/site-packages/tornado/stack_context.py", line 276, in null_wrapper
    return fn(*args, **kwargs)
  File "/home/galen/anaconda3/lib/python3.6/site-packages/zmq/eventloop/zmqstream.py", line 450, in _handle_events
    self._handle_recv()
  File "/home/galen/anaconda3/lib/python3.6/site-packages/zmq/eventloop/zmqstream.py", line 480, in _handle_recv
    self._run_callback(callback, msg)
  File "/home/galen/anaconda3/lib/python3.6/site-packages/zmq/eventloop/zmqstream.py", line 432, in _run_callback
    callback(*args, **kwargs)
  File "/home/galen/anaconda3/lib/python3.6/site-packages/tornado/stack_context.py", line 276, in null_wrapper
    return fn(*args, **kwargs)
  File "/home/galen/anaconda3/lib/python3.6/site-packages/ipykernel/kernelbase.py", line 283, in dispatcher
    return self.dispatch_shell(stream, msg)
  File "/home/galen/anaconda3/lib/python3.6/site-packages/ipykernel/kernelbase.py", line 233, in dispatch_shell
    handler(stream, idents, msg)
  File "/home/galen/anaconda3/lib/python3.6/site-packages/ipykernel/kernelbase.py", line 399, in execute_request
    user_expressions, allow_stdin)
  File "/home/galen/anaconda3/lib/python3.6/site-packages/ipykernel/ipkernel.py", line 208, in do_execute
    res = shell.run_cell(code, store_history=store_history, silent=silent)
  File "/home/galen/anaconda3/lib/python3.6/site-packages/ipykernel/zmqshell.py", line 537, in run_cell
    return super(ZMQInteractiveShell, self).run_cell(*args, **kwargs)
  File "/home/galen/anaconda3/lib/python3.6/site-packages/IPython/core/interactiveshell.py", line 2662, in run_cell
    raw_cell, store_history, silent, shell_futures)
  File "/home/galen/anaconda3/lib/python3.6/site-packages/IPython/core/interactiveshell.py", line 2785, in _run_cell
    interactivity=interactivity, compiler=compiler, result=result)
  File "/home/galen/anaconda3/lib/python3.6/site-packages/IPython/core/interactiveshell.py", line 2909, in run_ast_nodes
    if self.run_code(code, result):
  File "/home/galen/anaconda3/lib/python3.6/site-packages/IPython/core/interactiveshell.py", line 2963, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-27-f764a88bbadf>", line 1, in <module>
    shap_values = explainer.shap_values(X)
  File "/home/galen/anaconda3/lib/python3.6/site-packages/shap/explainers/deep/__init__.py", line 119, in shap_values
    return self.explainer.shap_values(X, ranked_outputs, output_rank_order)
  File "/home/galen/anaconda3/lib/python3.6/site-packages/shap/explainers/deep/deep_tf.py", line 262, in shap_values
    sample_phis = self.run(self.phi_symbolic(feature_ind), self.model_inputs, joint_input)
  File "/home/galen/anaconda3/lib/python3.6/site-packages/shap/explainers/deep/deep_tf.py", line 202, in phi_symbolic
    self.phi_symbolics[i] = tf.gradients(out, self.model_inputs)
  File "/home/galen/anaconda3/lib/python3.6/site-packages/tensorflow/python/ops/gradients_impl.py", line 630, in gradients
    gate_gradients, aggregation_method, stop_gradients)
  File "/home/galen/anaconda3/lib/python3.6/site-packages/tensorflow/python/ops/gradients_impl.py", line 698, in _GradientsHelper
    to_ops, from_ops, colocate_gradients_with_ops, func_graphs, xs)
  File "/home/galen/anaconda3/lib/python3.6/site-packages/tensorflow/python/ops/gradients_impl.py", line 194, in _PendingCount
    between_op_list, between_ops, colocate_gradients_with_ops)
  File "/home/galen/anaconda3/lib/python3.6/site-packages/tensorflow/python/ops/control_flow_ops.py", line 1445, in MaybeCreateControlFlowState
    loop_state.AddWhileContext(op, between_op_list, between_ops)
  File "/home/galen/anaconda3/lib/python3.6/site-packages/tensorflow/python/ops/control_flow_ops.py", line 1257, in AddWhileContext
    grad_state = GradLoopState(forward_ctxt, outer_grad_state)
  File "/home/galen/anaconda3/lib/python3.6/site-packages/tensorflow/python/ops/control_flow_ops.py", line 834, in __init__
    cnt, forward_index = forward_ctxt.AddForwardLoopCounter(outer_grad_state)
  File "/home/galen/anaconda3/lib/python3.6/site-packages/tensorflow/python/ops/control_flow_ops.py", line 2569, in AddForwardLoopCounter
    n = constant_op.constant(0, name="f_count")
  File "/home/galen/anaconda3/lib/python3.6/site-packages/tensorflow/python/framework/constant_op.py", line 214, in constant
    name=name).outputs[0]
  File "/home/galen/anaconda3/lib/python3.6/site-packages/tensorflow/python/util/deprecation.py", line 488, in new_func
    return func(*args, **kwargs)
  File "/home/galen/anaconda3/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 3274, in create_op
    op_def=op_def)
  File "/home/galen/anaconda3/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 1770, in __init__
    self._traceback = tf_stack.extract_stack()

---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-27-f764a88bbadf> in <module>()
----> 1 shap_values = explainer.shap_values(X)

~/anaconda3/lib/python3.6/site-packages/shap/explainers/deep/__init__.py in shap_values(self, X, ranked_outputs, output_rank_order)
    117         were chosen as "top".
    118         """
--> 119         return self.explainer.shap_values(X, ranked_outputs, output_rank_order)

~/anaconda3/lib/python3.6/site-packages/shap/explainers/deep/deep_tf.py in shap_values(self, X, ranked_outputs, output_rank_order)
    260                 # run attribution computation graph
    261                 feature_ind = model_output_ranks[j,i]
--> 262                 sample_phis = self.run(self.phi_symbolic(feature_ind), self.model_inputs, joint_input)
    263 
    264                 # assign the attributions to the right part of the output arrays

~/anaconda3/lib/python3.6/site-packages/shap/explainers/deep/deep_tf.py in phi_symbolic(self, i)
    200             try:
    201                 out = self.model_output[:,i] if self.multi_output else self.model_output
--> 202                 self.phi_symbolics[i] = tf.gradients(out, self.model_inputs)
    203 
    204             finally:

~/anaconda3/lib/python3.6/site-packages/tensorflow/python/ops/gradients_impl.py in gradients(ys, xs, grad_ys, name, colocate_gradients_with_ops, gate_gradients, aggregation_method, stop_gradients)
    628   with ops.get_default_graph()._mutation_lock():  # pylint: disable=protected-access
    629     return _GradientsHelper(ys, xs, grad_ys, name, colocate_gradients_with_ops,
--> 630                             gate_gradients, aggregation_method, stop_gradients)
    631 
    632 

~/anaconda3/lib/python3.6/site-packages/tensorflow/python/ops/gradients_impl.py in _GradientsHelper(ys, xs, grad_ys, name, colocate_gradients_with_ops, gate_gradients, aggregation_method, stop_gradients, src_graph)
    696     stop_gradient_ops = [t.op for t in stop_gradients]
    697     reachable_to_ops, pending_count, loop_state = _PendingCount(
--> 698         to_ops, from_ops, colocate_gradients_with_ops, func_graphs, xs)
    699 
    700     # Iterate over the collected ops.

~/anaconda3/lib/python3.6/site-packages/tensorflow/python/ops/gradients_impl.py in _PendingCount(to_ops, from_ops, colocate_gradients_with_ops, func_graphs, xs)
    192   # 'loop_state' is None if there are no while loops.
    193   loop_state = control_flow_ops.MaybeCreateControlFlowState(
--> 194       between_op_list, between_ops, colocate_gradients_with_ops)
    195 
    196   # Initialize pending count for between ops.

~/anaconda3/lib/python3.6/site-packages/tensorflow/python/ops/control_flow_ops.py in MaybeCreateControlFlowState(between_op_list, between_ops, colocate_gradients_with_ops)
   1443           loop_state.AddWhileContext(op, between_op_list, between_ops)
   1444       else:
-> 1445         loop_state.AddWhileContext(op, between_op_list, between_ops)
   1446   return loop_state
   1447 

~/anaconda3/lib/python3.6/site-packages/tensorflow/python/ops/control_flow_ops.py in AddWhileContext(self, op, between_op_list, between_ops)
   1255       if outer_forward_ctxt:
   1256         outer_grad_state = self._map.get(outer_forward_ctxt)
-> 1257       grad_state = GradLoopState(forward_ctxt, outer_grad_state)
   1258       self._map[forward_ctxt] = grad_state
   1259 

~/anaconda3/lib/python3.6/site-packages/tensorflow/python/ops/control_flow_ops.py in __init__(self, forward_ctxt, outer_grad_state)
    832       if outer_forward_ctxt:
    833         outer_forward_ctxt.Enter()
--> 834       cnt, forward_index = forward_ctxt.AddForwardLoopCounter(outer_grad_state)
    835       if outer_forward_ctxt:
    836         outer_forward_ctxt.Exit()

~/anaconda3/lib/python3.6/site-packages/tensorflow/python/ops/control_flow_ops.py in AddForwardLoopCounter(self, outer_grad_state)
   2581         is_constant=False,
   2582         parallel_iterations=self._parallel_iterations,
-> 2583         name="f_count")
   2584     self.loop_enters.append(enter_n)
   2585 

~/anaconda3/lib/python3.6/site-packages/tensorflow/python/ops/control_flow_ops.py in _Enter(data, frame_name, is_constant, parallel_iterations, use_ref, use_input_shape, name)
    256     else:
    257       result = gen_control_flow_ops.enter(
--> 258           data, frame_name, is_constant, parallel_iterations, name=name)
    259     if use_input_shape:
    260       result.set_shape(data.get_shape())

~/anaconda3/lib/python3.6/site-packages/tensorflow/python/ops/gen_control_flow_ops.py in enter(data, frame_name, is_constant, parallel_iterations, name)
    177     _, _, _op = _op_def_lib._apply_op_helper(
    178         "Enter", data=data, frame_name=frame_name, is_constant=is_constant,
--> 179         parallel_iterations=parallel_iterations, name=name)
    180     _result = _op.outputs[:]
    181     _inputs_flat = _op.inputs

~/anaconda3/lib/python3.6/site-packages/tensorflow/python/framework/op_def_library.py in _apply_op_helper(self, op_type_name, name, **keywords)
    785         op = g.create_op(op_type_name, inputs, output_types, name=scope,
    786                          input_types=input_types, attrs=attr_protos,
--> 787                          op_def=op_def)
    788       return output_structure, op_def.is_stateful, op
    789 

~/anaconda3/lib/python3.6/site-packages/tensorflow/python/util/deprecation.py in new_func(*args, **kwargs)
    486                 'in a future version' if date is None else ('after %s' % date),
    487                 instructions)
--> 488       return func(*args, **kwargs)
    489     return tf_decorator.make_decorator(func, new_func, 'deprecated',
    490                                        _add_deprecated_arg_notice_to_docstring(

~/anaconda3/lib/python3.6/site-packages/tensorflow/python/framework/ops.py in create_op(***failed resolving arguments***)
   3272           input_types=input_types,
   3273           original_op=self._default_original_op,
-> 3274           op_def=op_def)
   3275       self._create_op_helper(ret, compute_device=compute_device)
   3276     return ret

~/anaconda3/lib/python3.6/site-packages/tensorflow/python/framework/ops.py in __init__(self, node_def, g, inputs, output_types, control_inputs, input_types, original_op, op_def)
   1805 
   1806     if not c_op:
-> 1807       self._control_flow_post_processing()
   1808 
   1809   def _control_flow_post_processing(self):

~/anaconda3/lib/python3.6/site-packages/tensorflow/python/framework/ops.py in _control_flow_post_processing(self)
   1814     """
   1815     for input_tensor in self.inputs:
-> 1816       control_flow_util.CheckInputFromValidContext(self, input_tensor.op)
   1817     if self._control_flow_context is not None:
   1818       self._control_flow_context.AddOp(self)

~/anaconda3/lib/python3.6/site-packages/tensorflow/python/ops/control_flow_util.py in CheckInputFromValidContext(op, input_op)
    320         input_op.name, "".join(traceback.format_list(input_op.traceback)))
    321     logging.info(log_msg)
--> 322     raise ValueError(error_msg + " See info log for more details.")

ValueError: Cannot use 'gradients_2/f_count_1' as input to 'gradients_2/f_count' because they are in different while loops. See info log for more details.

'

**Comment by detrin** [comment]
@galenwilkerson Could you provide minimal example that would reproduce the error? Please also show output of `pip freeze`, prepare the example in a separated environment and share the version of python. Just keep in mind that python3.6 is no longer supported by this package.
