### ISSUE TITLE
ImportError: No module named '_tkinter'

### ISSUE THREAD

**Issue by hammurabi-ds** [shap/shap#551]
Hi. Im using your package on a remote and i get the following error 

`
Traceback (most recent call last):
  File "/usr/lib/python3.5/tkinter/__init__.py", line 36, in <module>
    import _tkinter
ImportError: No module named '_tkinter'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/user/.local/lib/python3.5/site-packages/shap/plots/summary.py", line 10, in <module>
    import matplotlib.pyplot as pl
  File "/usr/local/lib/python3.5/dist-packages/matplotlib/pyplot.py", line 115, in <module>
    _backend_mod, new_figure_manager, draw_if_interactive, _show = pylab_setup()
  File "/usr/local/lib/python3.5/dist-packages/matplotlib/backends/__init__.py", line 62, in pylab_setup
    [backend_name], 0)
  File "/usr/local/lib/python3.5/dist-packages/matplotlib/backends/backend_tkagg.py", line 4, in <module>
    from . import tkagg  # Paint image to Tk photo blitter extension.
  File "/usr/local/lib/python3.5/dist-packages/matplotlib/backends/tkagg.py", line 5, in <module>
    from six.moves import tkinter as Tk
  File "/usr/local/lib/python3.5/dist-packages/six.py", line 92, in __get__
    result = self._resolve()
  File "/usr/local/lib/python3.5/dist-packages/six.py", line 115, in _resolve
    return _import_module(self.mod)
  File "/usr/local/lib/python3.5/dist-packages/six.py", line 82, in _import_module
    __import__(name)
  File "/usr/lib/python3.5/tkinter/__init__.py", line 38, in <module>
    raise ImportError(str(msg) + ', please install the python3-tk package')
ImportError: No module named '_tkinter', please install the python3-tk package

During handling of the above exception, another exception occurred:

###

  File "/home/user/.local/lib/python3.5/site-packages/shap/__init__.py", line 11, in <module>
    from .plots.summary import summary_plot
  File "/home/user/.local/lib/python3.5/site-packages/shap/plots/summary.py", line 12, in <module>
    warnings.warn("matplotlib could not be loaded!", e)
TypeError: category must be a Warning subclass, not 'ImportError'
`

This is perhaps problematic for some one working on a remote which does not have _tkinter. From the last lines it seems that there is a TypeError in the try pass code you write in summary.py.

**Comment by slundberg** [comment]
I think this is something #508 would help with since presumably the issue comes from trying to import the plotting code on a system without support for it.
