### ISSUE TITLE
Multi-input CNN architecture

### ISSUE THREAD

**Issue by johnnypetr** [shap/shap#559]
Hello,
I tried to use SHAP for a multi-input (single output) classification architecture consisting of three CNN branches. However, I wasn't very successful with the code as I couldn't find a similar case.

The closest scenario seems to be here (due to the fact that a list of image can be parsed into the interpretation model): https://github.com/slundberg/shap/blob/master/notebooks/gradient_explainer/Explain%20an%20Intermediate%20Layer%20of%20VGG16%20on%20ImageNet%20(PyTorch).ipynb

However, the idea behind the classification is very different as my architecture aims to predict a class (0/1 - non-churning customer/churning customer) based on three sets of data (demographic data, transactional data and behavioral data) all represented in heatmaps.

Hence my question: is it possible to use SHAP for a multi-input CNN architecture?

The architecture looks like as follows: https://pasteboard.co/IbkV0lO.png
 
Thank you.

**Comment by slundberg** [comment]
It should be fine to use multiple inputs. You can just pass a list of inputs when you have multiple inputs (and a corresponding list of background datasets).

**Comment by johnnypetr** [comment]
I've tried to run DeepExplainer with the following code:

```
background = [bg_members,bg_transactions,bg_user_logs]
x_test = [members_test[0:2],transactions_test[0:2],user_logs_test[0:2]]

e = shap.DeepExplainer(model, background)
shap_values = e.shap_values(x_test)

shap.image_plot(shap_values, -x_test)
```

where the inputs in _background_ are numpy arrays of rgb arrays with the shape (300, 61, 4, 3), (300, 61, 39, 3) and (300, 61, 7, 3), respectively. And _x_test_ are corresponding inputs with the shapes (2, 61, 4, 3), (2, 61, 39, 3) and (2, 61, 7, 3).

I am receiving the following error:
```

InvalidArgumentError                      Traceback (most recent call last)
C:\ProgramData\Anaconda3\envs\caldiss\lib\site-packages\tensorflow\python\client\session.py in _do_call(self, fn, *args)
   1333     try:
-> 1334       return fn(*args)
   1335     except errors.OpError as e:

C:\ProgramData\Anaconda3\envs\caldiss\lib\site-packages\tensorflow\python\client\session.py in _run_fn(feed_dict, fetch_list, target_list, options, run_metadata)
   1318       return self._call_tf_sessionrun(
-> 1319           options, feed_dict, fetch_list, target_list, run_metadata)
   1320 

C:\ProgramData\Anaconda3\envs\caldiss\lib\site-packages\tensorflow\python\client\session.py in _call_tf_sessionrun(self, options, feed_dict, fetch_list, target_list, run_metadata)
   1406         self._session, options, feed_dict, fetch_list, target_list,
-> 1407         run_metadata)
   1408 

InvalidArgumentError: Incompatible shapes: [600,32] vs. [600,1,300,32]
	 [[{{node gradients_8/global_max_pooling2d_1/Max_grad/mul_1}}]]

During handling of the above exception, another exception occurred:

InvalidArgumentError                      Traceback (most recent call last)
<ipython-input-97-a3d786497def> in <module>
      3 
      4 e = shap.DeepExplainer(model, background)
----> 5 shap_values = e.shap_values(x_test)
      6 
      7 shap.image_plot(shap_values, -x_test)

C:\ProgramData\Anaconda3\envs\caldiss\lib\site-packages\shap\explainers\deep\__init__.py in shap_values(self, X, ranked_outputs, output_rank_order)
    117         were chosen as "top".
    118         """
--> 119         return self.explainer.shap_values(X, ranked_outputs, output_rank_order)

C:\ProgramData\Anaconda3\envs\caldiss\lib\site-packages\shap\explainers\deep\deep_tf.py in shap_values(self, X, ranked_outputs, output_rank_order)
    260                 # run attribution computation graph
    261                 feature_ind = model_output_ranks[j,i]
--> 262                 sample_phis = self.run(self.phi_symbolic(feature_ind), self.model_inputs, joint_input)
    263 
    264                 # assign the attributions to the right part of the output arrays

C:\ProgramData\Anaconda3\envs\caldiss\lib\site-packages\shap\explainers\deep\deep_tf.py in run(self, out, model_inputs, X)
    280         for t in self.learning_phase_flags:
    281             feed_dict[t] = False
--> 282         return self.session.run(out, feed_dict)
    283 
    284     def custom_grad(self, op, *grads):

C:\ProgramData\Anaconda3\envs\caldiss\lib\site-packages\tensorflow\python\client\session.py in run(self, fetches, feed_dict, options, run_metadata)
    927     try:
    928       result = self._run(None, fetches, feed_dict, options_ptr,
--> 929                          run_metadata_ptr)
    930       if run_metadata:
    931         proto_data = tf_session.TF_GetBuffer(run_metadata_ptr)

C:\ProgramData\Anaconda3\envs\caldiss\lib\site-packages\tensorflow\python\client\session.py in _run(self, handle, fetches, feed_dict, options, run_metadata)
   1150     if final_fetches or final_targets or (handle and feed_dict_tensor):
   1151       results = self._do_run(handle, final_targets, final_fetches,
-> 1152                              feed_dict_tensor, options, run_metadata)
   1153     else:
   1154       results = []

C:\ProgramData\Anaconda3\envs\caldiss\lib\site-packages\tensorflow\python\client\session.py in _do_run(self, handle, target_list, fetch_list, feed_dict, options, run_metadata)
   1326     if handle is None:
   1327       return self._do_call(_run_fn, feeds, fetches, targets, options,
-> 1328                            run_metadata)
   1329     else:
   1330       return self._do_call(_prun_fn, handle, feeds, fetches)

C:\ProgramData\Anaconda3\envs\caldiss\lib\site-packages\tensorflow\python\client\session.py in _do_call(self, fn, *args)
   1346           pass
   1347       message = error_interpolation.interpolate(message, self._graph)
-> 1348       raise type(e)(node_def, op, message)
   1349 
   1350   def _extend_graph(self):

InvalidArgumentError: Incompatible shapes: [600,32] vs. [600,1,300,32]
	 [[node gradients_8/global_max_pooling2d_1/Max_grad/mul_1 (defined at C:\ProgramData\Anaconda3\envs\caldiss\lib\site-packages\shap\explainers\deep\deep_tf.py:450) ]]

Caused by op 'gradients_8/global_max_pooling2d_1/Max_grad/mul_1', defined at:
  File "C:\ProgramData\Anaconda3\envs\caldiss\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\ProgramData\Anaconda3\envs\caldiss\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\ProgramData\Anaconda3\envs\caldiss\lib\site-packages\ipykernel_launcher.py", line 16, in <module>
    app.launch_new_instance()
  File "C:\ProgramData\Anaconda3\envs\caldiss\lib\site-packages\traitlets\config\application.py", line 658, in launch_instance
    app.start()
  File "C:\ProgramData\Anaconda3\envs\caldiss\lib\site-packages\ipykernel\kernelapp.py", line 505, in start
    self.io_loop.start()
  File "C:\ProgramData\Anaconda3\envs\caldiss\lib\site-packages\tornado\platform\asyncio.py", line 132, in start
    self.asyncio_loop.run_forever()
  File "C:\ProgramData\Anaconda3\envs\caldiss\lib\asyncio\base_events.py", line 427, in run_forever
    self._run_once()
  File "C:\ProgramData\Anaconda3\envs\caldiss\lib\asyncio\base_events.py", line 1440, in _run_once
    handle._run()
  File "C:\ProgramData\Anaconda3\envs\caldiss\lib\asyncio\events.py", line 145, in _run
    self._callback(*self._args)
  File "C:\ProgramData\Anaconda3\envs\caldiss\lib\site-packages\tornado\ioloop.py", line 758, in _run_callback
    ret = callback()
  File "C:\ProgramData\Anaconda3\envs\caldiss\lib\site-packages\tornado\stack_context.py", line 300, in null_wrapper
    return fn(*args, **kwargs)
  File "C:\ProgramData\Anaconda3\envs\caldiss\lib\site-packages\tornado\gen.py", line 1233, in inner
    self.run()
  File "C:\ProgramData\Anaconda3\envs\caldiss\lib\site-packages\tornado\gen.py", line 1147, in run
    yielded = self.gen.send(value)
  File "C:\ProgramData\Anaconda3\envs\caldiss\lib\site-packages\ipykernel\kernelbase.py", line 357, in process_one
    yield gen.maybe_future(dispatch(*args))
  File "C:\ProgramData\Anaconda3\envs\caldiss\lib\site-packages\tornado\gen.py", line 326, in wrapper
    yielded = next(result)
  File "C:\ProgramData\Anaconda3\envs\caldiss\lib\site-packages\ipykernel\kernelbase.py", line 267, in dispatch_shell
    yield gen.maybe_future(handler(stream, idents, msg))
  File "C:\ProgramData\Anaconda3\envs\caldiss\lib\site-packages\tornado\gen.py", line 326, in wrapper
    yielded = next(result)
  File "C:\ProgramData\Anaconda3\envs\caldiss\lib\site-packages\ipykernel\kernelbase.py", line 534, in execute_request
    user_expressions, allow_stdin,
  File "C:\ProgramData\Anaconda3\envs\caldiss\lib\site-packages\tornado\gen.py", line 326, in wrapper
    yielded = next(result)
  File "C:\ProgramData\Anaconda3\envs\caldiss\lib\site-packages\ipykernel\ipkernel.py", line 294, in do_execute
    res = shell.run_cell(code, store_history=store_history, silent=silent)
  File "C:\ProgramData\Anaconda3\envs\caldiss\lib\site-packages\ipykernel\zmqshell.py", line 536, in run_cell
    return super(ZMQInteractiveShell, self).run_cell(*args, **kwargs)
  File "C:\ProgramData\Anaconda3\envs\caldiss\lib\site-packages\IPython\core\interactiveshell.py", line 2819, in run_cell
    raw_cell, store_history, silent, shell_futures)
  File "C:\ProgramData\Anaconda3\envs\caldiss\lib\site-packages\IPython\core\interactiveshell.py", line 2845, in _run_cell
    return runner(coro)
  File "C:\ProgramData\Anaconda3\envs\caldiss\lib\site-packages\IPython\core\async_helpers.py", line 67, in _pseudo_sync_runner
    coro.send(None)
  File "C:\ProgramData\Anaconda3\envs\caldiss\lib\site-packages\IPython\core\interactiveshell.py", line 3020, in run_cell_async
    interactivity=interactivity, compiler=compiler, result=result)
  File "C:\ProgramData\Anaconda3\envs\caldiss\lib\site-packages\IPython\core\interactiveshell.py", line 3185, in run_ast_nodes
    if (yield from self.run_code(code, result)):
  File "C:\ProgramData\Anaconda3\envs\caldiss\lib\site-packages\IPython\core\interactiveshell.py", line 3267, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-97-a3d786497def>", line 5, in <module>
    shap_values = e.shap_values(x_test)
  File "C:\ProgramData\Anaconda3\envs\caldiss\lib\site-packages\shap\explainers\deep\__init__.py", line 119, in shap_values
    return self.explainer.shap_values(X, ranked_outputs, output_rank_order)
  File "C:\ProgramData\Anaconda3\envs\caldiss\lib\site-packages\shap\explainers\deep\deep_tf.py", line 262, in shap_values
    sample_phis = self.run(self.phi_symbolic(feature_ind), self.model_inputs, joint_input)
  File "C:\ProgramData\Anaconda3\envs\caldiss\lib\site-packages\shap\explainers\deep\deep_tf.py", line 202, in phi_symbolic
    self.phi_symbolics[i] = tf.gradients(out, self.model_inputs)
  File "C:\ProgramData\Anaconda3\envs\caldiss\lib\site-packages\tensorflow\python\ops\gradients_impl.py", line 664, in gradients
    unconnected_gradients)
  File "C:\ProgramData\Anaconda3\envs\caldiss\lib\site-packages\tensorflow\python\ops\gradients_impl.py", line 965, in _GradientsHelper
    lambda: grad_fn(op, *out_grads))
  File "C:\ProgramData\Anaconda3\envs\caldiss\lib\site-packages\tensorflow\python\ops\gradients_impl.py", line 420, in _MaybeCompile
    return grad_fn()  # Exit early
  File "C:\ProgramData\Anaconda3\envs\caldiss\lib\site-packages\tensorflow\python\ops\gradients_impl.py", line 965, in <lambda>
    lambda: grad_fn(op, *out_grads))
  File "C:\ProgramData\Anaconda3\envs\caldiss\lib\site-packages\shap\explainers\deep\deep_tf.py", line 287, in custom_grad
    return op_handlers[op.type](self, op, *grads)
  File "C:\ProgramData\Anaconda3\envs\caldiss\lib\site-packages\shap\explainers\deep\deep_tf.py", line 431, in handler
    return nonlinearity_1d_handler(input_ind, explainer, op, *grads)
  File "C:\ProgramData\Anaconda3\envs\caldiss\lib\site-packages\shap\explainers\deep\deep_tf.py", line 450, in nonlinearity_1d_handler
    grads[0] * tf.tile((xout - rout) / delta_in0, dup0)
  File "C:\ProgramData\Anaconda3\envs\caldiss\lib\site-packages\tensorflow\python\ops\math_ops.py", line 812, in binary_op_wrapper
    return func(x, y, name=name)
  File "C:\ProgramData\Anaconda3\envs\caldiss\lib\site-packages\tensorflow\python\ops\math_ops.py", line 1078, in _mul_dispatch
    return gen_math_ops.mul(x, y, name=name)
  File "C:\ProgramData\Anaconda3\envs\caldiss\lib\site-packages\tensorflow\python\ops\gen_math_ops.py", line 6175, in mul
    "Mul", x=x, y=y, name=name)
  File "C:\ProgramData\Anaconda3\envs\caldiss\lib\site-packages\tensorflow\python\framework\op_def_library.py", line 788, in _apply_op_helper
    op_def=op_def)
  File "C:\ProgramData\Anaconda3\envs\caldiss\lib\site-packages\tensorflow\python\util\deprecation.py", line 507, in new_func
    return func(*args, **kwargs)
  File "C:\ProgramData\Anaconda3\envs\caldiss\lib\site-packages\tensorflow\python\framework\ops.py", line 3300, in create_op
    op_def=op_def)
  File "C:\ProgramData\Anaconda3\envs\caldiss\lib\site-packages\tensorflow\python\framework\ops.py", line 1801, in __init__
    self._traceback = tf_stack.extract_stack()

...which was originally created as op 'global_max_pooling2d_1/Max', defined at:
  File "C:\ProgramData\Anaconda3\envs\caldiss\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
[elided 25 identical lines from previous traceback]
  File "C:\ProgramData\Anaconda3\envs\caldiss\lib\site-packages\IPython\core\interactiveshell.py", line 3267, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-14-3a07225b4861>", line 5, in <module>
    x1 = GlobalMaxPooling2D()(x1)
  File "C:\ProgramData\Anaconda3\envs\caldiss\lib\site-packages\keras\engine\base_layer.py", line 457, in __call__
    output = self.call(inputs, **kwargs)
  File "C:\ProgramData\Anaconda3\envs\caldiss\lib\site-packages\keras\layers\pooling.py", line 677, in call
    return K.max(inputs, axis=[1, 2])
  File "C:\ProgramData\Anaconda3\envs\caldiss\lib\site-packages\keras\backend\tensorflow_backend.py", line 1250, in max
    return tf.reduce_max(x, axis, keepdims)
  File "C:\ProgramData\Anaconda3\envs\caldiss\lib\site-packages\tensorflow\python\util\deprecation.py", line 507, in new_func
    return func(*args, **kwargs)
  File "C:\ProgramData\Anaconda3\envs\caldiss\lib\site-packages\tensorflow\python\ops\math_ops.py", line 1887, in reduce_max_v1
    return reduce_max(input_tensor, axis, keepdims, name)
  File "C:\ProgramData\Anaconda3\envs\caldiss\lib\site-packages\tensorflow\python\util\dispatch.py", line 180, in wrapper
    return target(*args, **kwargs)
  File "C:\ProgramData\Anaconda3\envs\caldiss\lib\site-packages\tensorflow\python\ops\math_ops.py", line 1923, in reduce_max
    name=name))
  File "C:\ProgramData\Anaconda3\envs\caldiss\lib\site-packages\tensorflow\python\ops\gen_math_ops.py", line 5715, in _max
    name=name)
  File "C:\ProgramData\Anaconda3\envs\caldiss\lib\site-packages\tensorflow\python\framework\op_def_library.py", line 788, in _apply_op_helper
    op_def=op_def)
  File "C:\ProgramData\Anaconda3\envs\caldiss\lib\site-packages\tensorflow\python\util\deprecation.py", line 507, in new_func
    return func(*args, **kwargs)
  File "C:\ProgramData\Anaconda3\envs\caldiss\lib\site-packages\tensorflow\python\framework\ops.py", line 3300, in create_op
    op_def=op_def)
  File "C:\ProgramData\Anaconda3\envs\caldiss\lib\site-packages\tensorflow\python\framework\ops.py", line 1801, in __init__
    self._traceback = tf_stack.extract_stack()

InvalidArgumentError (see above for traceback): Incompatible shapes: [600,32] vs. [600,1,300,32]
	 [[node gradients_8/global_max_pooling2d_1/Max_grad/mul_1 (defined at C:\ProgramData\Anaconda3\envs\caldiss\lib\site-packages\shap\explainers\deep\deep_tf.py:450) ]]`
```

**Comment by johnnypetr** [comment]
And when trying GradientExplainer, with the following code (the input is the same as in the previous case):
```
X = [bg_members,bg_transactions,bg_user_logs]
to_explain = [members_test[0:2],transactions_test[0:2],user_logs_test[0:2]]
y = to_categorical(msno_list["is_churn"][0:300])

def map2layer(x, layer):
    feed_dict = dict(zip([model.layers[0].input], [preprocess_input(x.copy())]))
    return K.get_session().run(model.layers[layer].input, feed_dict)

explainer = shap.GradientExplainer(
    (model.layers[7].input, model.layers[-1].output),
    map2layer(preprocess_input(X.copy()), 7),
    local_smoothing=100
)

shap_values,indexes = explainer.shap_values(map2layer(to_explain, 7), ranked_outputs=2)

index_names = np.vectorize(lambda x: class_names[str(x)][1])(indexes)

shap.image_plot(shap_values, to_explain, index_names)
```
and I am getting the following error:
```
TypeError                                 Traceback (most recent call last)
<ipython-input-92-0a3be7c82c18> in <module>
     10 explainer = shap.GradientExplainer(
     11     (model.layers[7].input, model.layers[-1].output),
---> 12     map2layer(preprocess_input(X.copy()), 7),
     13     local_smoothing=100
     14 )

C:\ProgramData\Anaconda3\envs\caldiss\lib\site-packages\keras\applications\__init__.py in wrapper(*args, **kwargs)
     26             kwargs['models'] = models
     27             kwargs['utils'] = utils
---> 28         return base_fun(*args, **kwargs)
     29 
     30     return wrapper

C:\ProgramData\Anaconda3\envs\caldiss\lib\site-packages\keras\applications\vgg16.py in preprocess_input(*args, **kwargs)
     19 @keras_modules_injection
     20 def preprocess_input(*args, **kwargs):
---> 21     return vgg16.preprocess_input(*args, **kwargs)

C:\ProgramData\Anaconda3\envs\caldiss\lib\site-packages\keras_applications\imagenet_utils.py in preprocess_input(x, data_format, mode, **kwargs)
    193     else:
    194         return _preprocess_symbolic_input(x, data_format=data_format,
--> 195                                           mode=mode, **kwargs)
    196 
    197 

C:\ProgramData\Anaconda3\envs\caldiss\lib\site-packages\keras_applications\imagenet_utils.py in _preprocess_symbolic_input(x, data_format, mode, **kwargs)
    136         else:
    137             # 'RGB'->'BGR'
--> 138             x = x[..., ::-1]
    139         mean = [103.939, 116.779, 123.68]
    140         std = None

TypeError: list indices must be integers or slices, not tuple
```
Am I doing something wrong?

**Comment by XinyuanHu** [comment]
@johnnypetr I run into the same incompatible shape error you had but with a LSTM model. Were you able to figure out what went wrong?

**Comment by jlevy44** [comment]
Can you do this with pytorch?

**Comment by slundberg** [comment]
Sorry for the slow reply here. Would you be kind enough to share a simple TF/Keras example where this is failing so I can rerun it and debug?

**Comment by alialamiidrissi** [comment]
The error comes from some global max pooling operation which collapses one dimension and create a problem during the custom gradient computation.

**Comment by XinyuanHu** [comment]
@alialamiidrissi I was able to run shop after setting return sequence to false and delete the max pool layer

**Comment by alialamiidrissi** [comment]
> @alialamiidrissi I was able to run shop after setting return sequence to false and delete the max pool layer

I was also able to solve the issue by replacing K.max() by a maxpooling2D layer

**Comment by ghost** [comment]
@alialamiidrissi , @slundberg 
Hi guys,i solved the issue adding to GlobalMaxPooling1D and GlobalAveragePooling1D in function call 
```
from keras import backend as K

class GlobalMaxPooling1D_(GlobalMaxPooling1D):
    def call(self, inputs):
        steps_axis = 1 if self.data_format == 'channels_last' else 2
        return K.max(inputs, axis=steps_axis, keepdims=True)
    
    
class GlobalAveragePooling1D_(GlobalAveragePooling1D):
    def call(self, inputs, mask=None):
        steps_axis = 1 if self.data_format == 'channels_last' else 2
        return K.mean(inputs, axis=steps_axis, keepdims=True)
```
respectively. I am not sure how this might affect the gradient calculations, will keep testing it, would be nice to have a feedback from you as well.

**Comment by slundberg** [comment]
I am adding a bug tag here to note that this needs to be examined when I get a chance to reproduce it. If `keepdims=True` fixes the issues then it must be connected to dropping a dimension.

**Comment by ghost** [comment]
After few tests i realised that the shaps computed with that correction are not meaningful. Keeping the dimension messes up the gradient computation for the shaps for some reason. As a temporary solution, this worked for me :

```
max_pool1 = MaxPooling1D(pool_size=step_size, strides=1)(x)
max_pool1 = Lambda(lambda s: backend.squeeze(s, axis=1))(max_pool1)
```
which is the same as writing GlobalMaxPooling1D.

**Comment by candalfigomoro** [comment]
Same issue with GlobalMaxPooling1D

**Comment by MochizukiShinichi** [comment]
> After few tests i realised that the shaps computed with that correction are not meaningful. Keeping the dimension messes up the gradient computation for the shaps for some reason. As a temporary solution, this worked for me :
> 
> ```
> max_pool1 = MaxPooling1D(pool_size=step_size, strides=1)(x)
> max_pool1 = Lambda(lambda s: backend.squeeze(s, axis=1))(max_pool1)
> ```
> 
> which is the same as writing GlobalMaxPooling1D.

This works for me!

**Comment by slundberg** [comment]
I also added a multi-input example notebook for GradientExplainer at: https://github.com/slundberg/shap/blob/master/notebooks/gradient_explainer/Multi-input%20Gradient%20Explainer%20MNIST%20Example.ipynb

**Comment by jeremy-rutman** [comment]
Does the mutli-input compatibility hold also for plots?

**Comment by jmtatsch** [comment]
multi-input example notebook moved here now: https://github.com/slundberg/shap/blob/master/notebooks/image_examples/image_classification/Multi-input%20Gradient%20Explainer%20MNIST%20Example.ipynb

**Comment by HanyangLiu** [comment]
but it seems that GradientExplainer still does not work when the two inputs have different shape (e.g., one input is static features with shape N by D, the other one is time series N by D by T). Anyone has met the similar issue?

**Comment by ofiryaish** [comment]
The problem of using GlobalMaxPooling1D which returns an error still exists. 

InvalidArgumentError: Incompatible shapes: [2,512] vs. [2,110,512]
	 [[node gradients_20/global_max_pooling1d/Max_grad/mul_1 (defined at /users/agnon/year2016/yaishof/.conda/envs/ofir_env/lib/python3.6/site-packages/shap/explainers/_deep/deep_tf.py:608) ]]

I don't understand why it does that..
