### ISSUE TITLE
KernelExplainer for Multiclass XGBoost model - returns NaN Value Error

### ISSUE THREAD

**Issue by pogoetic** [shap/shap#577]
Hi - I love SHAP! So I have read that TreeExplainer does not currently handle Mutliclass XGBoost models with a 'probability' output type but thats what I'm trying to generate, so i'm trying to use SHAP with KernelExplainer. I have 3 classes and my input data for SHAP is a 100 row sample with no inf, -inf, or NaN. Ideally, I would see the SHAP plots add up to a probability of 1.0. 

However, I get this error: 

`ValueError: Input contains NaN, infinity or a value too large for dtype('float64').`

Here is a code snippet i'm working with: 
```
import shap

## kernel shap sends data as numpy array which has no column names, so we fix it
def xgb_predict(data_asarray):
    data_asframe =  pd.DataFrame(data_asarray, columns=X_train.columns)
    return model.predict(data_asframe)

explainer = shap.KernelExplainer(xgb_predict, link='logit', data=X_test.iloc[:100])
shap_values = explainer.shap_values(X_test.iloc[1])
shap.initjs()
shap.force_plot(explainer.expected_value[0], shap_values[0][0], X_test.iloc[1])
```

What am I doing wrong here? Is it the same issue as with TreeExplainer where the logit transform is not yet implemented in SHAP? Thank you!

**Comment by dp-dpo** [comment]
I get exactly the same error when using a KernelExplainer regardless of what link I use. Looks like something doesn't pass the infinity check in sklearn.
```
Traceback (most recent call last):
  File "C:\Users\user\AppData\Local\Continuum\anaconda3\envs\pycharm\lib\site-packages\IPython\core\interactiveshell.py", line 2963, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-707-1235e1045d56>", line 1, in <module>
    shap_values = explainer.shap_values(train_shap)
  File "C:\Users\user\AppData\Local\Continuum\anaconda3\envs\pycharm\lib\site-packages\shap\explainers\kernel.py", line 209, in shap_values
    explanations.append(self.explain(data, **kwargs))
  File "C:\Users\user\AppData\Local\Continuum\anaconda3\envs\pycharm\lib\site-packages\shap\explainers\kernel.py", line 405, in explain
    vphi, vphi_var = self.solve(self.nsamples / self.max_samples, d)
  File "C:\Users\user\AppData\Local\Continuum\anaconda3\envs\pycharm\lib\site-packages\shap\explainers\kernel.py", line 566, in solve
    nonzero_inds = np.nonzero(LassoLarsIC(criterion=c).fit(mask_aug, eyAdj_aug).coef_)[0]
  File "C:\Users\user\AppData\Local\Continuum\anaconda3\envs\pycharm\lib\site-packages\sklearn\linear_model\least_angle.py", line 1511, in fit
    X, y = check_X_y(X, y, y_numeric=True)
  File "C:\Users\user\AppData\Local\Continuum\anaconda3\envs\pycharm\lib\site-packages\sklearn\utils\validation.py", line 762, in check_X_y
    _assert_all_finite(y)
  File "C:\Users\user\AppData\Local\Continuum\anaconda3\envs\pycharm\lib\site-packages\sklearn\utils\validation.py", line 56, in _assert_all_finite
    raise ValueError(msg_err.format(type_err, X.dtype))
ValueError: Input contains NaN, infinity or a value too large for dtype('float64').
```

I wonder if something SHAP does might make the predict function return NaNs.
I have a binomial logit model from coefficients, the predict function works fine when applied to my data (fully numeric dense dataset), however due to the size I have to use shap.kmeans. Anyway, even on a small subset (like first 10 rows) I still get the NaN error.


```
import shap

def mw_predict(data_asarray):
    df = pd.DataFrame(data_asarray, columns=coef.Parameter.tolist())
    df = df.mul(coef.Estimate.values, axis=1)
    pred = np.divide(np.exp(df.sum(axis=1)), pd.DataFrame(np.exp(df.sum(axis=1))).assign(GRP=train.GRP).groupby('GRP').transform(
                         'sum').iloc[:, 0])
    return pred

train_shap = train[coef.Parameter.tolist()].copy()
X_summary = shap.kmeans(train_shap,10)
explainer = shap.KernelExplainer(mw_predict, X_summary)
shap_values = explainer.shap_values(train_shap)
```

**Comment by slundberg** [comment]
Hmmm...could you share a self contained example I can run to debug this?

**Comment by fyang0507** [comment]
same issue detected at my side for a multi-class model.

```python

# X_train, X_test being numpy array
# clf is sklearn model
explainer = shap.KernelExplainer(clf.predict_proba, X_train, link="logit")
shap_values = explainer.shap_values(X_test, nsamples=10)
```

looks like it is a data-specific issue as the progress bar always stopped at similar (but not the same) places. Also if I limit the size of `X_test`(say I pass only a subset) then `shap_values` can be calculated.

**Comment by matheus695p** [comment]
any solution for this?

**Comment by matanost-netop** [comment]
Any advance here? I'm seeing the same issue
