### ISSUE TITLE
Gradient issue

### ISSUE THREAD

**Issue by eladBenedict** [shap/shap#586]
Hi,

I'm trying to run SHAP on our TF model, and am running into the following error:

**ValueError: Shape must be rank 2 but is rank 3 for 'gradients/post_embedding_feature_layer/calibrated_aposteriori_ctr_embedded_and_user_pageview_features/mul_grad/Tile_3' (op: 'Tile') with input shapes: [?,20], [3].**

The background argument (see code below) is a list of ndarrays with the following shapes (pasting just partial data for brevity) - in this case there are 1000 examples:
<type 'list'>: [(1, 1000), (1000, 10), (1000, 0), (1000, 10), (1000, 1522), (1, 1000), (1000, 10), (1000,), (1, 1000), (1, 1000), (1, 1000), (1, 1000), (1, 1000), (1, 1000), (1, 1000), (1, 1000), (1, 1000), (1, 1000), (1, 1000), (1, 1000, 0), (1, 1000), (1, 1000), (1000,), (1000, 0), (1, 1000), (1, 1000), (1000, 27), (1, 1000, 0), (1, 1000), (1, 1000), (1, 1000), (1000,), (1000,), (1000, 10), (1, 1000), (1000, 55), (1, 1000), (1, 1000), (1, 1000), (1000, 10), (1000,), (1000, 0), (1, 1000), (1, 1000), (1000, 25),...]

As you can see, they're shaped in various forms, which our model expects.
Since `e` is created correctly I had hoped that the same data would suffice for shap_values, but it doesn't. 

Can you please shed some light on the data shape(s) expected by shap_values as well as on the cryptic exception?

Thanks!
Elad

Code reference: 
```
import shap
import numpy as np
import tensorflow as tf
import os
import pandas as pd

from p13n.core.config import get_config, load_training_config
from train_serve.pipeline import pipeline_factory
from train_serve.training.data_generator.tf_record_dataset_utils import build_dataset_iterator

pipeline = pipeline_factory.build_model_pipeline('organic-ffm')
pipeline.load(os.path.join('/tmp/oaen_ttype_tage', "scoring"))
decode = pipeline.build_scoring_decode()
load_training_config(label='o_pv_title_signals_ttype_tage', publisher_group='o_a_en')
config = get_config('train')
sess = pipeline.session

with sess.graph.as_default():
    iterator = build_dataset_iterator(input_dir='/tmp/train', decode=decode, io_config=config.io)
    iterator_handle = sess.run(iterator.string_handle())
    feed_dict = {
        pipeline.get_iterator_handle_from_session(): iterator_handle
    }
    output_dict = pipeline.build_scoring_output_dict_from_session()
    input_tensors = [sess.graph.get_tensor_by_name(x + ":0") for x in sess.graph._nodes_by_name if "input" in x]
    input_tensors = [x for x in input_tensors if len(x.shape) > 0]
    background = sess.run(input_tensors, feed_dict=feed_dict)

    e = shap.DeepExplainer((input_tensors,tf.reshape(output_dict['score'],(-1,1))), data=background, session=sess)
    res = e.shap_values(background)
    print(res)
```

Stack trace:
```Traceback (most recent call last):
  File "/Users/elad.benedict/Library/Application Support/IntelliJIdea2018.2/python/helpers/pydev/pydevd.py", line 1664, in <module>
    main()
  File "/Users/elad.benedict/Library/Application Support/IntelliJIdea2018.2/python/helpers/pydev/pydevd.py", line 1658, in main
    globals = debugger.run(setup['file'], None, None, is_module)
  File "/Users/elad.benedict/Library/Application Support/IntelliJIdea2018.2/python/helpers/pydev/pydevd.py", line 1068, in run
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "/Users/elad.benedict/dev/r/Python/Taboola/products/personalization/p13n/train_serve/pipeline/shapSandbox.py", line 30, in <module>
    res = e.shap_values(background)
  File "/Users/elad.benedict/python27/lib/python2.7/site-packages/shap/explainers/deep/__init__.py", line 119, in shap_values
    return self.explainer.shap_values(X, ranked_outputs, output_rank_order)
  File "/Users/elad.benedict/python27/lib/python2.7/site-packages/shap/explainers/deep/deep_tf.py", line 262, in shap_values
    sample_phis = self.run(self.phi_symbolic(feature_ind), self.model_inputs, joint_input)
  File "/Users/elad.benedict/python27/lib/python2.7/site-packages/shap/explainers/deep/deep_tf.py", line 202, in phi_symbolic
    self.phi_symbolics[i] = tf.gradients(out, self.model_inputs)
  File "/Users/elad.benedict/python27/lib/python2.7/site-packages/tensorflow/python/ops/gradients_impl.py", line 596, in gradients
    gate_gradients, aggregation_method, stop_gradients)
  File "/Users/elad.benedict/python27/lib/python2.7/site-packages/tensorflow/python/ops/gradients_impl.py", line 779, in _GradientsHelper
    lambda: grad_fn(op, *out_grads))
  File "/Users/elad.benedict/python27/lib/python2.7/site-packages/tensorflow/python/ops/gradients_impl.py", line 398, in _MaybeCompile
    return grad_fn()  # Exit early
  File "/Users/elad.benedict/python27/lib/python2.7/site-packages/tensorflow/python/ops/gradients_impl.py", line 779, in <lambda>
    lambda: grad_fn(op, *out_grads))
  File "/Users/elad.benedict/python27/lib/python2.7/site-packages/shap/explainers/deep/deep_tf.py", line 287, in custom_grad
    return op_handlers[op.type](self, op, *grads)
  File "/Users/elad.benedict/python27/lib/python2.7/site-packages/shap/explainers/deep/deep_tf.py", line 411, in handler
    return nonlinearity_2d_handler(input_ind0, input_ind1, op_func, explainer, op, *grads)
  File "/Users/elad.benedict/python27/lib/python2.7/site-packages/shap/explainers/deep/deep_tf.py", line 480, in nonlinearity_2d_handler
    out1 = tf.where(tf.abs(tf.tile(delta_in1, dup0)) < 1e-7, tf.zeros_like(out1), out1)
  File "/Users/elad.benedict/python27/lib/python2.7/site-packages/tensorflow/python/ops/gen_array_ops.py", line 8514, in tile
    "Tile", input=input, multiples=multiples, name=name)
  File "/Users/elad.benedict/python27/lib/python2.7/site-packages/tensorflow/python/framework/op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File "/Users/elad.benedict/python27/lib/python2.7/site-packages/tensorflow/python/util/deprecation.py", line 454, in new_func
    return func(*args, **kwargs)
  File "/Users/elad.benedict/python27/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 3155, in create_op
    op_def=op_def)
  File "/Users/elad.benedict/python27/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 1731, in __init__
    control_input_ops)
  File "/Users/elad.benedict/python27/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 1579, in _create_c_op
    raise ValueError(str(e))
ValueError: Shape must be rank 2 but is rank 3 for 'gradients/post_embedding_feature_layer/calibrated_aposteriori_ctr_embedded_and_user_pageview_features/mul_grad/Tile_3' (op: 'Tile') with input shapes: [?,20], [3].
```

**Comment by niloofardadras** [comment]
@eladBenedict hi there.
were you able to solve this?

**Comment by abiudrodas** [comment]
Hi, I have the same issue, have you solve the problem? or is there any workaround?
