### ISSUE TITLE
importing the shap package fails due to cairo dependency

### ISSUE THREAD

**Issue by aehsaeiRH** [shap/shap#719]
I am facing a strange error on the import of the shap package. I'm able to import the shap package successfully within a Jupyter notebook, and also within JupyterLab. However, if I attempt to run the python script itself, I get the following error:

Traceback (most recent call last):
  File "src/models/interpret_model.py", line 16, in <module>
    import shap
  File "/usr/local/anaconda/lib/python3.6/site-packages/shap/__init__.py", line 11, in <module>
    from .plots.summary import summary_plot
  File "/usr/local/anaconda/lib/python3.6/site-packages/shap/plots/summary.py", line 10, in <module>
    import matplotlib.pyplot as pl
  File "/usr/local/anaconda/lib/python3.6/site-packages/matplotlib/pyplot.py", line 115, in <module>
    _backend_mod, new_figure_manager, draw_if_interactive, _show = pylab_setup()
  File "/usr/local/anaconda/lib/python3.6/site-packages/matplotlib/backends/__init__.py", line 62, in pylab_setup
    [backend_name], 0)
  File "/usr/local/anaconda/lib/python3.6/site-packages/matplotlib/backends/backend_cairo.py", line 24, in <module>
    import cairocffi as cairo
  File "/usr/local/anaconda/lib/python3.6/site-packages/cairocffi/__init__.py", line 41, in <module>
    cairo = dlopen(ffi, 'cairo', 'cairo-2', 'cairo-gobject-2')
  File "/usr/local/anaconda/lib/python3.6/site-packages/cairocffi/__init__.py", line 38, in dlopen
    raise OSError("dlopen() failed to load a library: %s" % ' / '.join(names))
OSError: dlopen() failed to load a library: cairo / cairo-2 / cairo-gobject-2
Failed with exit code: 1

**Comment by detrin** [comment]
@aehsaeiRH could you reproduce the error again? I think it should be gone with the newest version v0.42.1

@thatlittleboy CFC
