### ISSUE TITLE
SHAP throwing error for multi-input DeepExplainer

### ISSUE THREAD

**Issue by sambitnandi** [shap/shap#739]
I have created a deep learning model where some inputs and time-dependent which passes through an LSTM and some are time invariant and passes through a MLP architecture with embedding layers. As a result of that my input to the overall model is a list of arrays for the training. The model is running fine and creating expected results but I am facing challenges to generate SHAP values from a List input.

The model is working fine with a List of numpy arrays as a input

Model:
```
def LSTM_emb(m):
    X_datxt,X_input = dat.Xt()
    input_els_cat = []
    cat_els = []
    for i in range(X_input[1].shape[1]):
        input_els_cat.append(Input(shape=(1,)))
        input_dim = int(X_input[1][:,i].max() + 1)    # dimension being set as the unique values in the the column
        e = Flatten()(Embedding(input_dim, max(min(10, int(np.sqrt(input_dim))), 1),
                                          dropout=0.2)(input_els_cat[-1]))
        cat_els.append(e)

    input_els_seg = []
    seg_els = []
    for i in range(X_input[2].shape[1]):
        input_els_seg.append(Input(shape=(1,)))
        seg_els.append(e)

    input_els = input_els_cat + input_els_seg
    aux_els = cat_els + seg_els
    aux_input = concatenate(aux_els)
    layer1a = Dropout(0.2)(Dense(64, activation="sigmoid")(aux_input))
    layer2a = Dropout(0.2)(Dense(64, activation="sigmoid")(layer1a))
    layer3a = Dropout(0.2)(Dense(64, activation="sigmoid")(layer2a))

    ts_inputs = Input(shape=(X_input[0].shape[1],17))

    layer_0 = LSTM(units=16, return_sequences= True)(ts_inputs)
    layer_1 = LSTM(units=16, return_sequences=True)(layer_0)
    layer_2 = LSTM(units = 8)(layer_1)
    layer_3 = Dropout(0.2)(Dense(units=8)(layer_2))

    layer4 = concatenate([layer3a, layer_3])

    layer5 = Dropout(0.2)(Dense(64, activation="sigmoid")(layer4))
    layer6 = Dropout(0.2)(Dense(32, activation="sigmoid")(layer5))
    layer7 = Dropout(0.2)(Dense(16, activation="sigmoid")(layer6))

    out_class = Dense(1, activation="selu", use_bias=False)(layer7)

    ts_model = Model(inputs=input_els + [ts_inputs], outputs=out_class)

    optm = Adam()
    ts_model.compile(optimizer=optm, loss='mse', metrics=['mae'])
    ts_model.summary()
    return ts_model

def train_LSTM_emb(m):
    X_datxt,X_input = m.dat.Xt()
    model = LSTM_emb(m)
    lr_plato = ReduceLROnPlateau(monitor='val_loss', factor=0.2, patience=4,
                                 min_lr=0.000001, verbose=1)
    cp = ModelCheckpoint(filepath=m.path + 'model.h5', verbose=1,
                         save_best_only=True)
    es = EarlyStopping(monitor='val_loss', patience=9, verbose=1)
    model.fit(X_datxt, m.dat.yt(), epochs=10, batch_size=128,
              callbacks=[lr_plato, cp, es],verbose=1)
#    model.load_weights(m.path + 'model.h5')
    return model
```

SHAP looks like this

```
X_datxt, X_input = dat.Xt()
explainer = shap.DeepExplainer(m.model, X_datxt)
shap_values = explainer.shap_values(X_datxt)

```

X_datxt is a list of arrays
```
for i in range(15):
    print(X_datxt[i].shape)

(76716, 1)
(76716, 1)
(76716, 1)
(76716, 1)
(76716, 1)
(76716, 1)
(76716, 1)
(76716, 1)
(76716, 1)
(76716, 1)
(76716, 1)
(76716, 1)
(76716, 1)
(76716, 1)
(76716, 6, 17)
```

Error I am getting:

```
Traceback (most recent call last):

  File "<ipython-input-92-23fe389dc090>", line 3, in <module>
    shap_values = explainer.shap_values(X_datxt)

  File "C:\ProgramData\Anaconda3\lib\site-packages\shap\explainers\deep\__init__.py", line 119, in shap_values
    return self.explainer.shap_values(X, ranked_outputs, output_rank_order)

  File "C:\ProgramData\Anaconda3\lib\site-packages\shap\explainers\deep\deep_tf.py", line 262, in shap_values
    sample_phis = self.run(self.phi_symbolic(feature_ind), self.model_inputs, joint_input)

  File "C:\ProgramData\Anaconda3\lib\site-packages\shap\explainers\deep\deep_tf.py", line 282, in run
    return self.session.run(out, feed_dict)

  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\client\session.py", line 929, in run
    run_metadata_ptr)

  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\client\session.py", line 1137, in _run
    self._graph, fetches, feed_dict_tensor, feed_handles=feed_handles)

  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\client\session.py", line 471, in __init__
    self._fetch_mapper = _FetchMapper.for_fetch(fetches)

  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\client\session.py", line 261, in for_fetch
    return _ListFetchMapper(fetch)

  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\client\session.py", line 370, in __init__
    self._mappers = [_FetchMapper.for_fetch(fetch) for fetch in fetches]

  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\client\session.py", line 370, in <listcomp>
    self._mappers = [_FetchMapper.for_fetch(fetch) for fetch in fetches]

  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\client\session.py", line 258, in for_fetch
    type(fetch)))

TypeError: Fetch argument None has invalid type <class 'NoneType'>
```

**Comment by slundberg** [comment]
Hmmm...what version of SHAP do you have? And do you have the same issue with GradientExplainer?

**Comment by sambitnandi** [comment]
I am using 0.29.3. Gradient explainer is giving the same error :(

**Comment by slundberg** [comment]
I think in `self.session.run(out, feed_dict)` either `out` or `feed_dict` must have a None value in it. You could try printing at that step to see what component is None. Or you can share a minimal notebook example for debugging. Surprising that both explainers have the same issue there.

**Comment by niloofardadras** [comment]
@slundberg hi scott, I have the same issue now. seems like out is none for me. and i believe the issues goes back to phi_symbolic(self, i): function. I am using tensorflow 1.13 and also i pass tf.session to the deep explainer. is there anyway to solve this ?
