### ISSUE TITLE
TypeError: shap_values() got multiple values for argument 'ranked_outputs'

### ISSUE THREAD

**Issue by SeungJinWang** [shap/shap#748]
Dear Scott,
I have three questions(Actually I have a lot of questions, but I will ask next time...)

Q1. I tried to three inputs(categorical, continuous, text) and one output.

final_model = Model([model1.input, model2.input, model3.input], model_merge_out)
explainer = shap.DeepExplainer(final_model, [X_categorical_npary[0:100], X_continuous_npary[0:100], X_padded_docs[0:100]])
shap_values = explainer.shap_values([X_categorical_test_npary[0:100], X_continuous_test_npary[0:100], padded_docs_test[0:100]])
shap.summary_plot(shap_values, [X_categorical_npary[0:100], X_continuous_npary[0:100], X_padded_docs[0:100]], plot_type="bar")

However, when I ran the last code  I got an error as below

shap.summary_plot(shap_values, [X_categorical_npary[0:100], X_continuous_npary[0:100], X_padded_docs[0:100]], plot_type="bar")
Traceback (most recent call last):

  File "<ipython-input-26-0121926afd66>", line 1, in <module>
    shap.summary_plot(shap_values, [X_categorical_npary[0:100], X_continuous_npary[0:100], X_padded_docs[0:100]], plot_type="bar")

  File "C:\ProgramData\Anaconda3\lib\site-packages\shap\plots\summary.py", line 75, in summary_plot
    num_features = (shap_values[0].shape[1] if multi_class else shap_values.shape[1])

AttributeError: 'list' object has no attribute 'shape'

Q2. As above, whenever I run this kinds of multiple inputs model, I should get list type of "shap_values". So, I should convert list to numpy array type, right?

Q3. When I tried to use two inputs as below

final_model12 = Model([model1.input, model2.input], model_merge_out12)
final_model12.compile(optimizer='adam', loss='mae', metrics=['mse', 'mae', 'mape'])
history12 = final_model12.fit([X_categorical, X_continuous], Y_los, batch_size=64, epochs= 5 , verbose=1)

explainer_model12 = shap.DeepExplainer(final_model12, [X_categorical_npary[:100], X_continuous_npary[:100]])
shap_values_model12 = explainer_model12.shap_values(X_categorical_test_npary[0:100], X_continuous_test_npary[:100], ranked_outputs=None, output_rank_order='max')
shap.summary_plot(shap_values_model12, [X_categorical_npary[0:100], X_continuous_npary[0:100]], plot_type="bar")

Also, I got an error as below

TypeError: shap_values() got multiple values for argument 'ranked_outputs'

Thank you for your time.

**Comment by detrin** [comment]
@SeungJinWang Ad Q1 it is clearly wong use of shap, please have a look at documentation. Ad Q2 list or numpy.ndarray should be fine or I don't understand the question. Ad Q3 Could you please try to reproduce the error now with newest version of shap and if you ran into that error could you post the whole error log?? If you no longer have any of those issues we could close the issue.
