### ISSUE TITLE
CatBoost with nan values not supported

### ISSUE THREAD

**Issue by lrq3000** [shap/shap#761]
I just tried the very last commit from the github, and I tried to use shap on a catboost classifier model with categorical features and float ones, and with missing, nan values in some of the floats columns. Shap is unfortunately choking.

Here is my code:
```
explainer = shap.TreeExplainer(model, X_train)
shap_values = explainer.shap_values(X_train)
```

Here is the output:
```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-105-462755477be2> in <module>
----> 1 explainer = shap.TreeExplainer(model, X_train)
      2 shap_values = explainer.shap_values(X_train)

~\Anaconda3\lib\site-packages\shap\explainers\tree.py in __init__(self, model, data, model_output, feature_dependence)
     96         else:
     97             self.data = data
---> 98         self.data_missing = None if self.data is None else np.isnan(self.data)
     99         self.model_output = model_output
    100         self.feature_dependence = feature_dependence

TypeError: ufunc 'isnan' not supported for the input types, and the inputs could not be safely coerced to any supported types according to the casting rule ''safe''
```

If I use the `approximate=True` argument for `explainer.shap_values()`, I get the following error:

```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-137-3e443042e22d> in <module>
----> 1 explainer = shap.TreeExplainer(model)
      2 shap_values = explainer.shap_values(X_train2, approximate=True)

~\Anaconda3\lib\site-packages\shap\explainers\tree.py in __init__(self, model, data, model_output, feature_dependence)
    100         self.feature_dependence = feature_dependence
    101         self.expected_value = None
--> 102         self.model = TreeEnsemble(model, self.data, self.data_missing)
    103 
    104         assert feature_dependence in feature_dependence_codes, "Invalid feature_dependence option!"

~\Anaconda3\lib\site-packages\shap\explainers\tree.py in __init__(self, model, data, data_missing)
    628             self.dtype = np.float32
    629             cb_loader = CatBoostTreeModelLoader(model)
--> 630             self.trees = cb_loader.get_trees(data=data, data_missing=data_missing)
    631             self.tree_output = "log_odds"
    632             self.objective = "binary_crossentropy"

~\Anaconda3\lib\site-packages\shap\explainers\tree.py in get_trees(self, data, data_missing)
   1202 
   1203             # load the per-tree params
-> 1204             depth = len(self.loaded_cb_model['oblivious_trees'][tree_index]['splits'])
   1205 
   1206             # load the nodes

TypeError: object of type 'NoneType' has no len()
```

I also tried with a KernelExplainer instead of TreeExplainer, I get a similar but not exactly same error:

Code:
```
explainer = shap.KernelExplainer(model.predict_proba, X_train)
shap_values = explainer.shap_values(X_train)
```

Error:
```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-103-12524d6e96e8> in <module>
      4 explainer = shap.KernelExplainer(model.predict_proba, X_train)
----> 5 shap_values = explainer.shap_values(X_train)
      6 #shap_values = model.get_feature_importance(catboost.Pool(X_train, y_train, cat_features=categorical_columns), type='ShapValues')
      7 

~\Anaconda3\lib\site-packages\shap\explainers\kernel.py in shap_values(self, X, **kwargs)
    207                 if self.keep_index:
    208                     data = convert_to_instance_with_index(data, column_name, index_value[i:i + 1], index_name)
--> 209                 explanations.append(self.explain(data, **kwargs))
    210 
    211             # vector-output

~\Anaconda3\lib\site-packages\shap\explainers\kernel.py in explain(self, incoming_instance, **kwargs)
    232         # find the feature groups we will test. If a feature does not change from its
    233         # current value then we know it doesn't impact the model
--> 234         self.varyingInds = self.varying_groups(instance.x)
    235         if self.data.groups is None:
    236             self.varyingFeatureGroups = np.array([i for i in self.varyingInds])

~\Anaconda3\lib\site-packages\shap\explainers\kernel.py in varying_groups(self, x)
    424                         continue
    425                     x_group = x_group.todense()
--> 426                 num_mismatches = np.sum(np.invert(np.isclose(x_group, self.data.data[:, inds], equal_nan=True)))
    427                 varying[i] = num_mismatches > 0
    428             varying_indices = np.nonzero(varying)[0]

<__array_function__ internals> in isclose(*args, **kwargs)

~\Anaconda3\lib\site-packages\numpy\core\numeric.py in isclose(a, b, rtol, atol, equal_nan)
   2267     y = array(y, dtype=dt, copy=False, subok=True)
   2268 
-> 2269     xfin = isfinite(x)
   2270     yfin = isfinite(y)
   2271     if all(xfin) and all(yfin):

TypeError: ufunc 'isfinite' not supported for the input types, and the inputs could not be safely coerced to any supported types according to the casting rule ''safe''
```

Any help on this would be greatly appreciated! Thank you in advance!

**Comment by kylercape** [comment]
I had the same problem and fixed it by wrapping the inputs in `catboost.Pool`.
For example:

    shap_values = explainer.shap_values(Pool(X_train, cat_features=np.arange(13)))

**Comment by harshal-c** [comment]
@kylercape were you able to get it working when using Pool with KernelExplainer?

**Comment by harshalchaudhari35** [comment]
@kylercape were you able to get it working with Pool when using KernelExplainer?

**Comment by ibuda** [comment]
Since I see a very familiar error
```
TypeError: object of type 'NoneType' has no len()
```
maybe installing from github will solve it, as it helped in other cases:
```
pip install git+https://github.com/slundberg/shap
```

**Comment by harshalchaudhari35** [comment]
Hi @ibuda thanks for the quick response. I suppose my error is more to do with when I'm passing in categorical variables. you can refer to my original issue #1014 for more details on what I'm trying to acheive.

**Comment by ibuda** [comment]
That also aligns with what I suggest. Take a look at #757, categorical features are definitely the reason, but as I mentioned there, taking the oldest version code from github solves the issues.

**Comment by harshalchaudhari35** [comment]
The example you use in your issue is with TreeExplainer, in my case I'm trying to use the KernelExplainer. Even after installing from git. The issue still persists. 
I cannot use 
```
shap_values = KernelExplainer(model.predict, X_train).shap_values(Pool(X_train, cat_features=cat_features))
```

**Comment by ibuda** [comment]
@harshalchaudhari35 can you please provide some code sample, I'll look into it.

**Comment by harshalchaudhari35** [comment]
@ibuda sure 
```
import catboost
from catboost import *
import shap
from catboost.datasets import *



train_df, test_df = catboost.datasets.amazon()
y = train_df.ACTION
X = train_df.drop('ACTION', axis=1)
cat_features = list(range(0, X.shape[1]))
model = CatBoostClassifier(iterations=300, learning_rate=0.1, random_seed=12)
model.fit(Pool(X, y, cat_features=cat_features), verbose=False, plot=False)
explainer = shap.KernelExplainer(model.predict, Pool(X, cat_features=cat_features)).shap_values(Pool(X, cat_features=cat_features))
```
Error Traceback
Traceback (most recent call last):
  File "temp.py", line 17, in <module>
    explainer = shap.KernelExplainer(model.predict, Pool(X, cat_features=cat_features)).shap_values(Pool(X, cat_features=cat_features))
  File "/lib/python3.8/site-packages/shap/explainers/kernel.py", line 96, in __init__
    self.data = convert_to_data(data, keep_index=self.keep_index)
  File "/lib/python3.8/site-packages/shap/common.py", line 178, in convert_to_data
    assert False, "Unknown type passed as data object: "+str(type(val))
AssertionError: Unknown type passed as data object: <class 'catboost.core.Pool'>

Let me know if you are able to reproduce this.
shap version taken from git 
catboost==0.20.2

**Comment by harshalchaudhari35** [comment]
@ibuda were you able to replicate this?
