### ISSUE TITLE
Importing shap gives error

### ISSUE THREAD

**Issue by jamescastells** [shap/shap#923]
When attempting to import shap, the next error appears:

`Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/james/.local/lib/python3.6/site-packages/shap/__init__.py", line 8, in <module>
    from .explainers.kernel import KernelExplainer, kmeans
  File "/home/james/.local/lib/python3.6/site-packages/shap/explainers/kernel.py", line 11, in <module>
    from sklearn.cluster import KMeans
  File "/home/james/.local/lib/python3.6/site-packages/sklearn/cluster/__init__.py", line 6, in <module>
    from ._spectral import spectral_clustering, SpectralClustering
  File "/home/james/.local/lib/python3.6/site-packages/sklearn/cluster/_spectral.py", line 16, in <module>
    from ..neighbors import kneighbors_graph, NearestNeighbors
  File "/home/james/.local/lib/python3.6/site-packages/sklearn/neighbors/__init__.py", line 17, in <module>
    from ._nca import NeighborhoodComponentsAnalysis
  File "/home/james/.local/lib/python3.6/site-packages/sklearn/neighbors/_nca.py", line 22, in <module>
    from ..decomposition import PCA
  File "/home/james/.local/lib/python3.6/site-packages/sklearn/decomposition/__init__.py", line 19, in <module>
    from ._online_lda import LatentDirichletAllocation
ImportError: cannot import name 'LatentDirichletAllocation'
`

**Comment by slundberg** [comment]
Can you import sklearn? It looks like an issue with your sklearn install.

**Comment by jamescastells** [comment]
Yes, importing sklearn gives no problems.

**Comment by slundberg** [comment]
what about `from sklearn.cluster import KMeans`?

**Comment by jamescastells** [comment]
Interesting, that gives the same error. What would you suggest?

**Comment by slundberg** [comment]
It means KMeans is not working inside sklearn, so I would start by updating sklearn, testing different versions, and checking online. Good luck!
