### ISSUE TITLE
'None' gradient wrt to the input using TF2, Embeddings and GradientExplainer.

### ISSUE THREAD

**Issue by jacopodisi** [shap/shap#965]
Hi! I get this error using GradientExplainer with the Embedding layer of tf.keras.

```
Traceback (most recent call last):
  File "C:/Users/disimone/PycharmProjects/shap/notebooks/deep_explainer/Keras LSTM for IMDB Sentiment Classification.py", line 71, in <module>
    shap_values = explainer.shap_values(x_test[:10])
  File "C:\Users\disimone\PycharmProjects\shap\shap\explainers\gradient.py", line 106, in shap_values
    return self.explainer.shap_values(X, nsamples, ranked_outputs, output_rank_order, rseed, return_variances)
  File "C:\Users\disimone\PycharmProjects\shap\shap\explainers\gradient.py", line 288, in shap_values
    grad = [np.concatenate([g[l] for g in grads], 0) for l in range(len(X))]
  File "C:\Users\disimone\PycharmProjects\shap\shap\explainers\gradient.py", line 288, in <listcomp>
    grad = [np.concatenate([g[l] for g in grads], 0) for l in range(len(X))]
  File "<__array_function__ internals>", line 6, in concatenate
ValueError: zero-dimensional arrays cannot be concatenated
```

I have this error because `tf.GradientTape` in `_TFGradientExplainer` return `None` as gradient with respect to the input.

https://github.com/slundberg/shap/blob/a270b811a8147e12655842ddeb226b4ebae39f72/shap/explainers/gradient.py#L209

One possible solution would be to compute the SHAP values of the input of the LSTM layer (the output of the Embedding layer), but its a dirty fix. Do you have any other idea on how to fix this issue?

As a 'minimal' working example I modified the notebook 'Keras LSTM for IMDB Sentiment Classification'. Below a link to the Colab Notebook.

https://colab.research.google.com/drive/1bSI4XoHBXcxaj2n6gaZu2xaigbhuiezz

**Comment by slundberg** [comment]
Thanks for sharing! @imatiach-msft is working on fixing up DeepExplainer to work in TF2, and since DeepExplainer can handle non-differentiable functions it will be the easiest fix for this. However, I would like to have GradientExplainer support embeddings by essentially automatically using the output of the embeddings layer as the input to the model, then summing up the contributions across the embedding dimensions and dropping that sum back onto the original model inputs.

This summing can be done manually right now, but the automatic version of this for TF2 in eager mode is hard since I don't really know how to "run" sub portions of a graph in TF2 eager mode. If anyone has insight on how to do that I would be grateful for help. I spent a day on it a week ago and didn't get to a solution before I needed to move on.

**Comment by DavideStenner** [comment]
i don't know if this can help but:
https://colab.research.google.com/drive/1tTiOgJ7xvy3sjfiFC9OozbjAX1ho8WN9?usp=sharing
this is an example to calculate gradient of embedding in bert model.

**Comment by crisz** [comment]
I suppose the same error is reproduced on the torch version, with the following error message:

> RuntimeError: element 0 of tensors does not require grad and does not have a grad_fn
